### ISSUE TITLE
beforeDestroy hook: "TypeError: a.replace is not a function"

### ISSUE THREAD

**Issue by maximus1010101** [tinymce/tinymce-vue#1]
I change the route in the vue-router, and the component is automatically destroyed with this error:

Error in beforeDestroy hook: "TypeError: a.replace is not a function"
found in
---> <Editor>

I use component:
<editor api-key="..." :init="config" v-model="content" @input="updateData"></editor>

**Comment by fyrkant** [comment]
Hmm, that doesn't sound good! Can you provide some more code on how your app looks like? Maybe set up a simple example in a github repo that I can take a look at?

**Comment by maximus1010101** [comment]
Hello, I found the beginning of the problem. It's in the plugin "fontselect". When I change the active route in the vue-router, the <Editor> is destroyed and you throw this error. It also is throwed, when the update component with live reload.

**Comment by fyrkant** [comment]
@maximus1010101 
Sorry for the wait, got around to take a look at this today and it seems to be a bug in TinyMCE itself, not the vue package. I will keep this open until we have fixed it in TinyMCE!

**Comment by maximus1010101** [comment]
Thank you very much for the answer.

I'll wait for the solution.

**Comment by fyrkant** [comment]
Hi @maximus1010101 !
This should be fixed in the newly released 4.7.10 version of TinyMCE, can you try it out?

**Comment by maximus1010101** [comment]
Hello, thanks for the help!
Unfortunately this does not work for me.

I updated "@tinymce/tinymce-vue" package to v1.0.3 and "tinymce" to v4.7.10 and reinstall packages. Now I see the same error as before.

**Comment by fyrkant** [comment]
Hmm, that's no good, I'll look into this some more then.

**Comment by fyrkant** [comment]
@maximus1010101 
Are you sure you are using TinyMCE version 4.7.10? You can check it by opening up the console and writing `tinymce.minorVersion`.

**Comment by maximus1010101** [comment]
Sorry, this is my mistake!
I updated the package "tinymce" and did not see that "vue-tinymce" downloaded the package from the Internet, and did not use the package installed in the NPM

**Comment by fyrkant** [comment]
So you don't have the issue anymore with the latest 4.7.10 version?
