### ISSUE TITLE
Editor becomes unusable with keep-alive

### ISSUE THREAD

**Issue by TheJuki** [tinymce/tinymce-vue#10]
The editor body becomes white (No text) and uneditable when navigating to another keep-alive page and then back to the original keep-alive page with the editor. The source code popup shows the original HTML code.

Example: https://codesandbox.io/s/qq0zw6o5q

**Comment by TheJuki** [comment]
```
activated() {
    tinymce.EditorManager.execCommand('mceRemoveEditor', false, 'myEditor')
    tinymce.EditorManager.execCommand('mceAddEditor', false, 'myEditor')
  }
```
This seems to work. Probably not the best solution but it works.

**Comment by TheJuki** [comment]
It keeps views “alive”. This means views are deactivated and activated instead of destroyed when navigating to another page. This is useful when moving from one view to another without losing information on the unsaved form with the editor.

**Comment by fyrkant** [comment]
Seems like the problem is that the iframe that the TinyMCE content is inside of just gets removed when you change route, regardless of keep-alive. You can see the same problem in this example, if you start playing the video and change page and then change back the video restarts: https://codesandbox.io/s/1zlyj95q33

**Comment by TheJuki** [comment]
Yes. That is the problem. So, the only way to fix this is to re-initialize the editor?

**Comment by fyrkant** [comment]
Yes I think so. But maybe you can get the think you want, that the editor keeps it's value even when you change route without using keep-alive? Is is possible to drag out the v-model value to the base component so it stays up to date even when routes change? 🤔

**Comment by TheJuki** [comment]
No. It would not work in my case, I need the component (Which the editor component .vue file in my example is actually just a view) to contain the model data.

**Comment by fyrkant** [comment]
Ok, then I think re-initializing the editor is the only way to make it work.

**Comment by TheJuki** [comment]
Okay. Thanks!

**Comment by m-kiruba** [comment]
I had the same issue with keep-alive. I sorted this issue with having v-if on <tinymce-vue-editior> component and used a boolean variable call 'active' and set true on activated lifecycle hook and set false on deactivated Lifecycle Hook.

`<editor v-if="active" v-model="description" :init="tinymce_init"></editor>

deactivated() {
    this.active = false;
  },
  activated() {
    this.active = true;
  },
`

**Comment by RakibSiddiquee** [comment]
The following code works for me...

<editor v-if="active" v-model="description" :init="tinymce_init"></editor>

data(){
  return {
   active: false,
  }
},

mounted(){
  this.active= true;
},

destroyed(){
  this.active= false;
}
