### ISSUE TITLE
Setting the editor model to `null` does not clear the editor content

### ISSUE THREAD

**Issue by Shuyinsama** [tinymce/tinymce-vue#100]
Currently we use the tinymce-vue component to allow users to add content to their site. We have implemented a multilingual system where the user creates a page and adds some content to, for example, the english content of the page.

Now the user also wants to add content for the German version of this page and switches the language in a reactive manner (they click in a radio group of allowed languages to switch to that language for that page.

Now when the initial data object returns from the server the content for the german language comes back as`null` since nothing has been added yet (and also might never be added)

So whenever the user switches from english to german, the english content stays there because the code doesn't do anything when the data is `null`

**Please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox.io**
[https://codesandbox.io/embed/tinymcevue-f2wvu](https://codesandbox.io/embed/tinymcevue-f2wvu)
In this sandbox you can click on the buttons in the order they are presented. The editor is initialised with data. The first button will set that data to an empty string.
The second button will set the data back to a actual value string.
The third button will set that data to `null` upon which nothing happens

**What is the expected behavior?**
Just like providing an empty string I would expect null to clear the editor content.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
tested on the following versions:
`@tinymce/tinymce-vue:  2.1.0` and `@tinymce/tinymce-vue:  3.0.1`

Chrome (76.0.3809.132), Firefox (68.0.2), Edge 18

**Comment by Shuyinsama** [comment]
Hi @SimonFc 

Yes Vue can handle null values and is normal to use within data objects or models.
I've noticed though that the code for this plugin uses a watcher that always expects a string as the value ([Link to code](https://github.com/tinymce/tinymce-vue/blob/master/src/main/ts/Utils.ts#L99))

Which would be logical to think since the editor only expects a string as content, but the use case for having null in our case is that we dynamically switch between content of different languages.
Sometimes a user will not add content for 1 specific language leaving the data object to be null since we also don't want to save a empty string to the server.

It would be nice if the tinymce editor would check for a null value and just clears the editor content, instead of replacing the value with an empty string.

I am happy to make a pull request if preferred but if I am correct I would need to edit both this repo and the base tinymce code.

**Comment by SimonFc** [comment]
The change would be in tinymce-vue where we would place `typeof value === "string" ? value : ""` or something similar, but I still think that this is something that should fall on the user of tinymce-vue.

But again, is it a common practice in the Vue ecosystem for components to default to whatever their empty value might be when they receive null? Be it color pickers or input fields. I've found it more common that an invalid value would produce an error (or do nothing) since the type is invalid.

**Comment by Shuyinsama** [comment]
We have decided to fix this in our project in the mean time. I am still interested in seeing if the vue component benefits from this code. 

It is not exactly a Vue thing to handle null values. This is a part of javascript, and for me the logical explanation would be to clear the editor whenever a null value is passed. Because, just like an empty string, null is basically just an empty object and in the case of this editor should behave the same like a empty string.

Unless somebody else has arguments on why tinymce-vue should not handle this kind of thing I might still be open to make a PR for this.

And for completeness our solution was to get rid of the `v-model` attribute and fall back to the `v-on:input` and `value` attributes to basically do our own logic.

```
<html-editor id="editor-${componentIndex}"
             :init="{
	             branding: false,
	             convert_urls: false,
	             statusbar: false,
	             menubar: 'edit insert view format table tools'
             }"
             v-on:input="(value) => {
                if (typeof value === 'string' && value.trim().length > 0) {
                    ${modelPropertyName} = value;
                    return;
                }
                ${modelPropertyName} = null;
			}"
             :value="${modelPropertyName} == null ? '' : ${modelPropertyName}"
             plugins="link image autoresize code fullscreen table lists"
             toolbar="undo redo | formatselect | bold italic | alignleft aligncenter alignright | link image | numlist bullist | fullscreen code" ${attributes}></html-editor>
```
