### ISSUE TITLE
How to get the word count from TinyMCE

### ISSUE THREAD

**Issue by phuclh** [tinymce/tinymce-vue#101]
As the docs say, we can get the word count from an API call: https://www.tiny.cloud/docs/plugins/wordcount/

But I don't know how to access the editor instance, I tried to set an ID and access it, but it didn't work. Below is my code:

```
<tinymce-editor api-key=""
                             v-model="content"
                             id="'editor'">
</tinymce-editor>
```

```
import Editor from '@tinymce/tinymce-vue';
....
components: {
            'tinymce-editor': Editor
        },
```

I tried to access the ID like this: `Editor.get('editor')`, and I got an error:
`TypeError: __WEBPACK_IMPORTED_MODULE_1__tinymce_tinymce_vue__.a.get is not a function`

**Comment by SimonFc** [comment]
One way to do that is through the [setup](https://www.tiny.cloud/docs/configure/integration-and-setup/#setup) method:
```
<editor
  :init="{
    setup: (editor) => {
      
    }
  }"
  ></editor>
```
Alternatively, all event handlers get invoked with the editor as the second argument [Event binding](https://github.com/tinymce/tinymce-vue#event-binding)

**Comment by phuclh** [comment]
@SimonFc Thank you, but how can I get the instance outside the init prop.

My situation is I call a ajax method to save my content through a button. I want to run `tinymce.get('editor').save();` to discard TinyMCE autosave so it doesn't show the alert popup.

**Comment by SimonFc** [comment]
Something like this?
```
<template>
  <Editor @onInit="handleInit" />
</template>

<script>
  import 'tinymce/tinymce';
  import 'tinymce/themes/silver';
  import Editor from '@tinymce/tinymce-vue';

  export default {
    name: 'app',
    components: { Editor },
    methods: {
      handleInit: function (e, editor) {
        this.editorInstance = editor;

        console.log(this.editorInstance);
      }
    },
    data: function () {
      return {
        editorInstance: undefined
      }
    }
  }
</script>
```

**Comment by phuclh** [comment]
@SimonFc  You're awesome!!
