### ISSUE TITLE
How to access tinymce object?

### ISSUE THREAD

**Issue by r94ever** [tinymce/tinymce-vue#102]
Hi,

Please anyone can tell me how to access the tinymce object, I need to insert some content into editor by using `insertContent` method but have no idea how to access the tinymce object.

This is my code:

```
<script>
import Editor from '@tinymce/tinymce-vue';

export default {
  components: {
    'tinymce-editor': Editor,
  },

  methods: {
    insertIntoEditor() {
      tinymce.... // I want to use tinymce object here
    }
  }
}
</script>
```

Thanks for any help! :)

**Comment by r94ever** [comment]
I have just found the way to access it. Please close this issue :D

**Comment by xlcrr** [comment]
Why not post the solution?

console.log(tinycme); works

How did you insert content? I will post the answer then I find it

**Comment by xlcrr** [comment]
Here, took about 500 ms to copy and paste this and save others searching through the docs

```
add(content) {
   tinymce.activeEditor.insertContent(content);
}
```

**Comment by r94ever** [comment]
@xlcrr sorry since I think my problem is cause by I didn't research in document so nobody will like me 😁
