### ISSUE TITLE
Unable to load tinymce myself vs. cloud

### ISSUE THREAD

**Issue by brianhogg** [tinymce/tinymce-vue#11]
I've got tinymce loading outside of a vue component via the tinymce npm package, ie.

```
import tinymce from 'tinymce/tinymce';
import 'tinymce/themes/modern/theme';

import 'tinymce/plugins/paste';
import 'tinymce/plugins/media';
import 'tinymce/plugins/textcolor';
import 'tinymce/plugins/lists';
import 'tinymce-line-height-plugin/lineheight/plugin';
import 'tinymce/plugins/link';
import 'tinymce/plugins/table';
import 'tinymce/plugins/hr';
import 'tinymce/plugins/print';
import 'tinymce/plugins/autosave';
import 'tinymce/plugins/fullscreen';
import 'tinymce/plugins/image';

tinymce.init({
    selector: '.tinymce',
    theme: 'modern',
    menubar: false,
    plugins: ['paste', 'image', 'media', 'textcolor', 'lists', 'lineheight', 'link', 'table', 'hr', 'print', 'autosave', 'fullscreen', 'image'],
    skin_url: '/tinymce/skins/lightgray',
    branding: false,
    toolbar: [
        'bold italic underline removeformat | strikethrough superscript subscript | fontsizeselect | backcolor | bullist numlist | styleselect | lineheightselect',
        'link image media table hr | fullscreen undo redo print restoredraft'
    ]
});
```

but when I try to use `<editor>` with a Vue component with something like:

`<editor id="evidence-editor" class="tinymce">`

tinymce-vue isn't detecting that I'm attaching tinymce myself via the class. Also tried changing the selector to use the `evidence-editor` ID instead, but regardless it'll attached tinymce twice with one displaying the This domain is not registered with TinyMCE Cloud" error. I even tried setting `window.tinymce = tinymce` to satisfy the `getTinymce` function within tinymce-vue.js.

 Is there something I'm missing to be able to load tinymce myself via the npm package?

**Comment by fyrkant** [comment]
You don't have to run the tinymce.init function, you only have to make tinymce globally accessible. The `<editor></editor>` does the initilization for you.

**Comment by fyrkant** [comment]
You also have to include the skin files correctly.

**Comment by brianhogg** [comment]
Thanks for the quick reply @fyrkant! I tried just having it accessible but it was still showing the TinyMCE cloud error. I ended up instead fetching the data via `tinymce.activeEditor.getContent()` instead from within the vue component.

**Comment by fyrkant** [comment]
I think you need to change the 
```js
import tinymce from 'tinymce/tinymce';
```
to 
```js
import 'tinymce/tinymce';
```
to make it global.

**Comment by brianhogg** [comment]
Looks like that did the trick, along with ensuring the module/plugin is loaded before Vue is initialized. Thanks!

**Comment by Epskampie** [comment]
As mentioned on https://github.com/tinymce/tinymce-react#loading-tinymce-by-yourself 

To opt out of using TinyMCE cloud you have to make TinyMCE globally available yourself. This can be done either by hosting the tinymce.min.js file by youself and adding a script tag to you HTML or, if you are using a module loader, installing TinyMCE with npm. For info on how to get TinyMCE working with module loaders check out this page in the documentation: https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/

**Comment by rajneeshm49** [comment]
Hii @fyrkant and @brianhogg 
As u guys discussed. In order not to load it from cloud and no need to call tinymce.init, here is how Iam doing it.   

`<template>
    <editor :init="initValue" id="evidence-editor" class="tinymce"></editor>
</template>

<script>
import Editor from "@tinymce/tinymce-vue";

import 'tinymce';
import 'tinymce/themes/modern/theme';

import 'tinymce/plugins/link';

export default {
  name: "alchemy-tinymce-editor",
  components: {
    editor: Editor
  },
  data() {
    return {
      inputValue: null,
      initValue: {
        selector: ".tinymce",
        theme: 'modern',
        menubar: false,
        plugins: ['link'],
        skin_url: '/skins/lightgray',
        branding: false,
        toolbar: [
            'bold italic underline removeformat'
        ]
      }`
Am I doint something wrong in this. Its still not loading
