### ISSUE TITLE
Set content_style

### ISSUE THREAD

**Issue by murilohorstmann** [tinymce/tinymce-vue#110]
how do i use the **content_style** option?

**Comment by SimonFc** [comment]
https://www.tiny.cloud/docs/configure/content-appearance/#content_style
```
<editor
  [init]="{
    content_style: 'div { margin: 10px; border: 5px solid red; padding: 3px; }'
  }"
></editor>
```

**Comment by murilohorstmann** [comment]
i tried this exemple but didn't work, the style was not applied on body

**Comment by SimonFc** [comment]
It does? [CodeSandbox](https://codesandbox.io/s/tinymcevue-w8ktd?fontsize=14&hidenavigation=1&theme=dark) If you check the head-element of TinyMCE's iframe you'll see a style-element containing the css. Let me know if you got any questions!
