### ISSUE TITLE
[Vue warn]: Error in beforeDestroy hook: "TypeError: element.dom(...).removeEventListener is not a function"

### ISSUE THREAD

**Issue by huhaoGitHub** [tinymce/tinymce-vue#111]
**I use TinyMCE Vue with component and build into an app successfully. But When I leave the component,TinyMCE Vue starts to report error**

this error is:
`[Vue warn]: Error in beforeDestroy hook: "TypeError: element.dom(...).removeEventListener is not a function"

found in
<Editor>
       <TinymceEditor> at src/components/Editor/TinymceEditor.vue

`

Element not found
`
var unbind = function (element, event, handler, useCapture) {
      element.dom().removeEventListener(event, handler, useCapture);
    };
`

**Please tell me why does this happen?**

**Comment by SimonFc** [comment]
Hi! Difficult to say without knowing how use use tinymce-vue. Is it possible for you to set up a reproduction of your issue [here](https://codesandbox.io/s/9y95z5m40y?fontsize=14)?

**Comment by XDfield** [comment]
same here.I don't have this problem in the development environment, but the production environment always appears.

**Comment by SimonFc** [comment]
@XDfield Does this happen when you "leave" the component as well, as @huhaoGitHub describe?
Is it possible for you to describe how to replicate this issue or to setup a example project? Thanks!

**Comment by jscasca** [comment]
@XDfield @huhaoGitHub if you have a replication case I can reopen the issue. In the meantime, I'll go ahead and close this.
