### ISSUE TITLE
How to reinitialize tinymce

### ISSUE THREAD

**Issue by gomezmark** [tinymce/tinymce-vue#112]
Hi,

I'm trying to reuse the compont with tinymce.
But when I'm re-open the component, it became empty.

![image](https://user-images.githubusercontent.com/19304789/70383373-f04c8180-19a7-11ea-9b3e-9e6d3bfd905d.png)

![image](https://user-images.githubusercontent.com/19304789/70383381-0c502300-19a8-11ea-8485-f99b377494a8.png)

on my vue component

```
<template>
  <div>
    <v-dialog 
			v-model="dialog" persistent
			fullscreen 
      hide-overlay 
      transition="dialog-bottom-transition">
			<v-card tile>
        <v-toolbar
          flat
          >
          <v-btn icon 
            @click="dialog = false">
            <v-icon>chevron_left</v-icon>
          </v-btn>
          <v-toolbar-title>Edit Content</v-toolbar-title>
          <v-spacer></v-spacer>
          <v-toolbar-items>
            <v-btn 
              flat
              color="secondary"
              @click="setTextEditorContent">Save</v-btn>
          </v-toolbar-items>
        </v-toolbar>
				<v-card-text class="relative pa-0">
          <!-- <vue-mce 
            v-model="value"
            :config="config"/> -->
          <div :style="`height:${height}`">
            <tinymce-editor
              ref="editor"
              api-key="h3j674uac1gnsid8q3er8ltrt99qi2rnai7lp5wkeg025br7" 
              v-model="value"
              :init="config">
            </tinymce-editor>
          </div>

				</v-card-text>
			</v-card>
    </v-dialog>
  </div>
</template>

<script>
import Editor from '@tinymce/tinymce-vue';
// commonjs require
// NOTE: default needed after require

export default {
  data () {
    return {
      value: null,
      dialog: false,
      height: 800,
      config: {
        automatic: true,
        height: 800,
        fontsize_formats: "8px 10px 12px 14px 16px 18px 20px 22px 24px 26px 39px 34px 38px 42px 48px",
        plugins: 'print preview fullpage powerpaste searchreplace autolink table image media link',
        toolbar1: 'formatselect fontsizeselect | bold italic strikethrough forecolor backcolor link | alignleft aligncenter alignright | insertfile image link',
        table_toolbar: "tableprops tabledelete | tableinsertrowbefore tableinsertrowafter tabledeleterow | tableinsertcolbefore tableinsertcolafter tabledeletecol"
      }
    }
  },
  components: {
    'tinymce-editor': Editor // <- Important part
  },
  methods: {
    open (value) {
			let vm = this
      this.dialog = true
      vm.value = value
      console.log(value)
      console.log(this.$refs.editor)
			vm.$forceUpdate()
			return new Promise((resolve, reject) => {
        this.resolve = resolve
        this.reject = reject
      })
    },
    closeDialog () {
			this.dialog = false
		},
		setTextEditorContent () {
      console.log(this.$refs.editor)
			this.resolve(this.value)
      this.dialog = false
		},
  },
  mounted () {
    this.height = window.innerHeight - 64
  }
}
</script>

<style>
</style>
```

**Comment by SimonFc** [comment]
Hi!
I think this is due to a common issue with TinyMCE in iframe mode(try inline mode and it'll probably work just fine). Whenever an iframe gets moved/detached from the DOM it'll re-render - this is simply native iframe behaviour. This will break TinyMCE and unfortunately there's nothing we can do about it. As of now, it's up to the user to either make sure that doesn't happen or to manually tear down/set up TinyMCE(tinymce-vue) whenever necessary.

You should be able to use one of the standard workaround to achieve this. See if any of the ones described [here](https://michaelnthiessen.com/force-re-render/) works for you!

**Comment by gomezmark** [comment]
Hi @SimonFc 

Thank you for your response. 
That's what I have noticed. But the TinyMCE has method for destroy but do not have for init.

However, I did work around I think it is working fine.
I declared it as a global component. (_not sure if it is best solution_).

Thanks.

**Comment by Rocksride** [comment]
Hi, @gomezmark . Could you share your solution, a have the same problem. Thank you.

**Comment by gomezmark** [comment]
Hi @Rocksride 

I created a component and used it as global component

on my layout.js
```
 <v-app>
   <editor/>
 </v-app>
```

on my Editor.vue
this is where I put the tinymce, then showing the component using event bus + Promise

```
<template>
  <div>
    <v-dialog 
	v-model="dialog" persistent
	fullscreen 
        hide-overlay 
        transition="dialog-bottom-transition">
	<v-card tile>
            <tinymce-editor 
              v-model="value"
              :init="config">
            </tinymce-editor>
          </div>
	</v-card-text>
       </v-card>
    </v-dialog>
  </div>
</template>


...
...
mounted () {
 eventHub.$on('open-editor', (data, resolve) => { this.open(data, resolve) })
}
```

Hope this helps.

**Comment by Rocksride** [comment]
@gomezmark, Thank you very much. Worked for me!

**Comment by richardhulbert** [comment]
If you are using the editor in various places. I found that the easiest way is to force it to re-render as @SimonFc suggests. You will need to bind the :key to a value and change that value to force Vue to re-render the component.

**Comment by young-altair** [comment]
Thanks a lot @SimonFc  for this guide, you save couple of weeks of my life, Sir!

**Comment by bekifani** [comment]
I have encountered the same problem and tried to solve it without making changes to tinymce inline-block mode. i just emited an event from my livewire component and set the content of the editor.
 Livewire.on('start_editing', ()=>{ tinymce.get('edit_description').setContent(@this.description); }); 
don't forget to add wire:ignore attribute to the editor.

**Comment by kamal8ali** [comment]
A small tip, if the add the `:key="refreshKey"`  method and it didn't work for you, you may want to put to a timer
```
setTimeout(() => {
        refreshKey.value += 1
      }, 200)
```
this works fine, no need to register the component globally
