### ISSUE TITLE
how to use the 'images_upload_base_path'?

### ISSUE THREAD

**Issue by murilohorstmann** [tinymce/tinymce-vue#114]
how to use the 'images_upload_base_path'?

I tried 

`init: {
				convert_urls: false,
				images_upload_base_path: '/../../',
				relative_urls: false,
			},`

and not work

**Comment by SimonFc** [comment]
Have you configured the [images_upload_url](https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_url) option and set up the a server-side upload handler?

**Comment by SimonFc** [comment]
Closing this, I assume that you figured it out
