### ISSUE TITLE
Official workaround for focusin dialog with bootstrap-vue modal not work

### ISSUE THREAD

**Issue by asika32764** [tinymce/tinymce-vue#116]
See https://codesandbox.io/s/tinymce-vue-bootstrap-vue-modal-focusin-zxfjn

Use [official workaround](https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog) for bootstrap-vue modal not works. The Tinymce dialog are not editable.

```js
// Prevent Bootstrap dialog from blocking focusin
$(document).on('focusin', function(e) {
  if ($(e.target).closest(".tox-tinymce-aux, .moxman-window, .tam-assetmanager-root").length) {
    e.stopImmediatePropagation();
  }
});
```

Seems works with native Bootstrap 4 https://codesandbox.io/s/bootstrap-tinymce-mxi9f

**Comment by SimonFc** [comment]
I saw in the issue and PR discussion over at BootstrapVue that they're providing a work-around for this. (Fun to see that they're adding a TinyMCE specific example to their docs!) Since they have provided a work-around I'll close this issue
