### ISSUE TITLE
visualblocks plugin does not seem to work with tinymce-vue

### ISSUE THREAD

**Issue by ChuckFields** [tinymce/tinymce-vue#117]
**What is the current behavior?**
When you enable visual blocks, nothing happens
Demo: [codesandbox.io](https://codesandbox.io/s/tinymcevue-70lf9)

**What is the expected behavior?**
I can see the 'mce-visualblocks' class gets added, but the visual blocks are not visible. 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
@tinymce/tinymce-vue: 3.0.1
tinymce: 5.1.5

**Comment by SimonFc** [comment]
The thing that's missing is something we call "content UI CSS", it's the CSS that provides things like resize-handle bars (and of course, the styling for visual blocks). This is not to be confused with [content_css](https://www.tiny.cloud/docs/configure/content-appearance/#content_css) which provides CSS for the content itself.

How you provide this "content UI CSS" really depends on your setup but I've updated your [CodeSandbox](https://codesandbox.io/s/tinymcevue-wdfho?fontsize=14&hidenavigation=1&theme=dark) so as to serve this through the public dir. (Note - I've copied the skin css there as well). TinyMCE will expect all skin related CSS to be located at `skins/ui/<skin_name>/` but you can change this by using the [skin_url](https://www.tiny.cloud/docs/configure/editor-appearance/#skin_url) setting.

A tips - there're many different url settings described [here](https://www.tiny.cloud/docs/configure/editor-appearance/). Depending on your setup some of the might be useful.

Hope this is helpful!

**Comment by ChuckFields** [comment]
@SimonFc  I got it working, thank you for the detailed response. Do you know if there a way to tell tinymce to just get it's content UI CSS from node_modules/tinymce/skins/ui/oxide?

**Comment by SimonFc** [comment]
Great to hear!

The recommended approach when self-hosting is to copy the skins, it's described a bit [here](https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/#gettingtheskin) (And of course, if you're using a task runner you can automate this step to copy to whatever build output you have)

Given that the server you have serve the node_modules dir as well there's nothing that prevents you from loading from `node_modules/tinymce/skins/..` by using the skin_url setting but it's very uncommon to do this. Mostly you would want to end up with a self-contained build that you can deploy. In any case, this much depends on your setup so I can't provide any specifics on how to do it!
