### ISSUE TITLE
Customize plugin?

### ISSUE THREAD

**Issue by xlcrr** [tinymce/tinymce-vue#119]
Hi,

I would like to add a custom button / svg to the image plugin

I am able to achieve the following button (arrow-up, in box) with the following code

<img width="481" alt="Screenshot 2020-01-20 at 13 15 35" src="https://user-images.githubusercontent.com/25985241/72729391-f462e600-3b86-11ea-9b70-cdeaafe823cf.png">

```
<tinymce-editor :init="initObj" />

initObj: {
  plugins: ['image'],

  file_picker_callback: function(callback, value, meta) {
    // no code necessary to render the button
  }
}

```

How can I change the icon of this button, add text or hover customization to the button, or change its position?

Thanks!

**Comment by SimonFc** [comment]
It's possible to change the icons TinyMCE use by [creating](https://www.tiny.cloud/docs/advanced/creating-an-icon-pack/#creatingatinymceiconpack) and providing an icon pack. If you only want to replace a single icon it could perhaps be simpler to just do something like [this](http://fiddle.tinymce.com/MZgaab)

If you want to change the look and do a very small extend the layout, you could [create](https://www.tiny.cloud/docs/advanced/creating-a-skin/#makingoreditingaskin) your own skin. It's a somewhat complicated approach though and will possibly force you to change the look of more dialogs than just this one. Perhaps not what you're looking for.

It's unfortunately not possible to change the overall structure and content of the predefined UI components that TinyMCE and its plugins provides, such as the dialog in the image plugin. We do expose an API for creating things like [dialogs](https://www.tiny.cloud/docs/ui-components/dialog/) from the ground up though.

I hope this somewhat answers your question!
