### ISSUE TITLE
How to use file picker callback

### ISSUE THREAD

**Issue by salamat1307** [tinymce/tinymce-vue#126]
How to use file picker?

**Comment by SimonFc** [comment]
Are you looking for the [file_picker_callback](https://www.tiny.cloud/docs/configure/file-image-upload/#file_picker_callback) documentation?

**Comment by salamat1307** [comment]
> Are you looking for the [file_picker_callback](https://www.tiny.cloud/docs/configure/file-image-upload/#file_picker_callback) docs?

Yes I read file pickes docs.  I installed alexusmai/vue-laravel-file-manager package for my vue project. Now I need initialize file picker callback. In docs

**Comment by SimonFc** [comment]
It sounds like you're having difficulties with integrating this third-party feature? As such this doesn't seem to be an issue with tinymce-vue nor tinymce. If you think it is, could you explain the problem you encounter?
