### ISSUE TITLE
How to clear cache?

### ISSUE THREAD

**Issue by xlcrr** [tinymce/tinymce-vue#128]
Hi,

We are using tiny in multiple 'steps' but when we make small changes and navigate between them, we believe tiny might be caching content and not reflecting the small changes.

Is there a way to bust the cache with tiny?

Thanks for your help !

**Comment by lnewson** [comment]
@xlcrr it's not exactly clear what you mean here. Are you talking about making changes to the content within the editor, loading TinyMCE itself or something else?

If you mean TinyMCE itself, then TinyMCE being a client-side application isn't responsible for cache handling, as that's done primarily by the server that hosts/serves TinyMCE. TinyMCE does however offer a [`cache_suffix`](https://www.tiny.cloud/docs/configure/integration-and-setup/#cache_suffix) setting that can be used as a cache busting strategy.

If you mean something else, then can you please include more information and preferably a way to reproduce the issue?

**Comment by jscasca** [comment]
Hey @xlcrr 

Just wanted to reach out and see if you sorted this out or if you can clarify how you are using TinyMCE.

Cheers,

**Comment by xlcrr** [comment]
Hey guys,

Thanks for the reminder.

Turns out we were loading the data incorrectly. We are using tiny to build emails, and we were loading the content directly from the .html instead of going through a route and a controller and extracting it from there. Using a controller solved our issue. Hope this can help someone else! Thanks for the insightful support and reminder.
