### ISSUE TITLE
I can't find what I'm looking for: integrations/vue.md

### ISSUE THREAD

**Issue by mini98k** [tinymce/tinymce-vue#133]
请问在vue项目上使用tinymce,怎么设置行高属性

**Comment by tylerkelly13** [comment]
Sorry, we can only accept issues in English. Please reopen or open a new issue if you can translate your issue/question into English.

**Comment by mini98k** [comment]
How do I set the row height property using tinymce on a vue project

**Comment by jscasca** [comment]
Hi @mini98k 

What do you mean by row height? You can set the height of the editor by setting the `height` property in your configuration object. If you are using the editor as a Vue component you can use this template from the docs (https://www.tiny.cloud/docs/integrations/vue/#tinymcevuejsintegrationquickstartguide).

```
 <template>
   <div id="app">
     <img alt="Vue logo" src="./assets/logo.png">
     <editor
       api-key="no-api-key"
       :init="{
         height: 500,
         menubar: false,
         plugins: [
           'advlist autolink lists link image charmap print preview anchor',
           'searchreplace visualblocks code fullscreen',
           'insertdatetime media table paste code help wordcount'
         ],
         toolbar:
           'undo redo | formatselect | bold italic backcolor | \
           alignleft aligncenter alignright alignjustify | \
           bullist numlist outdent indent | removeformat | help'
       }"
     />
   </div>
 </template>

 <script>
 import Editor from '@tinymce/tinymce-vue'

 export default {
   name: 'app',
   components: {
     'editor': Editor
   }
 }
 </script>
```

If you want to set the row height of a table row you will need to use the `content_css` property and add you own css. You can find more here: https://www.tiny.cloud/docs/configure/content-appearance/#content_css

Let me know if that helps.

**Comment by mini98k** [comment]
Can't we set the lineheight property with the latest tinymce yet in the vue project

**Comment by jscasca** [comment]
To set the lineheight you have to set your custom css using the `content_css` property. You can also use the line-heihgt-formatter plugin (https://github.com/castler/tinymce-line-height-plugin).

Currently there is no Vue specific property to set the lineheight
