### ISSUE TITLE
Is it compatible with VueJS 1.x ?

### ISSUE THREAD

**Issue by wayson** [tinymce/tinymce-vue#134]
I would like to use it with VueJS 1.x. But it seems it doesn't work properly in VueJS 1.x. It keeps throws ID not found error in console.

Where can I find the compatibility list of this vue component?

**Comment by jscasca** [comment]
Hi @wayson , is there any particular reason why you want to run VueJs 1.x?

**Comment by jscasca** [comment]
I'm running the editor on Vue1 and not getting errors in the console. Can you share a bit more of your implementation?

**Comment by wayson** [comment]
Thank you @jscasca . It's a legacy platform and the company doesn't want to upgrade it to VueJS 2.x.

We used webpack 1.x to develop and build the project.

I tried to import tinymce in following steps:

main.js
``` javascript
import Vue from 'vue'
import App from './components/templates/App.vue'
import VueRouter from 'vue-router'
...
import Editor from '@tinymce/tinymce-vue'
// Set globals
window.Vue = Vue
window.io = Io

// Register global components
Vue.component('v-editor', Editor)
```

TinyMceEditor.vue
``` javascript
<template>
   <div id="app">
     <img alt="Vue logo" src="./assets/logo.png">
     <v-editor
       api-key="no-api-key"
       :init="{
         height: 500,
         menubar: false,
         plugins: [
           'advlist autolink lists link image charmap print preview anchor',
           'searchreplace visualblocks code fullscreen',
           'insertdatetime media table paste code help wordcount'
         ],
         toolbar:
           'undo redo | formatselect | bold italic backcolor | \
           alignleft aligncenter alignright alignjustify | \
           bullist numlist outdent indent | removeformat | help'
       }"
     />
   </div>
 </template>

 <script>

 export default {
...
 }
 </script>
```

When I tried to render the page, the editor is not shown. It seems VueJS 1.x has ignore the component. 

Do you know how to use it in VueJS 1.x?

**Comment by jscasca** [comment]
Are you seeing any errors in the console? I haven't seen any issues running it using `vue1`.

Have you tried importing it locally in `TinyMceEditor.vue` instead of in `main.js` ?
E.G.:
```
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <v-editor
      api-key="no-key"
      :init="{
        height: 500,
        menubar: false,
        plugins: ['advlist autolink'],
        toolbar: 'undo redo | formateselect | bold italic backcolor'
      }"
    />
  </div>
</template>

<script>
import Editor from '@tinymce/tinymce-vue'

export default {
  name: 'App',
  components: {
    'v-editor': Editor
  }
}
</script>
```
I can't think of any reason why it wouldn't work on VueJS 1.x

**Comment by jscasca** [comment]
I'm closing this ticket for lack of activity but I'm happy to reopen if we can narrow down the issue to something in the wrapper.
