### ISSUE TITLE
How to make a simple plugin with Vue components?

### ISSUE THREAD

**Issue by AmirrezaNasiri** [tinymce/tinymce-vue#137]
Sorry for asking here, but I think this can be a question for others too.

How should we make a simple plugin using a Vue Single File Component instead of traditional TinyMCE dialogs with a button in the menu? I would appreciate it even if it's the simplest possible plugin (a simple text insertion maybe?).

**Comment by jscasca** [comment]
Hi @AmirrezaNasiri, I don't think I follow exactly on what you want to do.

The idea of traditional 'dialog and button' in the editor is to leverage all the APIs provided by TinyMCE.

Would you like to display Vue components that interact with the editor?

**Comment by jscasca** [comment]
I'm happy to discuss this if you want to elaborate on the issue but I'll close it in the meantime
