### ISSUE TITLE
Unable to modify quickbars_selection_toolbar buttons

### ISSUE THREAD

**Issue by newelement** [tinymce/tinymce-vue#138]
When I specify buttons for quickbars_selection_toolbar it ignores my setting and shows the default set.

```
...
menubar: false,
toolbar: false,
plugins: [ 'quickbars', 'anchor', 'link', 'table', 'lists', 'hr', 'image', 'imagetools', 'paste' ],
quickbars_insert_toolbar: 'formatselect fontsizeselect | forecolor backcolor | bullist numlist | blockquote | image table tabledelete hr',
quickbars_selection_toolbar: 'fontsizeselect forecolor backcolor bold italic alignleft aligncenter alignright blockquote link anchor',
fontsize_formats: "8px 10px 12px 14pt 16px 18px 20px 22px 24px 26px 28px 30px 36px",
inline: false,
...
```

Expected behavior would be in the example fiddle.
http://fiddle.tinymce.com/Xfhaab

**Comment by jscasca** [comment]
Hi @newelement 

That seems a bit weird. I have no issues on Vue using the quickbars plugin. What version of tinymce-vue are you using?

**Comment by newelement** [comment]
I'm using the latest version

**Comment by jscasca** [comment]
I made a sandbox for this but it seems to be working fine: https://codesandbox.io/s/tinymcevue-dmr6n Is this not working for you?

**Comment by newelement** [comment]
Ugh.. after returning to this after a few weeks it's now working. Must have been cached on my end bad...
