### ISSUE TITLE
tinymce-vue  Invalid

### ISSUE THREAD

**Issue by rookieDJ** [tinymce/tinymce-vue#139]
When used   ‘keep-alive’  tinymce  Invalid

**Comment by jscasca** [comment]
Hi @rookieDJ 

Can you elaborate more on this issue? Is the Editor inside the `keep-alive` tags and not working? Are you seeing any errors in the console? What are you trying to achieve?

**Comment by yanshuok** [comment]
I think the problem is when the route changes and then switch the route back, the container of the editor becomes empty. The console doesn't log any errors. I fixed this problem by adding v-if to destroy the editor in deactivated and re-init the editor in activated hook.
