### ISSUE TITLE
Html tags showing

### ISSUE THREAD

**Issue by Sidney-Dev** [tinymce/tinymce-vue#14]
I just added tinymace in my Vue template. I can see the editor when I load the page, however,  after I save the records from the text area, I visit the which shows those records and I notice that the html code is ignored. Meaning that I will see the paragraph tags,strongs and etc.

I imported exactly as per the docummentation and in the vue component the field looks like this:

`<editor :init="TinyMceInit" v-model="post.description"></editor>
`
Anything I did not do properly?
Hope someone can help

**Comment by fyrkant** [comment]
I'm not sure I understand the problem, how is the html ignored? Can you create a demo app showing the problem?

**Comment by fyrkant** [comment]
Closed due to inactivity.
