### ISSUE TITLE
Custom skin gets overwritten

### ISSUE THREAD

**Issue by voicecode-bv** [tinymce/tinymce-vue#146]
Hi all, 

I'm using this tool for one of my projects and created a custom skin using the official skin creator. When adding the values below to the init option, I see the files are being loaded.

```
skin_url: "/tinymce/skins/ui/mytheme",
content_css: "/tinymce/skins/ui/mytheme/content.min.css",
```

Right after these files are loaded, TinyMCE will load the default skin and content css files from the tiny.cloud CDN which will overwrite my custom theme. 

When I block the requests in the browsers network tab, my custom theme will work just fine. 
How can I disable the requests for the default skin and content css files? This is driving me nuts :) 

![Schermafbeelding 2020-05-11 om 15 23 05](https://user-images.githubusercontent.com/4598259/81566575-598f5100-939b-11ea-8600-021b6a7a8ef0.png)

**Comment by jscasca** [comment]
Hi @voicecode-bv 

Do you have multiple editors in the same page? The vue-wrapper will pass a final init configuration object to the TinyMce editor and I am not aware of a similar issue on the editor. I tried replicating your issue but my skin seems to be working normally in this [codesandbox](https://codesandbox.io/s/tinymcevue-iinmp?file=/src/App.vue)

Can you elaborate with a replication case or share your code to see if we can spot anything that will be triggering this behaviour?

**Comment by voicecode-bv** [comment]
@jscasca omg... it was because there are multiple editors on the same page hidden in a tabbed navigation. Thank you so much!
