### ISSUE TITLE
Saving function

### ISSUE THREAD

**Issue by chad-l** [tinymce/tinymce-vue#149]
I can't seem to trigger the save function with the 'save_onsavecallback'. I see in the documentation about the "mceSave" command, but not much is said about it. Also I expect to be able to trigger a function when saving without the use of the form element.

https://codesandbox.io/s/tinymcevue-8x1q8?file=/src/App.vue

I expect to be able to trigger a function on save without the use of the form element.

"tinymce": "^5.2.2", "@tinymce/tinymce-vue": "^3.2.1",  using chrome

**Comment by jscasca** [comment]
Hi @chad-l 

The `save_onsavecallback` is an editor property. If you want to use this setting you need to specify it on the `init` object of the vue component.
E.G:
```
:init="{
          height: 700,
          save_onsavecallback: function() {
            saveText();
          }
        }"
```

**Comment by chad-l** [comment]
Thanks @jscasca , that helped. I didn't expect that I needed to wrap the function in a function. I have a similar question about the autosave. How can I trigger a function with autosave? Can I do something like "autosave_onautosavecallback: function() { saveText(); }" ?

**Comment by jscasca** [comment]
@chad-l if you want to deal with the `autosave` plugin you can listen to its events `RestoreDraft`, `StoreDraft` and `RemoveDraft`. I don't believe it has a callback property besides the documented options: https://www.tiny.cloud/docs/plugins/autosave/
