### ISSUE TITLE
打包发布后，toolbar上面的按钮全部显示不出来

### ISSUE THREAD

**Issue by qiaobincs** [tinymce/tinymce-vue#150]
![image](https://user-images.githubusercontent.com/42260105/82964988-795c8100-9ff9-11ea-9a25-8f58ff4bda7b.png)

**Comment by qiaobincs** [comment]
![icon_not_found](https://user-images.githubusercontent.com/42260105/82965054-a9a41f80-9ff9-11ea-802f-047fe385ae1c.png)

**Comment by jscasca** [comment]
@qiaobincs 

Can you share a little bit more of your implementation to narrow down the issue? Is this a self hosted solution? How are you building?

**Comment by zhoufenfens** [comment]
是不是安装了 tinymce@5.3.0 版本，如果是装的这个版本，是因为icon从core里面抽出来了，请动态引入icon 
> import 'tinymce/icons/default';

-----
have you installed tinymce@5.3.0 ?

**Comment by dybxin** [comment]
> 是不是安装了 tinymce@5.3.0 版本，如果是装的这个版本，是因为icon从core里面抽出来了，请动态引入icon
> 
> > import 'tinymce/icons/default';
> 
> have you installed tinymce@5.3.0 ?

thanks!

**Comment by qiaobincs** [comment]
问题已解决，非常感谢！



qiaobincs@163.com
 
发件人： dybxin
发送时间： 2020-07-09 17:11
收件人： tinymce/tinymce-vue
抄送： qiaobincs; Mention
主题： Re: [tinymce/tinymce-vue] 打包发布后，toolbar上面的按钮全部显示不出来 (#150)
是不是安装了 tinymce@5.3.0 版本，如果是装的这个版本，是因为icon从core里面抽出来了，请动态引入icon
import 'tinymce/icons/default';
have you installed tinymce@5.3.0 ?
thanks!
