### ISSUE TITLE
Initialization is slow in China

### ISSUE THREAD

**Issue by greatflag** [tinymce/tinymce-vue#151]
Hi, For some reasons, the network is poor to TINY CLOUD, and It will has a hint if the api-key is null.

**Comment by tinydylan** [comment]
Hi,

Can you please provide some more detail about the issue? What code are you using to load TinyMCE?

If you're using Tiny Cloud, you'll need to sign up for an API key and configure TinyMCE to use it. See step 6 of the [quick start guide](https://www.tiny.cloud/docs/integrations/vue/#tinymcevuejsintegrationquickstartguide)

Please also see our article on improving performance in Tiny Cloud:

https://www.tiny.cloud/blog/3-tips-to-improve-tinymce-performance-in-the-cloud/

Thanks!

**Comment by greatflag** [comment]
Thanks for your reply. I wrote it according to official TinyMCE Vue.js integration quick start guide. My code is the same as the example code. 

Chrome's console says "A cookie associated with a cross-site resource at http://tiny.cloud/ was set without the `SameSite` attribute" after refresh my page everytime. and it says "GET https://sp.tinymce.com/i?....net::ERR_INTERNET_DISCONNECTED.  GET https://cdn.tiny.cloud/1/.../tinymce/5.2.2-80/themes/silver/theme.min.js net::ERR_INTERNET_DISCONNECTED"If turn wireless off into Offline Status

@tinydylan My question is ”How to use TinyMCE in a Vue project and it supports offline mode(without a connection to the Internet)“ . Thanks

**Comment by jscasca** [comment]
Hi @greatflag 

The Vue integration allow users to self-host their own version of TinyMCE. You can load the TinyMCE script in your header as explained here: [Vue integration procedure](https://www.tiny.cloud/docs/integrations/vue/#procedure) under *TinyMCE self hosted* or you can specify from which location to lazy load the editor script as exemplified here: [tinymce-script-src example](https://www.tiny.cloud/docs/integrations/vue/#exampletinymce-script-src)

Let me know if this helps.

**Comment by greatflag** [comment]
@jscasca , Many thanks to your answer, it works so well.
Set tinymce-script-src refer to file [http://download.tiny.cloud/tinymce/community/tinymce_5.3.1.zip](url)
