### ISSUE TITLE
vue dev Toolbar icon show,prod Toolbar icon no show?

### ISSUE THREAD

**Issue by hzhh110** [tinymce/tinymce-vue#153]
vue dev Toolbar icon show,prod Toolbar icon no show?How do I set it up?

**Comment by jscasca** [comment]
Is this for a self-hosted solution? What version of TinyMCE are you using?

**Comment by mymbrooks** [comment]
@jscasca the toolbar icon not show both dev and prod state.

My self-hosted version:
package.json
"tinymce": "^5.3.2",
"tinymce-i18n": "^20.4.4",
"@tinymce/tinymce-vue": "^3.2.2"

main.js
import Tinymce from 'tinymce/tinymce'
import 'tinymce/themes/silver'
import 'tinymce/skins/ui/oxide/skin.min.css'
import 'tinymce-i18n/langs5/zh_CN.js'
import Editor from '@tinymce/tinymce-vue'
...
new Vue({
  el: '#app',
  router,
  store,
  i18n,
  components: {
    Window,
    'editor': Editor,
    Tinymce
  },
  render: h => h(App)
})

vue
data() {
    return {
      // 富文本
      editorInit: {
        language: 'zh_CN',
        menubar: false,
        statusbar: false,
        toolbar: 'bold italic subscript superscript'
      },
...

<el-form-item :label="$t('instrument.specification')" prop="specification">
      <editor id="specification" v-model="instrument.specification" :init="editorInit" />
</el-form-item>

![1](https://user-images.githubusercontent.com/1232612/86332138-acd79e80-bc7c-11ea-9452-1d4f7bde7a6a.png)

**Comment by serenehaly** [comment]
> Is this for a self-hosted solution? What version of TinyMCE are you using?

I have the same problem.The toolbar icon cannot be displayed.

[version]
tinymce：5.3.2
@tinymce/tinymce-vue：3.2.2

[use]
<editor id="target_method" v-model="formData.target_method" :init="editorInit" />

//  富文本编辑器
import tinymce from 'tinymce/tinymce'
import 'tinymce/themes/silver/theme'
import Editor from '@tinymce/tinymce-vue'

editorInit: {
        language_url: '/tinymce/langs/zh_CN.js',
        language: 'zh_CN',
        skin_url: '/tinymce/skins/ui/oxide',
        height: 500,
        statusbar: false, // 隐藏编辑器底部的状态栏
        paste_data_images: true, // 允许粘贴图像(需要引入插件paste)
        menubar: false, // 隐藏最上方menu
        nonbreaking_force_tab: true,
        plugins: 'link lists code table colorpicker textcolor wordcount contextmenu advlist paste preview fullscreen',
        toolbar: 'bold italic underline strikethrough | fontsizeselect | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist table | undo redo removeformat preview fullscreen | link unlink code'
      }

![image](https://user-images.githubusercontent.com/14230501/86549373-0a683580-bf72-11ea-9283-47d9581cffc9.png)
![image](https://user-images.githubusercontent.com/14230501/86549407-22d85000-bf72-11ea-923a-3883a8254db1.png)
![image](https://user-images.githubusercontent.com/14230501/86549465-469b9600-bf72-11ea-853d-e66c9f6a764e.png)

**Comment by serenehaly** [comment]
> @jscasca the toolbar icon not show both dev and prod state.
> 
> My self-hosted version:
> package.json
> "tinymce": "^5.3.2",
> "tinymce-i18n": "^20.4.4",
> "@tinymce/tinymce-vue": "^3.2.2"
> 
> main.js
> import Tinymce from 'tinymce/tinymce'
> import 'tinymce/themes/silver'
> import 'tinymce/skins/ui/oxide/skin.min.css'
> import 'tinymce-i18n/langs5/zh_CN.js'
> import Editor from '@tinymce/tinymce-vue'
> ...
> new Vue({
> el: '#app',
> router,
> store,
> i18n,
> components: {
> Window,
> 'editor': Editor,
> Tinymce
> },
> render: h => h(App)
> })
> 
> vue
> data() {
> return {
> // 富文本
> editorInit: {
> language: 'zh_CN',
> menubar: false,
> statusbar: false,
> toolbar: 'bold italic subscript superscript'
> },
> ...
> 
> ![1](https://user-images.githubusercontent.com/1232612/86332138-acd79e80-bc7c-11ea-9452-1d4f7bde7a6a.png)

我也遇到同样的问题，你解决了吗？

**Comment by serenehaly** [comment]
// Default icons are required for TinyMCE 5.3 or above
import 'tinymce/icons/default';

**Comment by mymbrooks** [comment]
@serenehaly Thanks it works
