### ISSUE TITLE
Tab in IE

### ISSUE THREAD

**Issue by mbsa92** [tinymce/tinymce-vue#154]
When trying to tab thru RTE in IE, focus stays on the toolbar. It is not possible to tab thru toolbar down to the textarea. 

Steps to reproduce: 
1.	Click tab into RTE
2.	Try to get tab thru toolbaren, and down to the textarea. 

Result: 
Focus stays on the toolbar

Expected: 
Focus contiue to the textarea

Version: 3.2.1

This bug can also be reproduced on https://www.tiny.cloud/

**Comment by jscasca** [comment]
Hi,

Just checking if this is still an issue. Seems like it should be fixed by now by the latest version of tinyMCE.

**Comment by mesterjagels** [comment]
This bug is still an issue. If you have focused on the toolbar you can't change focus to the textarea, and if you have focus in the text area you can't change focus to the toolbar
