### ISSUE TITLE
Partial loss of Chinese language pack

### ISSUE THREAD

**Issue by tengfeiS** [tinymce/tinymce-vue#155]
Why some Chinese characters in the editor are lost after they are packaged online?

**Comment by tengfeiS** [comment]
For example, click "description text" in the pop-up window of insert picture

**Comment by jscasca** [comment]
Hi @tengfeiS 

This is the repository for issues related to the Vue wrapper only. Unfortunately the wrapper doesn't have to do anything with the editor languages. If they are incomplete you can submit a request for the TinyMCE repository or head over https://www.tiny.cloud/get-tiny/language-packages/ to contribute with translations.
