### ISSUE TITLE
Dragging text into tinyMCE does not update it's bound value

### ISSUE THREAD

**Issue by ChuckFields** [tinymce/tinymce-vue#156]
To Reproduce:

Go here: [https://codesandbox.io/s/tinymcevue-30by5?file=/src/App.vue](https://codesandbox.io/s/tinymcevue-30by5?file=/src/App.vue)

Drag the 'Drag me' element to the tinyMCE editor. 
You'll notice the value at the top does not reflect the value in the editor. If you then modify the editor, the changes are then reflected.

I would expect the drag event to update the bound value.

tinymce-vue: 3.2.2

**Comment by jscasca** [comment]
Hi @ChuckFields 

Currently the wrapper is only triggering by default on the following events: `change keyup undo redo`. We are replacing the `keyup` event by the `input` event soon to handle this use case. It's been a long time coming.

However, in the meantime you can add your own events by using the `modelEvents` property of the wrapper. E.G. https://codesandbox.io/s/tinymcevue-i41tr?file=/src/App.vue

Let me know if that helps

**Comment by ChuckFields** [comment]
@jscasca Thanks, that works!

**Comment by jscasca** [comment]
In version 3.2.3 `modelEvents` include `input` by default.
