### ISSUE TITLE
Missing content of Chinese package 

### ISSUE THREAD

**Issue by muxu85** [tinymce/tinymce-vue#161]
Missing content of Chinese package . 
For example, the "Alternative Description" in the picture setting has no corresponding Chinese.
I hope to complete these Chinese contents, thank you very much.

**Comment by jscasca** [comment]
Hi @muxu85 

This is the repository for issues related to the Vue wrapper only. Unfortunately the wrapper doesn't have to do anything with the editor languages. If they are incomplete you can submit a request for the TinyMCE repository or head over https://www.tiny.cloud/get-tiny/language-packages/ to contribute with translations.

**Comment by Rockergmail** [comment]
@jscasca I knew tinymce.addI18n method can change language. But how to expose tinymce object in tinymce-vue?

**Comment by jscasca** [comment]
@Rockergmail The Vue wrapper doesn't expose the tinymce object, it will try to find a global tinymce or load one from either the `tinymce-script-src` property or the cloud. If you want to access the tinymce object you will have to load the tinymce script beforehand to have access to the global object

**Comment by jscasca** [comment]
@Rockergmail 

Hope this helps:
> https://github.com/tinymce/tinymce-vue/issues/136#issuecomment-614306529
