### ISSUE TITLE
Can't install tinymce-vue (URGENT - Affecting Production Builds)

### ISSUE THREAD

**Issue by joao-p-pinto-findmore** [tinymce/tinymce-vue#162]
**What is the current behavior?**

I've been using this package in a Vue.js web app without any issues. Since some time today (GMT) I can no longer install this package. I was running some builds and they started failing and it is because the package seems to not be available to be installed.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**

1. Create a new folder.
2. Initialize a new node repository (npm init).
3. Try and install @tinymce/tinymce-vue (e.g., npm i @tinymce/tinymce-vue, npm i @tinymce/tinymce-vue@latest,  npm i @tinymce/tinymce-vue@1.0.8,  npm i @tinymce/tinymce-vue@3.2.2).

Installing won't work and will throw this error:

![image](https://user-images.githubusercontent.com/65542285/89521725-eea5b880-d7d7-11ea-856e-4c8eca77aa86.png)

**What is the expected behavior?**

The package should be installed successfully.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**

It is affecting everything.

**Comment by Rikko91** [comment]
I have the same issue :(

**Comment by danielamaia** [comment]
i also have the same issue

![image](https://user-images.githubusercontent.com/32894795/89523246-77255880-d7da-11ea-9ff6-61c0a0ae031b.png)

**Comment by BernardObinna** [comment]
Me too

**Comment by joao-p-pinto-findmore** [comment]
As a workaround I copied the version that I had on my node_modules (the @tinymce folder) into a folder on my project and installed it with npm i {{ path_of_folder }} (in my case npm i static/@tinymce/tinymce-vue):

![image](https://user-images.githubusercontent.com/65542285/89527225-e7cf7380-d7e0-11ea-8a30-c43f09e74910.png)

On my package.json it adds this line:

![image](https://user-images.githubusercontent.com/65542285/89527274-f9188000-d7e0-11ea-85ca-38bbdd8207c7.png)

This isn't a long time solution, but for now it works 👍

**Comment by jscasca** [comment]
Hi,

This seems to be an issue with the npm registry and unfortunately is out of our control. It seems like it should be working now but it might take some time to re-populate the cache. Sorry for the inconvenience and thank you for your patience.

You can follow up the npm status update to have the latest reports on the issue: https://status.npmjs.org/

Cheers,

**Comment by joao-p-pinto-findmore** [comment]
From looking at https://status.npmjs.org/ the team behind the NPM registry says that they've fixed the issue and from my side I've tested this again and everything seems to be working fine, so I'll be closing this.
