### ISSUE TITLE
content_css second entry is canceled

### ISSUE THREAD

**Issue by wuchenge** [tinymce/tinymce-vue#163]
### first entry is normal.
> but,second entry is abnormal. debug is content.css is canceled.
![image](https://user-images.githubusercontent.com/11495523/89879601-c7932080-dbf5-11ea-88ed-e5f4a6c3cd3c.png)

* use: chrome vue@2.5.9

## supplement
>  it is in model use iview . it meaning visitable or hidden use tinymce second find issue. but in route no find.

**Comment by langop** [comment]
same problem in ant vue modal，555

**Comment by jscasca** [comment]
@wuchenge do you have multiple editors in the same page?

**Comment by langop** [comment]
> @wuchenge do you have multiple editors in the same page?

no, only one. i use new page route instead of modal>_<

**Comment by jscasca** [comment]
@langop The Vue integration prepares a final configuration object that it passes to TinyMCE and is TinyMCE doing all the file loading. For each editor or editor load there will be `content.css` load. Is not easy to say why it fails to load without seeing your particular environment. Could you provide a small replication case in a code sandbox?

**Comment by langop** [comment]
@jscasca I write the function roughly according to this idea:   https://codesandbox.io/s/p1-mguhh  check it

**Comment by jscasca** [comment]
We are still investigating this issue. We need to do some further research into the a-model component of the ant-design-vue library to better understand this.

**Comment by Gardent** [comment]
@langop 
`
<template>
  <div v-if="editorInit">
    <tinymce-editor v-model="content" :init="option" />
  </div>
</template>

<script>
// eslint-disable-next-line no-unused-vars
import tinymce from 'tinymce/tinymce'
import 'tinymce/themes/silver'
import 'tinymce/icons/default'
import 'tinymce/skins/ui/oxide/skin.css'
import './langs/zh_CN.js'
import 'tinymce/plugins/fullscreen'
import 'tinymce/plugins/code'
import tinymceEditor from '@tinymce/tinymce-vue'

export default {
  name: 'Tinymce',
  components: {
    tinymceEditor
  },
  props: {
    value: {
      type: String,
      default: ''
    },
    placeholder: {
      type: String,
      default: ''
    },
    height: {
      type: Number,
      default: 240
    }
  },
  data() {
    return {
      editorInit: false,
      option: {
        skin: false,
        content_css: false,
        language: 'zh_CN',
      },
      content: ''
    }
  },
  watch: {
    content(val) {
      this.$emit('input', val)
    },
    value(val) {
      this.content = val
    }
  },
  mounted() {
    this.editorInit = true
  }
}
</script>
`
This can be handled, but I don’t know if it’s a good idea

**Comment by Gardent** [comment]
`<template>
  <div v-if="editorInit">
    <tinymce-editor v-model="content" :init="option" />
  </div>
</template>

<script>
// eslint-disable-next-line no-unused-vars
import tinymce from 'tinymce/tinymce'
import 'tinymce/themes/silver'
import 'tinymce/icons/default'
import 'tinymce/skins/ui/oxide/skin.css'
import './langs/zh_CN.js'
import 'tinymce/plugins/fullscreen'
import 'tinymce/plugins/code'
import tinymceEditor from '@tinymce/tinymce-vue'

export default {
  name: 'Tinymce',
  components: {
    tinymceEditor
  },
  props: {
    value: {
      type: String,
      default: ''
    },
    placeholder: {
      type: String,
      default: ''
    },
    height: {
      type: Number,
      default: 240
    }
  },
  data() {
    return {
      editorInit: false,
      option: {
        skin: false,
        content_css: false,
        content_style: `.mce-content-body[data-mce-placeholder]{ position: relative;}
          .mce-content-body[data-mce-placeholder]:not(.mce-visualblocks)::before {  color: rgba(34, 47, 62, 0.7);  content: attr(data-mce-placeholder);  position: absolute;}`,
        language: 'zh_CN',
        resize: 'true',
        menubar: false,
        statusbar: true,
        height: this.height,
        plugins: 'fullscreen code',
        fontsize_formats: '12px 14px 16px 18px 20px 24px 30px',
        toolbar: [
          'bullist numlist | outdent indent | forecolor | bold italic | h2 p  media | alignleft aligncenter alignright' +
            '| fontsizeselect | newdocument undo redo restoredraft removeformat | fullscreen code link image'
        ],
        placeholder: this.placeholder
      },
      content: ''
    }
  },
  watch: {
    content(val) {
      this.$emit('input', val)
    },
    value(val) {
      this.content = val
    }
  },
  mounted() {
    // 延后初始化，避免先于父组件渲染
    this.editorInit = true
  }
}
</script>`

**Comment by Gardent** [comment]
@langop 
try this [demo](https://codesandbox.io/s/p1-forked-7voqp?file=/src/components/HelloWorld.vue)
But I don't know if it's a good idea
