### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by Yakoot** [tinymce/tinymce-vue#165]
are you planning to support vue 3?

now it's not working

**Comment by anish2690** [comment]
@Yakoot for timing you can use my branch kept build files there.

**Comment by Yakoot** [comment]
@anish2690 thx)

**Comment by Yakoot** [comment]
it's for ts =( I'll create my own fork
Or it's time to rewrite my project using typescript =)

**Comment by MalachiDraven** [comment]
Yes please, we very much need support for Vue 3.

**Comment by tinydylan** [comment]
Hi,

Good news - we're working on official Vue 3 support right now. 

Regards,

Dylan
Tiny Technologies

**Comment by snowdream** [comment]
We want tinymce to support  Vue 3 and Typescript.

**Comment by windhc** [comment]
thanks, we very much need support for Vue 3.

**Comment by jscasca** [comment]
So the newest version of the wrapper,  v4.0, is out to support Vue 3

**Comment by Yakoot** [comment]
does it work with vite?

**Comment by jscasca** [comment]
It should. If you pull down the repo there is even a vite demo in there.

**Comment by jscasca** [comment]
Closing this ticket since Vue3 support is out there. Hope it is working well for everybody
