### ISSUE TITLE
vue keep-alive，Enter again and the show content is lost，but have still the value 

### ISSUE THREAD

**Issue by nanliu666** [tinymce/tinymce-vue#166]
![image](https://user-images.githubusercontent.com/30199403/90862965-d2517080-e3c0-11ea-80b8-d0caddf677fc.png)
now my fix ：
to.meta.$keepAlive = false

**Comment by jscasca** [comment]
Hi @nanliu666 

Could you provide us with a sandbox replication to better understand what is going on?

Feel free to fork one of our Vue [codesandboxes](https://codesandbox.io/s/9y95z5m40y?fontsize=14&file=/src/App.vue)

**Comment by wuyuweixin** [comment]
same issue.

**Comment by jscasca** [comment]
Thanks @wuyuweixin, can you help us out with a small replication?

**Comment by wuyuweixin** [comment]
OK,I will provide replication repo later.

**Comment by wuyuweixin** [comment]
@jscasca  [codesandbox](https://codesandbox.io/s/tinymcevue-forked-thqnj?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.vue)

**Comment by pgfeng** [comment]
I had the same problem.

**Comment by jscasca** [comment]
Unfortunately, the wrapper currently only supports the `keep-alive` tag when using the inline version of the editor.

The way the editor works is by creating an iframe and latching onto it when initializing, but re-rendering the iframe can break the editor. As such, having the iframe 'stay-alive' with the `keep-alive` tag in memory will try to render the iframe resulting in a broken editor.

I will escalate this but it might take a while to address this issue

**Comment by wuyuweixin** [comment]
Thanks!

**Comment by jscasca** [comment]
Hey guys, we worked on a workaround for the `keep-alive` tag in the wrapper. It's included in the latest releases (v4.0 for Vue3 and v3.2.6 for Vue 2.x).

Let us know if this is working as expected

**Comment by jscasca** [comment]
I'm closing this one since no one has complained about the fix so I hope it's working

**Comment by wuyuweixin** [comment]
@jscasca  [codesandbox](https://codesandbox.io/s/tinymcevue-forked-ib3uz?file=/src/EditorTest.vue) No work with tinymce 4.5.12

**Comment by jscasca** [comment]
@wuyuweixin 

This was on me, it was working on Tinymce v5 and forgot the v4 support. I'm reopening the case to work it out.

**Comment by jscasca** [comment]
@wuyuweixin this should be fixed for Tiny v4 in v3.2.7, let me know if that works for you

**Comment by wuyuweixin** [comment]
Has V3.2.7 been released ?

**Comment by jscasca** [comment]
The release automation must have been delayed. You can find it here: https://www.npmjs.com/package/@tinymce/tinymce-vue/v/3.2.7
