### ISSUE TITLE
resizer of table plugin can be dragged in other pages

### ISSUE THREAD

**Issue by greatflag** [tinymce/tinymce-vue#168]
![image](https://user-images.githubusercontent.com/6038392/91525983-39c56e00-e935-11ea-80a9-485ea53b3095.png)

**Comment by jscasca** [comment]
Hi @greatflag 

I don't follow, how is the resizer dragged into a different page. Can you elaborate on what is happening here?

**Comment by wuligelovevc** [comment]
![image](https://user-images.githubusercontent.com/5836200/91800201-28dd6b00-ec5b-11ea-8874-2846cfca41b3.png)
Hello jscasca @jscasca !  When I scroll the parent element of the table, the top values in style attributes of "application" and "presentation" do not change.

**Comment by wuligelovevc** [comment]
Since the "top" of styles not change, the location of resize bars seems wrong.

**Comment by greatflag** [comment]
@jscasca , Hi, I use tinymce in a vue single page project, 'page' means different router. resizers of table plugin are rendered out of the 'app' div-node, so they stand still always.
