### ISSUE TITLE
Add some css libraries.

### ISSUE THREAD

**Issue by einnar82** [tinymce/tinymce-vue#17]
How can i add some css libraries to inject in the editor?

**Comment by fyrkant** [comment]
Do you mean to style the content that you create within the editor? Maybe the [content_css](https://www.tiny.cloud/docs/configure/content-appearance/#content_csshttps://www.tiny.cloud/docs/configure/content-appearance/#content_css) setting is what you are looking for?

**Comment by einnar82** [comment]
Thanks man! It's working.
