### ISSUE TITLE
Events must be lowercase in HTML templates

### ISSUE THREAD

**Issue by lonnylot** [tinymce/tinymce-vue#178]
**What is the current behavior?**

When using HTML templates we cannot bind to events such as `@onKeyUp` or `@onBlur` because, as described in https://github.com/vuejs/vue/issues/4688, HTML template are _always automatically_ lowercased

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**

https://codesandbox.io/s/tinymcevue-forked-jy7y7

**What is the expected behavior?**

Events are fired

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**

tinymce-vue 3.2.2
Chrome

**Comment by lonnylot** [comment]
![bueller](https://user-images.githubusercontent.com/656791/94736062-a5866680-0339-11eb-8d95-50ecbaa2a76e.gif)

---

What's going on? How can I help move this along?

**Comment by jscasca** [comment]
Hi @lonnylot 

Unfortunately, your codesandbox is not working for me. If the case-sensitivity is the issue, that should be an easy fix since listeners are validated against a list of possible events triggered. You can help move this along faster by creating a PR with a fix for the issue and adding a story for this use case or a test.

Otherwise, we will investigate this a bit further to address this issue.

**Comment by lonnylot** [comment]
@jscasca Thanks for the response. Something weird is going on w/ that codesandbox...it doesn't seem to want to allow inline templates. Inline templates has been a pretty common pattern in Laravel apps so you can spin up a project there and duplicate the issue pretty quickly. The Laravel community _has_ started moving away from inline HTML templates as VueJS 3 doesn't even support them anymore, but there are still plenty of current projects that use them.

I created the PR, but couldn't figure out how to write the story as it requires inline HTML templates (not JS compiled ones).

Let me know how else I can help.

**Comment by lonnylot** [comment]
Any ETA for a 3.x release with this fix?

**Comment by jscasca** [comment]
We are currently preparing the new release supporting Vue3 and is undergoing QA at the time.

**Comment by jscasca** [comment]
Vue 3 support has been release and it includes this fix. Let us know when you try it out. In the meantime I'm closing this issue

**Comment by lonnylot** [comment]
@jscasca I'm not using Vue3 and Vue3 doesn't support inline-templates so it's not usable on the 4.x release.

https://v3.vuejs.org/guide/migration/inline-template-attribute.html#overview

Can you please merge this into the 3.x release

**Comment by lonnylot** [comment]
I now have to fork your library and patch this so I can use it....I really didn't want to do this, but it's causing too many issues.

**Comment by jscasca** [comment]
Hi @lonnylot , I thought this was released back in v3.2.4 ? Your fix was applied to v4.x and v3.x, is this not the case?

**Comment by lonnylot** [comment]
@jscasca I can't seem to find the 3.2.4 tag on GH and the PR only says it is merged into master. I'm not sure how your release process works...please let me know how I could check and confirm.

**Comment by lonnylot** [comment]
But also - if v4 is only for Vue3 then it shouldn't be in there b/c, as mentioned, Vue3 doesn't support inline templates.

**Comment by jscasca** [comment]
It was merged into master, and the v3.x branch was created from master at the time so it included that fix. It shouldn't break v4 even if it's not supported in Vue3. As for the tags, I'll take a look into it, maybe the release process has been ignoring the tags

**Comment by lonnylot** [comment]
Thanks, I appreciate the info and explanation.
