### ISSUE TITLE
Be able to use scss at the content_css

### ISSUE THREAD

**Issue by lincolnlemos** [tinymce/tinymce-vue#179]
Can someone help me figure out how can I pass a .scss file into the content_css property of my init?

**Comment by jscasca** [comment]
I don't think that will be possible as the `content_css` property only takes a bunch of urls and the editor is the one injecting them later on. This is not vue specific so maybe you can try asking in the tinymce repo?

**Comment by tomvdk** [comment]
I struggle with the same issue, we're using vuecli & webpack so everything gets bundled correctly. We can import the skin like this which is needed for the edtior to appear: 
import "tinymce/skins/ui/oxide/skin.css";

But how can we add css for the content of the editor when using typescript? Are urls the only way? Then, we can never package/bundle the css right?

**Comment by jscasca** [comment]
Hi @tomvdk,

As far as I know, urls are the only way unfortunately. As I said, this has to be addressed by the TinyMCE editor at its core and there is no current way, that I am aware at least, for a wrapper to work around this :(

Maye you can open a feature request for the editor to take in `css` content?

I will have to close this ticket as the Vue wrapper cannot address this issue

**Comment by jscasca** [comment]
@tomvdk @lincolnlemos I have been notified that there is actually a way to pass css instead of urls by using the `content_style` property instead of `content_css`.  You can find the docs here: https://www.tiny.cloud/docs/configure/content-appearance/#content_style

Let me know if this works as you expected or if there is an issue with the wrapper passing this content and I will be happy to reopen this issue

**Comment by tomvdk** [comment]
> @tomvdk @lincolnlemos I have been notified that there is actually a way to pass css instead of urls by using the `content_style` property instead of `content_css`. You can find the docs here: https://www.tiny.cloud/docs/configure/content-appearance/#content_style
> 
> Let me know if this works as you expected or if there is an issue with the wrapper passing this content and I will be happy to reopen this issue

That does work. Thanks. However, you need to pass all your css as a large string and you violate the DRY principle. But gives you the possibility to style your content a bit. 👍

**Comment by lincolnlemos** [comment]
I appreciate the effort! I will follow up on the TinyMCE repo! 

Not sure if this solves my problem too.
I would like to have the .scss because I'm using the same file across two projects. 
The idea was to import the file from the main project. 

Thanks anyway!
