### ISSUE TITLE
About import other lang packages in this vue component.

### ISSUE THREAD

**Issue by gzb219** [tinymce/tinymce-vue#18]
How can I import other language packages in tinymce-vue, such as Chinese language packages.

**Comment by fyrkant** [comment]
You can use the `language_url` property in the `:init` object, see [this page in the documentation for details.](https://www.tiny.cloud/docs/configure/localization/#language_url).

It would look something like this: 
```js
<editor :init="{ language_url : '/languages/fi.js' }"></editor>
```
