### ISSUE TITLE
Tinymce ignoring preload css static files - redownloads them

### ISSUE THREAD

**Issue by robotichead** [tinymce/tinymce-vue#182]
**Method**
1. Constructed a simple page with TinyMce Vue component
2. Make sure the application JS imports the TinyMce Vue JS
3. Load the page

**Expected Results**
The preload css libraries to be utilised instead of redownloading. The preload will shorten the page load times.

**Actual Results**
The preload css libraries are downloaded again, causing;
1. Slower page load times
2. Unnecessary bandwidth usage
3. Worse Lighthouse score

**My code references**

The HEAD component
```  
    <!-- tinymce -->
    <link rel="preload" href="NearBeach/tinymce/skins/ui/oxide/skin.min.css" as="style">
    <link rel="preload" href="NearBeach/tinymce/skins/content/default/content.min.css" as="style">
    <link rel="preload" href="NearBeach/tinymce/skins/ui/oxide/content.min.css" as="style">
    <script defer type="text/javascript" src="NearBeach/tinymce/tinymce.min.js"></script>
```
The BODY component
```
    <!-- MAIN COMPONENT -->
    <main class="container" role="main">
        <div id="app">
            <editor
               :init="{
                 height: 500,
                 menubar: false,
                 toolbar: 'undo redo | formatselect | ' +
                  'bold italic backcolor | alignleft aligncenter ' +
                  'alignright alignjustify | bullist numlist outdent indent | ',
               }"
            />
        </div>
    </main>

    <!-- Load NearBeach Webpack File -->
    <script defer type="text/javascript" src="NearBeach/NearBeach.min.js"></script>
```

The NearBeach.min.js uncompiled code can be found in my project here - https://github.com/robotichead/NearBeach/blob/main/src/js/app.js

The NearBeach mock tinymce template (referenced in the code above) can be found here - https://github.com/robotichead/NearBeach/blob/tinymce_tests/NearBeach/templates/NearBeach/temp/tinymce.html

When I load the page, I expect the preloaded CSS files will be utilised within TinyMce, instead they are not and they are re-downloaded. This can be seen within the network console

![image](https://user-images.githubusercontent.com/12730065/95068482-1326fe00-0751-11eb-8260-d182aeae5485.png)

It is also noted in Chrome's Lighthouse

![image](https://user-images.githubusercontent.com/12730065/95068558-2b971880-0751-11eb-9d78-79918f3961ba.png)

**Comment by sharatbaradia** [comment]
Any updates on this one? Looks like the all the files are being downloaded again.

**Comment by robotichead** [comment]
I am still replicating this issue - I feel like I should try and replicate this issue using just the native tinymce library to see if the issue steams that far up stream

**Comment by jscasca** [comment]
To the best of my knowledge, you can use `skin:false` and `content_css:false` to stop the editor from attempting to load the CSS. In that case you will need to manually load the CSS. Otherwise, the editor will try to load the files when initialising.

**Comment by robotichead** [comment]
Adding in `skin:false` and `content_css:false` causes TinyMCE not to load

**Comment by koukaicheng** [comment]
> 据我所知，您可以使用`skin:false`和`content_css:false`阻止编辑器尝试加载 CSS。在这种情况下，您将需要手动加载 CSS。否则，编辑器将在初始化时尝试加载文件。

Thanks

**Comment by robotichead** [comment]
I have upgraded to 5.0.1 - this issue is no longer appearing for me. I am happy to close
