### ISSUE TITLE
左键点击菜单栏没有反应，需要右键点击

### ISSUE THREAD

**Issue by name-liushuai** [tinymce/tinymce-vue#186]
鼠标左键点击菜单栏没有反应，需要鼠标右键点击才会生效

**Comment by jscasca** [comment]
Can you produce a replication case to better understand your issue?

**Comment by name-liushuai** [comment]
已经解决，是有其他依赖影响了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jscasca"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 中午12:56
收件人: "tinymce/tinymce-vue"<tinymce-vue@noreply.github.com&gt;; 
抄送: "刘帅"<2962878171@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tinymce/tinymce-vue] 左键点击菜单栏没有反应，需要右键点击 (#186)





 
Can you produce a replication case to better understand your issue?
