### ISSUE TITLE
I can't find what I'm looking for: dialog? Modal?

### ISSUE THREAD

**Issue by Nice2Work** [tinymce/tinymce-vue#192]
I can't get TinyMCE to work in a dialog or modal. It seems this issue is a long-standing issue (as I remember this when I was working with jQuery and the company was looking for an editor.

No matter what you choose (inline, full, basic) all popup dropdowns are BEHIND the dialog box. Almost having the wrong Z-INDEX. You can see the dropdown (partly) when the dialog box is small and I can provide the screenshot, not sure if you see this here below.

![image](https://user-images.githubusercontent.com/44038482/97821571-e8ad5f80-1c80-11eb-87b4-29231d8c555e.png)

**Comment by lnewson** [comment]
@Nice2Work you'll need to configure the z-index to be higher than whatever framework you're using. https://github.com/tinymce/tinymce/issues/6100#issuecomment-708571713 has some details on how to do that.

**Comment by Nice2Work** [comment]
Yes, this worked great, thanks a lot, and I applaud your helpdesk for your response times. Customer service at its best !!!
