### ISSUE TITLE
Struggles "exporting" TinyMCE's content from a component

### ISSUE THREAD

**Issue by Drillan767** [tinymce/tinymce-vue#194]
Hello!

I've been playing around with TinyMCE inside a VueJS project, and I have been struggling for ONE element:

I want to set the Wysiwyg inside a component, then "summon" it from a parent, have it slapped a v-model, and expecting it to return in a string the html it has. I have no trouble assigning it a value from a parent component, but I can't find a way to get its value: even after typing stuff in the editor, the parent's v-model is empty.

I've created a [CodeSandbox](https://codesandbox.io/s/tinymcevue-forked-3vmvt): I moved around the editor so it looks like in my project, and added a small textarea just under so you can see what I'm expecting. 

Apologies if it's a "newbie" issue but I couldn't frankly find a solution on the docs or StackOverflow .

**Comment by jscasca** [comment]
Hey @Drillan767 

You can try using the `v-model` directive, if you are using vue2.x, andjust go through the set/get. I modified your [codesandbox](https://codesandbox.io/s/tinymcevue-forked-x9eto?file=/src/Wysiwyg.vue), let me know if that works for you.

**Comment by Drillan767** [comment]
Hello!

Thanks, it works fine now, I didn't know such things were possible via a computed value!
