### ISSUE TITLE
is not working when use paste plugin when I copy paste same text content

### ISSUE THREAD

**Issue by Charlie50503** [tinymce/tinymce-vue#198]
**What is the current behavior? Describe the bug**
I used language tab to change tinymce content 
let l can input like en or jp text conent in same editor,
but when I full copy(ctrl + A & ctrl + C) en content to paste jp content (jp is nothing in the edtior)
v-model is not working 
input area had same content with en,but data is not change.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
<img src="https://user-images.githubusercontent.com/61115012/100945831-65b04b00-3545-11eb-8e21-be968c887261.png"  width="500" height="300" />
<img src="https://user-images.githubusercontent.com/61115012/100946043-dd7e7580-3545-11eb-8d5d-893a1fdc0b85.png"  width="500" height="300" />
<img src="https://user-images.githubusercontent.com/61115012/100946778-6ba72b80-3547-11eb-80cf-a1eefc2dc713.png"  width="500" height="300" />

**What is the expected behavior?**
data should be change when I ctrl + v

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
```
OS windws 10
"@tinymce/tinymce-vue": "^3.2.6",
"tinymce": "^5.6.1",
"vue": "^2.6.11",
```

I created an example 
[https://codesandbox.io/s/tinymce-paste-bug-3wuj3](https://codesandbox.io/s/tinymce-paste-bug-3wuj3)

**Comment by Charlie50503** [comment]
I using tinymce like my example in my project with more other language can be change.
how could I avoid this problem?
I have to check paste text size with use `paste_preprocess` if context is oversize I can overwrite this context and limit this text content.

is something solution

thank!

**Comment by Charlie50503** [comment]
I think I found solution with this problem

When I add this in my init
```
paste_preprocess: (plugin, args) => {
       this.my_value = args.content;
},
```
It's working!

although I have no idea what the reason is.

but I think maybe is the problem with paste plugin conflict with vue's v-model.
paste text content can showing on tinymce's textarea but v-model got nothing,
maybe v-model's watch was not distinguish dom changed when I doing paste total same text in same textarea
and this problem just happened at '123' → '' → '123'(is nothing in en's data)
won't happen at '123' → '1' → '123'(already has some text in en's data)

**Comment by jscasca** [comment]
Hi @Charlie50503 

This definitely looks like a bug in Tinymce. The problem is that the wrapper hooks on the editor events to propagate the changes, by default it hooks unto `change input undo redo`, and none of those events are triggered in this particular case. The particular case being pasting after setting the editor's content to `''` or empty.

One way to work around this issue is by changing the `modelEvents` property in the vue wrapper to add the `keyup` event.

In your example: 
```
<editor
      v-model="my_value"
      :init="init"
      modelEvents="change input keyup undo redo"
    ></editor>
```

Let me know if this helps

**Comment by Charlie50503** [comment]
Thanks for your reply!
`modelEvents="change input keyup undo redo"`
It's working for me
but I didn't tested all pattern,I just tested paste action with my case.
