### ISSUE TITLE
TinyMCE from npm invisible

### ISSUE THREAD

**Issue by Corben78** [tinymce/tinymce-vue#2]
When I use this component with a local install of tinymce from npm, the editor doesn't show up.

My custom vue component, using tinymce-vue looks like this:
```javascript
<template>
    <editor :init="{ plugin: ['paste', 'link']}"></editor>
</template>

<script type="text/javascript">
    import tinymce from 'tinymce/tinymce';
    import 'tinymce/themes/modern/theme';
    import 'tinymce/plugins/paste';
    import 'tinymce/plugins/link';

    require.context('file-loader?name=[path][name].[ext]&context=node_modules/tinymce!tinymce/skins', true, /.*/);

    import Editor from '@tinymce/tinymce-vue';

    export default {
        components: { Editor },
    }
</script>
```
This component is globally registered and used in a Laravel 5.5 view.

When not using the npm installed version, the cloud version shows up correctly.

When inspecting the html, I can see elements from TinyMCE, but they are hidden, e.g. the `div` has `style="visibility: hidden"` and beneath the `textarea` has `style="display: none"`. Making them manually visible doesn't help, as it's not properly shown. There are no errors in the javascript console nor in the apache2 log.

What am I missing?

**Comment by fyrkant** [comment]
Hmm, I think that you probably have to set the `skin_url` on the editor for it to find the files.

**Comment by Corben78** [comment]
Thank you @fyrkant! That hint was the right direction. In fact TinyMCE didn't find the skin.

I still had some problems though.

First I tried just so import the css files, which I've seen [here](https://github.com/tinymce/tinymce/issues/2914#issuecomment-319552104), This kinda works, but I didn't show any icons then. But I realized that the missing css files must be the problem.

Looks like the `require.context` command didn't copy all files from the skin directory. So I copied them manually to my `public` folder in Laravel. Setting `skin_url: '/skins/lightgray'` still didn't work, as I'm not using a virtual host, but a subdirectory with a config file in apache. To get the proper path to the Laravel app I'm setting a global variable window.App.base_url, which I tried to use here: `skin_url: window.App.base_url + '/skins/lightgray'`. This disabled the element completely. So I'm using now a Vue variable for this, and it is working.

Here is the complete snippet:
```javascript
<template>
    <editor :init="{ branding: false, plugins: ['paste', 'link'], skin_url: skinurl }"></editor>
</template>

<script type="text/javascript">
    import tinymce from 'tinymce/tinymce';
    import 'tinymce/themes/modern/theme';
    import 'tinymce/plugins/paste';
    import 'tinymce/plugins/link';

    //require.context('file-loader?name=[path][name].[ext]&context=node_modules/tinymce!tinymce/skins', true, /.*/);

    import Editor from '@tinymce/tinymce-vue';

    export default {
        data() {
            return {
                skinurl: window.App.base_url + '/skins/lightgray'
            }
        },

        components: { Editor },
    }
</script>
```

**Comment by Corben78** [comment]
Small addition... the `require.context()` does work. It just doesn't work with my setup. It copies the file to my `public/fonts/vendor/tinymce/skins` and `public/images/vendor/tinymce/skins`directories, als well as it creates files below `public/skins` which contain js code to redirect to the files in the directories above.

I guess with a vhost, where the Laravel app is located in the document root this does all work properly, in my case though I removed that `require.context()` command and added the following line to my `webpack.mix.js` file:
```javascript
mix.copyDirectory('node_modules/tinymce/skins', 'public/skins');
```
I addition with the `skin_url` mechanism above it works as intended.

**Comment by fyrkant** [comment]
I think the best way is just copying the files manually to where you have your other static files and don't mix in webpack with that at all.
