### ISSUE TITLE
codesample doesn't work

### ISSUE THREAD

**Issue by drinkingcode** [tinymce/tinymce-vue#206]
**configuration**

`"@tinymce/tinymce-vue": "^3.2.0",`

index.html
`<link rel="stylesheet" type="text/css" href="prism.css" />
    <script src="prism.js"></script>`

`<editor
      :init="{
        height: 600,
        menubar: false,
        plugins: [
          ' lists table codesample link image tinydrive  media preview',
        ],
        toolbar:
          'undo redo | formatselect fontselect fontsizeselect | bold italic underline strikethrough forecolor backcolor | \
        alignleft aligncenter alignright outdent indent | \
        bullist numlist table | codesample link image insertfile media | preview ',
        codesample_languages: [
          //配置语言的下拉框
          { text: 'JavaScript', value: 'javascript' },
          { text: 'CSS', value: 'css' },
          { text: 'C', value: 'c' },
          { text: 'C++', value: 'cpp' },
          { text: 'Python', value: 'python' },
          { text: 'Java', value: 'java' },
          { text: 'HTML/XML', value: 'markup' },
        ],
        codesample_global_prismjs: true,
        language: 'zh_CN',
      }"
      apiKey=""  //my apiKey
    >
    </editor>`

**problem**
code doesn't highlight  by codesample plugin 

**expect**
code can highlight

**Comment by jscasca** [comment]
Are you trying a custom theme or just default prism? Seems to be working properly

![prismjs](https://user-images.githubusercontent.com/6062777/104411647-7dec9e80-55b6-11eb-9ef8-508388942676.png)

**Comment by drinkingcode** [comment]
> Are you trying a custom theme or just default prism? Seems to be working properly
> 
> ![prismjs](https://user-images.githubusercontent.com/6062777/104411647-7dec9e80-55b6-11eb-9ef8-508388942676.png)

if you click preview button, it doesn't work properly，you can try it !

**Comment by jscasca** [comment]
That is currently a known bug that the preview plugin will not highlight content as it requires to run prism over the content and the preview plugin was not build with that functionality in mind.

Unfortunately, that is not related to the vue wrapper. You'll have to open an issue on the `tinymce` repo to follow up on the resolution of that case.
