### ISSUE TITLE
is text will disappear when I do paste same text in the editor(Chrome,old edge)

### ISSUE THREAD

**Issue by Charlie50503** [tinymce/tinymce-vue#207]
**What is the current behavior?**
when I paste same text in editor, paste content  will disappear.
pattern 1.
①input '123'
②ctrl+A
③ctrl+V
④content is disappear.
![tinymce-paste-bug-demo-2](https://user-images.githubusercontent.com/61115012/103504460-cd3a1d00-4e9a-11eb-8e59-ca7939359cda.gif)
pattern 2.
①input '123456'
②select '456' (down)
③ctrl+V to '456' (up)
④content is disappear.
![tinymce-paste-bug-demo-1](https://user-images.githubusercontent.com/61115012/103504494-eb078200-4e9a-11eb-963a-7f11cf98b73b.gif)
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io]
[example](https://codesandbox.io/s/tinymce-paste-plugin-bug2-1eq2i?file=/src/views/Home.vue)

**What is the expected behavior?**
when I pasted same content on text will not disappear .will be cover old content by new content.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
```
browser : Chrome 87,edge 44
OS: windows 10
tinymce-vue: 3.2.6
tinymce: 5.6.0
vue: 2.6.12
```

**Comment by jscasca** [comment]
Hi @Charlie50503 

This is a very weird and specific case in which the `paste` plugin is not playing nice with the `input` event triggering a backwards deletion that the wrapper emits and fails to finish with the `insertFromPaste`. I'm not sure why this is happening but the only workaround I can provide at the time would be to change the wrapper `modelEvents` and remove the `input` event.
```
<editor
      v-model="my_value"
      modelEvents="change keydown undo redo"
      :init="init"
    ></editor>
```

[Code Sandbox](https://codesandbox.io/s/tinymce-paste-plugin-bug2-forked-h4osh?file=/src/views/Home.vue)

**Comment by Charlie50503** [comment]
Thanks for your reply.

I will try it.

**Comment by jscasca** [comment]
Did this work for you use case? I'm going to close this ticket but feel free to reopen it if that workaround is not enough
