### ISSUE TITLE
when I using vue's keepalive in edge got "TypeError: Object expected" error

### ISSUE THREAD

**Issue by Charlie50503** [tinymce/tinymce-vue#208]
**What is the current behavior?**
<img src="https://user-images.githubusercontent.com/61115012/103711362-9b3fcc80-4ffa-11eb-980a-b89ecd4d5af4.png"  width="800" height="300" />
![tinymce-edge-bug](https://user-images.githubusercontent.com/61115012/103711732-5ff1cd80-4ffb-11eb-8847-c5efc6756eca.gif)

example: 
https://codesandbox.io/s/tinymce-test-for-edge-3okki?file=/src/App.vue

**What is the expected behavior?**
not error log.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
```
OS windws 10
@tinymce/tinymce-vue: 3.2.6,
tinymce: 5.6.0",
vue: 2.6.12,
```

**Comment by jscasca** [comment]
Sorry I could not replicate this issue on Edge, what version of Edge are you using? Have you tried in the latest version?

**Comment by Charlie50503** [comment]
Sorry .I forgot to add the browser version.
`Edge 44.18362.449.0`

**Comment by jscasca** [comment]
I'm using that same version but can't replicate the issue you are seeing with your provided sandbox. Could you be missing a polyfill in your project?

**Comment by Charlie50503** [comment]
Hi @jscasca 
If you are asking an I use polyfill.
Yes. This is My setting
I'm using vue/cli's [babel-preset-app#polyfills API](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app#polyfills)
my setting is working in IE.
So I think is also working Edge.
```
//babel.config.js
module.exports = {
	plugins: [],
	presets: [
		[
			"@vue/app",
			{
				"useBuiltIns": "entry",
				polyfills: [
					'es6.promise',
					'es6.symbol'
				]
			}
		],
	],
	comments: false,
};

```

**Comment by Charlie50503** [comment]
The old edge does not exist after the windows 10 update, so close this issue.
