### ISSUE TITLE
This domain is not registered with TinyMCE Cloud. Start a free trial to discover our premium cloud services and pro support.

### ISSUE THREAD

**Issue by vortechron** [tinymce/tinymce-vue#22]
can some one show me step by step on how to remove this error? i dont want to use tinymce cloud or register anything, all i want is to use tinymce community version.

**Comment by bmarz** [comment]
Does this help? => https://github.com/tinymce/tinymce-vue#loading-tinymce-by-yourself 👍

**Comment by vortechron** [comment]
@bmarz using tinymce.min.js solve my problem, but i want to use it in npm loader, how to do it?

**Comment by bmarz** [comment]
@vortechron

After running `npm i tinymce`, I did the following: 

In my javascript bundle:

- import "tinymce/tinymce" 
- import "tinymce/themes/modern/theme"

In my scss bundle:

- import "~tinymce/skins/lightgray/skin.min.css".

Hope this helps 👍

**Comment by skunkwerk** [comment]
The instructions don't work:

Even when I put the following in my Vue app, it loads, but I still see the warning message:

import Editor from '@tinymce/tinymce-vue';

  export default {
    components: {
      'editor': Editor // <- Important part
    }....

in the html section
<editor></editor>

**Comment by milp** [comment]
I would also like to know.

**Comment by fyrkant** [comment]
Closing this as it's not a problem with the wrapper component.
