### ISSUE TITLE
Vue 2.x documentation / storybook link returns a 404 error

### ISSUE THREAD

**Issue by ericmschow** [tinymce/tinymce-vue#221]
**What is the current behavior?**
The documentation for how to implement it in older versions of Vue doesn't work. This link: https://tinymce.github.io/tinymce-vue/ shows a 404 error for me
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**
Click the link above.
**What is the expected behavior?**
There is documentation that shows me the correct way to implement this for Vue 2.x, because my attempts to do it without documentation have been failures.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
All of them presumably, it's a web link.

**Comment by jscasca** [comment]
Hi @ericmschow 

Thanks for bringing this up. We have updated the storybook in github pages. 

Are you still having issue implementing the Editor in Vue? You can always use the [TinyMCE vue integration](https://www.tiny.cloud/docs/integrations/vue/) documentation as a starting point. Let me know if you have any difficulties getting this working.
