### ISSUE TITLE
Editor stops working after route change VueJS 2 + Vuetify + TinyMCE 3

### ISSUE THREAD

**Issue by emailnikola** [tinymce/tinymce-vue#223]
"vue": "^2.6.11"
"vuetify": "^2.2.11"
"@tinymce/tinymce-vue": "^3.2.8"

Editor stops working after route changes.
When editor initally loads on some page two following requests get sent and get processed properly (css content returns):
https://cdn.tiny.cloud/1/my_id/tinymce/5.7.0-107/skins/ui/oxide/content.min.css
https://cdn.tiny.cloud/1/my_id/tinymce/5.7.0-107/skins/content/default/content.min.css

After I navigate to some other route and try to load editor there both routes get called again but this time network shows these two requests as CANCELLED.

**Comment by jscasca** [comment]
@emailnikola Do you have a code sandbox or a replication case on github that we can use?

**Comment by ferdynator** [comment]
I have an issue with a similar stack. It appears as hiding and revealing the vue tinymce component again renders it useless. There is no content in the editor input area and the controls are unresponsive. Quickest example I was able to come up with is using a vuetify modal:

```vue
<template>
  <div class="hello">
  <v-dialog
      v-model="dialog"
      persistent
      max-width="1200px"
  >
    <template #activator="{ on, attrs }">
      <v-btn
          color="primary"
          v-bind="attrs"
          v-on="on"
      >
        <v-icon>
          mdi-plus
        </v-icon>
        Open dialog
      </v-btn>
    </template>
    <TinyMce
        :content="editorContent"
        @update:content="editorContent = $event"
    />
  </v-dialog>
  </div>
</template>

<script>
import TinyMce from "@/components/Editor";

export default {
  name: 'HelloWorld',
  components: {TinyMce},
  data() {
    return  {
      editorContent: 'test',
      dialog: null,
    }
  }
}
</script>

<style scoped>
</style>
```

and Editor.vue:

```vue
<template>
  <Editor
      :initial-value="content"
      :init="init"
      @onChange="updateContent"
  />
</template>

<script>
import tinymce from 'tinymce/tinymce';
import Editor from '@tinymce/tinymce-vue';
import 'tinymce/themes/silver';
import 'tinymce/icons/default';

import 'tinymce/plugins/image';
// ...

export default {
  name: 'TinyMce',
  components: {
    Editor
  },
  props: {
    content: {default: () => '', type: String}
  },
  emits: ['update:content'],
  data() {
    return {
      init: {
        plugins: [
          'lists advlist',
        ],
        toolbar:  'undo redo code',
      }
    }
  },
  methods: {
    updateContent($event, editor) {
      this.$emit('update:content', editor.getContent())
    },
  }
}
</script>
```

**Comment by emailnikola** [comment]
I confirm that this idea solved the issue.

setTimeout(() => {this.showEditor = true}, 200);

Thank you @ferdynator
