### ISSUE TITLE
setAttribute in objectResized event is not reactive

### ISSUE THREAD

**Issue by 604587986** [tinymce/tinymce-vue#226]
**What is the current behavior?**
setAttribute in objectResized event is not reactive,but use function getAttribute will get changed value

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**
https://codesandbox.io/s/long-hooks-j9cl7?file=/src/App.vue

**What is the expected behavior?**
how to change content when i use setAttribute function 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
4.0.0

**Comment by jscasca** [comment]
Hi @604587986 

You can use the `modelEvent` property of the wrapper and add `nodeChange` to emit changes when this triggers.
```
<editor
      api-key="ljx6g779252ge7s7znozes906uzq4qxcr4p4di9eow87vxdf"
      v-model="bindValue"
      modelEvents="change undo redo input nodeChange"
      @objectResized="handleImgResize"
    />
```

Or you can fire a `change` event from the editor after manually changing the attributes.
```
handleImgResize(e, editor) {
      if (e.target.nodeName === "IMG") {
        e.target.setAttribute("data-width", e.width);
        e.target.setAttribute("data-height", e.height);
        this.dataWidth = e.width;
        this.dataHeight = e.height;
        editor.fire('change');
      }
    },
```

Let me know if this helps

**Comment by 604587986** [comment]
> Hi @604587986
> 
> You can use the `modelEvent` property of the wrapper and add `nodeChange` to emit changes when this triggers.
> 
> ```
> <editor
>       api-key="ljx6g779252ge7s7znozes906uzq4qxcr4p4di9eow87vxdf"
>       v-model="bindValue"
>       modelEvents="change undo redo input nodeChange"
>       @objectResized="handleImgResize"
>     />
> ```
> 
> Or you can fire a `change` event from the editor after manually changing the attributes.
> 
> ```
> handleImgResize(e, editor) {
>       if (e.target.nodeName === "IMG") {
>         e.target.setAttribute("data-width", e.width);
>         e.target.setAttribute("data-height", e.height);
>         this.dataWidth = e.width;
>         this.dataHeight = e.height;
>         editor.fire('change');
>       }
>     },
> ```
> 
> Let me know if this helps

These are effective, thank you！
