### ISSUE TITLE
I can't find what I'm looking for: integrations/vue.md

### ISSUE THREAD

**Issue by grzesiekb** [tinymce/tinymce-vue#228]
whether I can create my own vue components inside the editor.

**Comment by jscasca** [comment]
Hi @grzesiekb 

Unfortunately, most of TinyMCE only accepts js functions, objects and strings. You can probably work around that by creating your own dialogs but they will not leverage the TinyMCE apis which kind of defeats the purpose. Is there any particular thing you want to achieve?
