### ISSUE TITLE
Add the specified class to the specified label

### ISSUE THREAD

**Issue by lovelike123** [tinymce/tinymce-vue#232]
For example, A tag adds class1, P tag adds class2.
 <a class="class1"></a>
<p class="class2"></p>

**Comment by jscasca** [comment]
Hi @lovelike123 

You can probably use a formatting option to define your tags as formats. You can find more information here: [TinyMCE content formatting](https://www.tiny.cloud/docs/configure/content-formatting/#formats)

Or you can probably use a parser or serializer to filter the content and add the classes per node. You can find more information here: [https://www.tiny.cloud/docs/api/tinymce.html/tinymce.html.domparser/](https://www.tiny.cloud/docs/api/tinymce.html/tinymce.html.domparser/)

Let me know if that helps
