### ISSUE TITLE
I can't find what I'm looking for: how to use it in vue3.0

### ISSUE THREAD

**Issue by starting-outcome** [tinymce/tinymce-vue#233]

**Comment by jscasca** [comment]
Hi @starting-outcome 

The latest release of the TinyMCE-vue wrapper supports Vue 3.0. You can find more information in the [TinyMCE-Vue quick start guide](https://www.tiny.cloud/docs/integrations/vue/#tinymcevuejsintegrationquickstartguide)

You can follow that tutorial to get started and follow up with specific questions if you hit a roadblock
