### ISSUE TITLE
Adding Vue component in editor.ui.registry.addAutocompleter

### ISSUE THREAD

**Issue by shrnetomi** [tinymce/tinymce-vue#234]
**Is your feature request related to a problem? Please describe.**
Unable to add already created Vue component in autocompleter

 **Describe the solution you'd like**
Code can be written such a way that it would render Vue components in tinymce autocompleter.

 **Describe alternatives you've considered**
Adding customise css may help.

**Comment by jscasca** [comment]
Hi @shrnetomi 

The Tinymce [Autocompleter](https://www.tiny.cloud/docs/ui-components/autocompleter/) has a very specific API to let users easily add and display items. You can customise and add classes although is recommended to only add styles that do not affect the layout.

Unfortunately, this repository is only for issues related to the wrapper around TinyMCE in Vue and not for issues with the editor. What you are suggesting is a feature request that should be open in the [TinyMCE repository](https://github.com/tinymce/tinymce)

**Comment by shrnetomi** [comment]
ok thanks @jscasca
