### ISSUE TITLE
Accessing the Vue component from TinyMCE setup

### ISSUE THREAD

**Issue by marcbelletre** [tinymce/tinymce-vue#236]
Hi,

I'm trying to create a button which opens a custom media library modal. I already did this a few years ago using jQuery but can't find a way to make it work within a Vue component.

I added a TinyMCE editor inside a Vue component which already has a `openLibrary()` method. 
The `openLibrary()` method basically changes a boolean value which controls whether the modal is displayed or not.  

I tried to add the following configuration to the `init` object:
```js
setup: function (editor) {
    function openLibrary () {
        // Call the component's openLibrary() method
        // this.openLibrary()
    }

    editor.ui.registry.addButton('image', {
        icon: 'image',
        tooltip: "Insert image from library",
        onAction: openLibrary
    })
}
```

In this context, `this` is not referencing the component so it doesn't work. Is there any other way to access the component from here?

**Comment by jscasca** [comment]
Have you tried defining the function outside the editor setup context?

For exmaple:
```
<template>
  <editor
    api-key="qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc"
    :init="init"
  ></editor>
</template>

<script>
import Editor from "@tinymce/tinymce-vue";

export default {
  name: "App",
  components: {
    editor: Editor,
  },
  data() {
    const openLib = this.openLibrary;
    return {
      init: {
        toolbar: ["undo redo", "openlib"],
        setup: (editor) => {
          editor.ui.registry.addButton("openlib", {
            icon: "custom",
            onAction: openLib,
          });
        },
        height: 500,
      },
    };
  },
  methods: {
    openLibrary: () => {
      console.log("opening library?");
    },
  },
};
</script>
```

Let me know if that helps

**Comment by marcbelletre** [comment]
Hi @jscasca,

That did the trick! I found a similar solution in the meantime and was about to post it but yours is way better.

Thank you very much for your help!
