### ISSUE TITLE
One event to catch them all

### ISSUE THREAD

**Issue by lebadapetru** [tinymce/tinymce-vue#248]
Yeah the title sounds too broad but i couldn't think of anything better, so just hear me out
I'm trying to make a wrapper around tinymce to use in my project and i came across the following bump:

`I need to fire two different events ( maybe more ) for each type of change. @keyup for typing and @change for inserting medial urls`

VTinyMCE.vue :

```
<template>
  <editor
      :api-key="apiKey"
      :init="config"
      v-model="modelValue"
      @input="onInput"
      @change="onInput"
  />
</template>

<script>
import Editor from '@tinymce/tinymce-vue'

export default {
  name: "VTinyMCE",
  components: {
    editor: Editor
  },
  props: {
    modelValue: {
      type: String,
      default: ''
    },
    name: {
      type: String,
      default: 'description'
    }
  },
  emits: ['update:modelValue'],
  setup(props, { emit }) {

    const onInput = (event, editor) => {
       //some other stuff
       emit('update:modelValue', editor.getContent())
    }

    //return
  }
}
</script>
```

ComponentUsingTheWrapper:

```
<VTinyMCE v-model="description" />
```

The problem with this approach is that the `onInput` gets triggered twice which duplicates the process following the change and i was wondering if another event exists or can be implemented to catch all kinds of change events?
Something like this but translated for vue:

```
tinymce.init({
    // ...
    setup: function(editor) {
        editor.on('Paste Change input Undo Redo Keyup', function () {
            //do something
        });
    }
    // ,...
});
```

**Comment by jscasca** [comment]
Hi @lebadapetru 

Unfortunately, there is no Vue specific way to achieve that. Have you tried emitting the change from the TinyMCE config?
```
<editor :init="tinyConf"/>
...
tinyConf = {setup: (editor) => {
  editor.on('change input', () => {
    this.$emit('update:modelValue', editor.getContent());
  });
}}
```

**Comment by jscasca** [comment]
I think this should work better in your setup: 
```
  setup(props, {emit}) {
    const conf = {
      setup: (e) => {
        e.on('change input', () => {
          console.log('input: ', e.getContent());
          // emit here
        })
      }
    };
    return {
      conf
    };
  },
 ```

**Comment by lebadapetru** [comment]
Now i got multiple emits because the change event triggers when the state is changed, input also fires with it because an input has been made and when i click out of the editor, the change gets triggered again... So it kind of behaves like it did before. I'm not really sure why there isn't a way to just catch the input, whatever it may be: media inserts, copy/paste, typing, etc... I just want to trigger a setter so i can update the state without having multiple calls for the same purpose

**Comment by jscasca** [comment]
Oh sorry, that was on me. I thought you wanted to fire the same function from multiple events. The wrapper is open to allow users to define how they interact with all the different events, so they can work around any particular goal they want to achieve.

If you want to emit a model value change on every event you can use the [`modelEvent` property](https://www.tiny.cloud/docs/integrations/vue/#model-events) to add any event you consider relevant. If you want to add you own code in there you will have to define your own event handlers and emit the change after you change those value.

**Comment by jscasca** [comment]
@lebadapetru I think what you are trying to achieve can work like this:
```
<editor :init="conf" modelEvent="" />
...
setup(props, {emit}) {
    let cache = '';
    const conf = {
      setup: (e) => {
        e.on('change input keyup keydown undo redo nodechange', () => {
          if (e.getContent() !== cache) {
            cache = e.getContent();
            console.log('change to: ', cache);
            // emit change here
          }
        })
      }
    };
    return {
      conf
    };
  },
  ```
