### ISSUE TITLE
Broken link to Vue2 integration

### ISSUE THREAD

**Issue by edwardsph** [tinymce/tinymce-vue#249]
**Documentation/Product Version**
TinyMCE 5 Documentation

**Links to Page(s) affected**
https://www.tiny.cloud/docs/integrations/vue/#tinymcevuejsintegrationquickstartguide

**Description of Issue**
The link to the storybook below is a 404:
`For examples of the TinyMCE Vue.js 2.x integration, visit: the tinymce-vue storybook.`

**Comment by jscasca** [comment]
![gh-pages](https://user-images.githubusercontent.com/6062777/120449593-e952d380-c3d2-11eb-9947-28b77580280f.png)

**Comment by jscasca** [comment]
@edwardsph page should be back online at https://tinymce.github.io/tinymce-vue/
