### ISSUE TITLE
Multi-word component name

### ISSUE THREAD

**Issue by SimplyThomas** [tinymce/tinymce-vue#25]
Using <editor> as the component name breaks a VueJs styleguide's Priority A (Essential for Error Prevention) rule: https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential 

This rule was created by the VueJS core team to follow the W3C Web Components specification for valid custom element names: http://w3c.github.io/webcomponents/spec/custom/#valid-custom-element-name

This would obviously be a breaking change, but it is extremely important especially since the W3C will not add any new HTML, SVG, or XML elements with hyphens in them in the future.

**Comment by fyrkant** [comment]
So the fix should be to change the name from `editor` to something like `editor-component` or `tinymce-editor` or something like that?

**Comment by SimplyThomas** [comment]
That would be correct.

<vue-editor>, <v-editor>,<editor-component>. <tinymce-editor>, or any other flavor would suffice.

**Comment by fyrkant** [comment]
@SimplyThomas I thought about this today and I can't really see _where_ this name should be changed, only in the readme? Because you just set whatever name you want when adding it to your app like this:
```
var app = new Vue({
  el: '#app',
  data: { /* Your data */ },
  components: {
    'editor': Editor // <- Important part
  },
  methods: { /* Your methods */}
})
```

**Comment by SimplyThomas** [comment]
@fyrkant while you can set the component name as whatever you want, the default variable name should follow the specification.

Like you said, when registering the Vue components, you can override this default variable name by setting the object key to the desired value. So when registering it, you have the option to name it whatever you want.

```js
var app = new Vue({
  el: '#app',
  data: { /* Your data */ },
  components: {
    'tinymce-editor': Editor, // <- override the default component name
    Editor, // <- this sets the component name as <editor> by default
  },
  methods: { /* Your methods */}
})
```
You could just change it in the README and that should catch the 99% use-case, but because you're also making the recommendation to import from an inline `<script>`, the variable that's being exported should ideally match what your recommendation is.

In `rollup.build.js` the `browserBuildOptions.name` field would need to change
```js
const browserBuildOptions = { 
  file: 'lib/browser/tinymce-vue.js',
  format: 'iife',
  name: 'Editor', 
  globals: {
    vue: 'Vue'
  } 
};
```

The variable name would need to change from `Editor` to something of your choosing (i.e. `TinymceEditor`, `TinyMceEditor`, `VEditor`)

Keep in mind, that when registering Vue components, PascalCase variables automatically get translated to slugged variants wherever the capitalization is. My examples above would translate to `<tinymce-editor>`, `<tiny-mce-editor>` and `<v-editor>` respectively.

This will also help future-proof this component for use in render functions. While Vue will allow you to override native HTML Elements with a render function, they warn you when it does happen and strongly discourage it. The following example would still work, even if there were a native `<editor>` element.

```html
    <script>
        new Vue({
          render: h => h(Editor),
        }).$mount('#app')
    </script>
```

I hope this helped. 🍻

**Comment by SimonFc** [comment]
@SimplyThomas Great answer. It was a while since you wrote here but I would like to confirm a few things. In no scenario are you forced to use `<editor></editor>` as in all cases it's possible to define what tag name to use tinymce-vue as, right?

And in your last example with
```
new Vue({
    render: h => h(Editor),
}).$mount('#app')
```
it would render in place of an element with an `#app` id, nowhere do I see that it would register the component as `<editor>`?

I fully agree that we should update the readme so that it follows best practices, it's just that we want to avoid breaking changes whenever it's not absolutely needed:)

**Comment by SimplyThomas** [comment]
> @SimplyThomas Great answer. It was a while since you wrote here but I would like to confirm a few things. In no scenario are you forced to use `<editor></editor>` as in all cases it's possible to define what tag name to use tinymce-vue as, right?

That is correct. You are able to customize and register the component to use a different name when registering it. It is not forced, but the default convention that is being conveyed through example is to register it as `<editor>`.
> And in your last example with
> 
> ```
> new Vue({
>     render: h => h(Editor),
> }).$mount('#app')
> ```
> 
> it would render in place of an element with an `#app` id, nowhere do I see that it would register the component as `<editor>`?
> 
> I fully agree that we should update the readme so that it follows best practices, it's just that we want to avoid breaking changes whenever it's not absolutely needed:)
That is also correct. The issue is future-proofing. If there is ever an introduction of a native `<editor>` element, it would cause issues with this library. The W3C's specification for web components allows for two-hyphenated words to be used for custom elements. This is to prevent custom elements from overlapping with native elements.

Again, this is more a best practice than a current bug/issue.

**Comment by SimonFc** [comment]
And of course, what we recommend should be what's considered best practice. I've updated the readme to use a multi-word example(`<tinymce-editor>`).

Thanks for shedding some light on this issue! I'll be closing this now since this has been fixed
