### ISSUE TITLE
I can't find what I'm looking for: demo/local-upload.md

### ISSUE THREAD

**Issue by Hirvi25** [tinymce/tinymce-vue#250]
'Browse for an Image' option in upload tab is not working in vue js

**Comment by jscasca** [comment]
@Hirvi25 I can't see any issue what seems to be the problem? What Browser and Vue version are you using?

Can you send a simple replication if this is not working for you? https://codesandbox.io/s/tinymcevue-forked-8dh9v?file=/src/App.vue
