### ISSUE TITLE
工作流程：用户通过图像对话框插入任意图片链接并点击确定>web回调方法将链接传递到服务端>服务端校验图片是否合格>上传至私有的图库并返回图库链接>web回调方法接收图库链接插入到文本域内

### ISSUE THREAD

**Issue by taozuidesongshu** [tinymce/tinymce-vue#259]
工作流程：用户通过图像对话框插入任意图片链接并点击确定>web回调方法将链接传递到服务端>服务端校验图片是否合格>上传至私有的图库并返回图库链接>web回调方法接收图库链接插入到文本域内

Work flow: The user inserts any picture link through the image dialog box and clicks OK>web callback method to pass the link to the server>server verifies whether the picture is qualified>upload to a private gallery and return to the gallery link>web callback method to receive the gallery link Insert into the text field

1.这极大方便了用户，不用通过图片上传就可以插入图片，同时节省了用户的流量消耗。
2.方便网站维护自己文章内容和图库的同时鉴别图片是否符合规定

1. This greatly facilitates users, as they can insert pictures without uploading them, and at the same time saves users' data consumption.
2. It is convenient for the website to maintain its own article content and gallery while identifying whether the image meets the regulations

_Originally posted by @taozuidesongshu in https://github.com/tinymce/tinymce/issues/6369#issuecomment-864848444_

**Comment by jscasca** [comment]
Hi @taozuidesongshu , this is a repo for issues concerning only the vue wrapper. What you are suggesting is better addressed in the TinyMCE repo. I suggest following up on your opened issue since the wrapper can't provide functionalities beyond what the editor can do.
