### ISSUE TITLE
如何使用本地资源

### ISSUE THREAD

**Issue by orochitian** [tinymce/tinymce-vue#264]
依照教程，使用 tinymce-vue 后发现：
依赖的文件加载全部来自于CDN网络。
如何使用本地的相关文件呢？

**Comment by jscasca** [comment]
Hi @orochitian 

If you want to avoid the CDN you can have a self hosted TinyMCE and use the `tinymceScriptSrc` property to load that specific version. It's easier to make the TinyMCE folder public than to import each element.

**Comment by orochitian** [comment]
@jscasca 
你好，非常感谢你的回答，他确实解决了我遇到的问题！
