### ISSUE TITLE
@on-change event does not fire when content changes 

### ISSUE THREAD

**Issue by jthannah** [tinymce/tinymce-vue#265]
**What is the current behavior?**
The @on-change event never fires

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**
Simply open the codesandbox here: https://codesandbox.io/s/vue3-example-forked-6rbfp?file=/src/App.vue
Type something in the editor, it should print the message in the console

**What is the expected behavior?**
The @on-change event fires when the content of the editor changes

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
TinyMCE/vue 4.0.4
Firefox 90
Chrome 91

**Comment by jscasca** [comment]
@jthannah 

You can use `@change` or `v-on:change` to bind the event. Keep in mind that the `change` event of TinyMCE will not trigger in every content change but when the content is committed. From the [docs](https://www.tiny.cloud/docs/advanced/events/):
> Fired when the editor content changes have been committed, such as when moving focus away from the editor.

**Comment by jthannah** [comment]
@jscasca Thanks for the reply. The initial confusion was caused by this documentation mentioning `onChange` : https://www.tiny.cloud/docs/integrations/vue/#eventbinding

However, I was looking for something that would give me more 'real-time' updates on the content. I've ended up using the `setup` function in the `init` prop: 
```
setup: (editor: Editor) => {
     editor.on('init', () => {
          if (pageDescription) {
            editor.setContent(pageDescription)
          }
     })
    editor.on('input', () => {
          handleDescriptionChange(editor.getContent())
    })
    editor.on('change', () => {
          handleDescriptionChange(editor.getContent())
    })
    }
}
```
