### ISSUE TITLE
Placeholder doesn't work

### ISSUE THREAD

**Issue by mfrro** [tinymce/tinymce-vue#270]
**What is the current behavior?**
When initializing an editor using v-model and the placeholder attribute, the placeholder isn't shown.
```
<editor v-model="html" :init="config" />

config = {
  inline: true,
  placeholder: 'Text',
}

html = ''
```

**What is the expected behavior?**
When the v-model value is falsy the placeholder should be shown.

**Versions**
tinymce-vue@4.0.4
tinymce@5.8.2
vue@3.1.5

**Comment by jscasca** [comment]
Sorry can't replicate this issue: https://codesandbox.io/s/keen-stitch-08iyq?file=/public/index.html

@mfrro If you can provide a replication I can look into it

**Comment by mfrro** [comment]
@jscasca I looked at it again and it turns out this only happens when tinymce isn't loaded from the cloud but is installed with npm and imported in the main.js. There's probably a conflict with the global config and the local Editor config.  
Other init settings (like toolbar) can be set locally.  
Here's a replication: https://codesandbox.io/s/mutable-frost-4e7bn?file=/public/index.html

**Comment by jscasca** [comment]
@mfrro that's actually a problem with the skin/css stuff. When you are importing stuff from npm you have to load some things yourself, like the skin and css. More info on this can be found in the [module-loader docs](https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/webpack/webpack_es6_npm/#procedure)

Anyway this should work: https://codesandbox.io/s/nervous-satoshi-bwvbg?file=/src/App.vue

I do think it's easier to put the tinymce folder in the public folder and just load the `tinymce.min.js` in your `index.html`

Let me know if you have trouble with that or if you think I should re-open the issue.

**Comment by mfrro** [comment]
@jscasca Thanks for your help! Moving the tinymce folder to the public folder resolved the issue.

**Comment by ahelmi365** [comment]
I've the same issue in React
