### ISSUE TITLE
DOM XSS

### ISSUE THREAD

**Issue by Yakir6** [tinymce/tinymce-vue#271]
**What is the current behavior?**
`<redacted>`

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**
`<redacted>`

**What is the expected behavior?**
`<redacted>`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
tinymce-vue@4.0.4
tinymce@5.8.2
vue@3.1.5

**Comment by lnewson** [comment]
Hi @Yakir6,

Thank you for bringing this matter to our attention. We're looking into this, however for now we've edited the original post to remove the replication information as this pertains to a potential security vulnerability.

If you'd like to follow-up on this issue, provide more information or log future security reports, please do so by emailing infosec@tiny.cloud. Please see [Reporting TinyMCE Security Issues](https://www.tiny.cloud/docs/advanced/security/#reportingtinymcesecurityissues) for more information.

Thanks again for your help in ensuring the security of our products.

**Comment by lnewson** [comment]
This issue was fixed in TinyMCE 5.10.0.
