### ISSUE TITLE
Vuetify dialog, can't write in source code editor or insert code sample

### ISSUE THREAD

**Issue by Wolffyx** [tinymce/tinymce-vue#278]
**What is the current behavior?**

When I open the dialog with the editor the editor does not work as intended.

One small problem is that the editor sometimes does not initialize correctly and I can't write, sometimes it does but some plugins does not work or I cant focus it because I have an input in the same dialog(I need the inputs in the dialog). The plugins are source code editor and insert code sample.

The steps are this, after I open the model and with luck the editor initialize I write some random text on the editor after that I am trying to edit the source code and when I open it(the source code editor) I can't click it to edit the content the focus is on the input that is on the dialog with the editor. Same goes for the Insert Code Sample.

![image](https://user-images.githubusercontent.com/14310774/141484798-1b840d07-cec1-457a-87dd-c145d89ec970.png)
Focused on the input:
![image](https://user-images.githubusercontent.com/14310774/141484895-e1e5bd28-59dd-48f7-8c5f-40d3852e9ae6.png)

 ​

Example here: [codesandbox.io](https://codesandbox.io/embed/tinymce-vue-forked-1uped?fontsize=14&hidenavigation=1&theme=dark)

**What is the expected behavior?**

When I open the modal the editor to get initialized every time and all plugins to work, Source code editor and Insert Code Sample to focus correctly and let me write.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**

The  version o the editor is "@tinymce/tinymce-vue": "^3.0.1", Chrome,  OS: Windows. I only tested on tinymce-vue.

**Comment by lnewson** [comment]
This was answered in https://stackoverflow.com/questions/70028032/tinymce-vuetify-dialog-cant-write-in-source-code-editor-or-insert-code-sample so I'm going to close this. Let us know if you are still experiencing issues though and we'll reopen this.
