### ISSUE TITLE
tinymce-vue with tinymce NPM package

### ISSUE THREAD

**Issue by zwik** [tinymce/tinymce-vue#279]
Hello all,

Currently I've the situation where I've downloaded the zip file and moved the content somewhere in the public directory and a reference to the minified javascript in the HTML file. This of course works and is easy to setup, though not very maintenance friendly.

I've been wanting to setup the same but with the tinymce NPM package, though I've no idea how to set that up. The documentation of the regular tinymce package suggests to import tinymce and initialize it. However, the tinymce-vue package should do the initialization since we're passing the editorconfig object to the component.

How should I make these two work together? To be clear, I can't use cloud solution. Thanks in advance for any help!

**Comment by jscasca** [comment]
The way the tinymce-vue package works is by creating the component surrounding the editor. The actual editor is loaded once the component is rendered. For the editor to load we need the TinyMCE instance at that time. If the component can't find one it will default to a cloud CDN.

The easiest way probably would be to setup a script to copy the tinymce folder from node_modules into your public folder if I am understanding your intent correctly. You can just reference that TinyMCE from your `index.html` to make it available to the vue component.

@zwik hope this helps make it clear how it can work

**Comment by zwik** [comment]
Thank you for your answer @jscasca . But what you describe is what I tried to describe in the first paragraph and is indeed the easiest way but unfortunately also the worst way to maintain.

Yesterday I finally figured out how to solve it. Here's some code:

```js
import 'tinymce/tinymce'
import Editor from '@tinymce/tinymce-vue'

import 'tinymce/themes/silver/theme'
import 'tinymce/icons/default'

// import plugins

import contentUiCss from '!!raw-loader!tinymce/skins/ui/oxide/content.css'
import contentCss from '!!raw-loader!tinymce/skinds/content/default/content.css'
```

In your Vue component where you pass the editorConfig you can then have an object that looks like this:

```js
editorConfig: {
  content_style: contentUiCss.toString() + contentCss.toString(),
  content_css: false,
  skin: false,
  // the rest of the config
}
```

So additionally you probably want to install `raw-loader` as a devDependency as well. Now TinyMCE can be version managed using NPM which is a lot easier to maintain then putting some files somewhere.

it would be great if this style could be documented somewhere in the TinyMCE docs as well!

**Comment by jscasca** [comment]
@zwik good to know that's working for you. This is actually documented in the [module-loader docs](https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/webpack/webpack_es6_npm/#procedure)

I do find it easier to just tie a copy script into the build process to update from node_modules so that you can always have the latest from npm while having the editor available in your public folder.

**Comment by afan0228** [comment]
toolbar fontsizeselect is lost
