### ISSUE TITLE
Multiple instances and custom plugin

### ISSUE THREAD

**Issue by byWalkoff** [tinymce/tinymce-vue#280]
Hi there! Using custom plugin with multiple instances on the page behave not as expected. Plugin appears only on last one editor instance. Here's an example: https://codesandbox.io/s/gallant-tree-02q5l?file=/src/components/HelloWorld.vue

**Comment by jscasca** [comment]
@byWalkoff the codesandbox is not working for me. The `plugin.js` is empty. Can you double check the example?

**Comment by byWalkoff** [comment]
@jscasca i've fixed codesandbox, it didn't saved somehow.. Please have a look again.

**Comment by byWalkoff** [comment]
Btw, hacky workaround for a moment is to provide a different name of plugin for each instance of editor.

**Comment by jscasca** [comment]
@byWalkoff unfortunately, I am no expert on how the plugin loading works on the editor. To the best of my understanding it is better to load the plugins before the setup phase. With that in mind my suggestions would be:
1. Don't use the plugin manager and just create the buttons e.g: https://codesandbox.io/s/naughty-borg-q4mm4?file=/src/components/HelloWorld.vue
2. Load as an external plugin: https://codesandbox.io/s/jolly-franklin-sszn0?file=/src/components/HelloWorld.vue

**Comment by byWalkoff** [comment]
@jscasca thanks for your suggestions, both are more clear to implement. I guess you can close this issue.
