### ISSUE TITLE
Add a method to update init Object value

### ISSUE THREAD

**Issue by trcat** [tinymce/tinymce-vue#283]
Our team want to update init Object when Editor has created, but there is no such method to realize this feature

an add a method or other way to realize this feature,

**Comment by jscasca** [comment]
@trcat currently, the TinyMCE editor does not provide a way to change the current configuration object. Current workarounds involve re-loading the component.

What is the particular use case for changing the configuration after the editor has initialized?

**Comment by jscasca** [comment]
A `rerender(init)` function has been implemented in v4.0.3. You can find a sample in the package vite demo
