### ISSUE TITLE
TinyMCE changes html code adding style tag with background-image

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce-vue#284]
Hi, developers! Something happened with my TinyMCE. It starts change html code adding something. I don't know what to do. Ask for help!

Before:

<img width="1178" alt="Снимок экрана 2021-11-23 в 21 53 12" src="https://user-images.githubusercontent.com/77324079/143094399-d995cfd0-371b-4c3b-be0e-29d580a24e09.png">

After:

<img width="1164" alt="Снимок экрана 2021-11-23 в 21 52 58" src="https://user-images.githubusercontent.com/77324079/143094406-0a9bd9aa-eaea-46ab-8b17-c664412a1086.png">

**Comment by jscasca** [comment]
Can you elaborate on how this is happening? @Macartini

**Comment by Macartini** [comment]
> 

Hi! This happened after saving the page where TinyMCE is integrated. After saving I have this on page:

![изображение_viber_2021-11-05_11-05-49-430](https://user-images.githubusercontent.com/77324079/145991169-b7ae45ce-47e0-4141-b64e-ededa4802036.jpg)

Divvvvvvvvvvvvv) And the code in TinyMCE looks like I have described earlier.

**Comment by jscasca** [comment]
@Macartini Can you post your entire configuration? Are you using the editor from the cloud? If not, what version of the editor are you using? When was the last time your code worked properly?

If possible, can you create a small replication case using a codesandbox? (Example of the content you want to display before and after inserting it in the editor)
