### ISSUE TITLE
出现滚动条后 鼠标选不中文字

### ISSUE THREAD

**Issue by taolei1990** [tinymce/tinymce-vue#289]
![image](https://user-images.githubusercontent.com/23173640/150044619-baed9f2a-b820-44d0-8785-87a82d0694ea.png)
本来应该选一行的 结果会把后面几行都选中了

**Comment by taolei1990** [comment]
没有滚动条的时候是正常的

**Comment by jscasca** [comment]
I cannot replicate the described behaviour.
![vue_289](https://user-images.githubusercontent.com/6062777/151497353-995eaf2b-b229-49f5-be87-0faed5be7e2d.png)

Am I understanding this correctly?
