### ISSUE TITLE
api-key is blank in production env

### ISSUE THREAD

**Issue by mikinovation** [tinymce/tinymce-vue#295]
**What is the current behavior?**

I created editor component and pass API Key as props in vue3.
When I tried to use variable as env, no-api-key request would be sent in production env.
However it works in development env

![Screenshot 2022-02-21 172331](https://user-images.githubusercontent.com/33025073/154925955-83863683-09bc-4f45-b0cd-6d10a1f36bd0.png)

```
<template>
  <Editor
    :api-key="TINYMCE_API_KEY"
    ....
  />
</template>

<script setup lang="ts">
import Editor from '@tinymce/tinymce-vue'
import { defineProps, inject } from 'vue'
import { useVModel } from 'vue-composable'

interface Props {
  value: string
}

const props = defineProps<Props>()

const TINYMCE_API_KEY = process.env.VUE_APP_TINYMCE_API_KEY || ''

const vmValue = useVModel(props, 'value')
</script> 
```

When I tried to pass api key directry to editor component, it works properly.

```
<template>
  <Editor
    api-key="abcdefghijklmn"
    ....
  />
</template>
```

I already confirmed api key is passed in production env.
What's problem in production env?

**version**

- vue@3.0.0
- @tinymce/tinymce-vue@4

**Comment by jscasca** [comment]
@mikinovation is this a github repo that we can look into? My best guess is that the env variable is not coming through to the component. If you have a sample repo we can investigate deeper into it
