### ISSUE TITLE
Trying to load TinyMCE as a standalone (non-cloud) free installation but still get the This domain is not registered message

### ISSUE THREAD

**Issue by milp** [tinymce/tinymce-vue#30]
I have wrapped the call to the tinyMCE inside another VUE component (warapper) called Wysiwyg as below:

```
   import editor from '@tinymce/tinymce-vue';

    export default {

        name: 'Wysiwyg',

        components: { editor },

    }
```

This works but show the dreaded message:
`This domain is not registered with TinyMCE Cloud. Start a free trial to discover our premium cloud services and pro support.`

I don't want to use cloud but want to run the tinyMCE as a standalone editor for my project.

What should I do?

**Comment by fyrkant** [comment]
You need to make tinymce globally available before you load the editor, so either add a script tag in you page to tinymce or bundle it up.

**Comment by milp** [comment]
The above code that I have shown, is inside the Wysisyg component (vue). Inside that component, in the template tag (not shown because it was not being formatted correctly) I call <editor></editor>

As you can see, the editor itself is imported from the tinymce folder which in inside node_modules folder

**Comment by a2exfr** [comment]
Have same issue. 
Using:

> import Vue from 'vue';
> import Editor from '@tinymce/tinymce-vue';
> 
> Vue.component('editor', Editor);

then

` <editor v-model="text"></editor>`


Also [here ](https://tinymce.github.io/tinymce-vue/?selectedKind=TestComponent&selectedStory=inline%20in%20init&full=0&addons=1&stories=1&panelRight=0) this message everywhere

**Comment by fyrkant** [comment]
The `tinymce-vue` package is only a wrapper around tinymce, so when I'm talking about that you need to make tinymce globally available I'm not talking about the package but about tinymce: https://github.com/tinymce/tinymce-vue#loading-tinymce-by-yourself

**Comment by milp** [comment]
@frykant, either I am too dumb or I am not understanding. Here's what I am trying to do (hopefully it formats the code properly in the code block):

`import editor from '@tinymce/tinymce-vue';
    import tinymce from 'tinymce/tinymce';
    import 'tinymce/themes/modern/theme';

export default {
        name: 'Wysiwyg',
        components: { editor },
    }
`

It compiles correctly but is now giving me 404 errors about the errors about skin.min.css & content.min.css not found.
How do I get rid of the 404 errors? Or How do I make it work? Am I on the right path?

**Comment by fyrkant** [comment]
You're on the right path, you just need to make the skin available too, see this documentation page: https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/#gettingtheskin

**Comment by fyrkant** [comment]
Closing this as it's not a problem with the wrapper component.

**Comment by prashant1k99** [comment]
> For anyone struggling with this the documentation isn't helpful at all. This is how I resolved the issue.
> First Import tinymce and copy the skins folder.
> 
> ```
> npm install tinymce --save
> cp -r node_modules/tinymce/skins skins
> ```
> To be safe I manually moved the skins folder to my public folder and then added this to my main.js
> 
> ```
> import "tinymce/tinymce"
> import "tinymce/themes/silver" 
> import "../public/skins/ui/oxide/skin.min.css"
> import "../public/skins/ui/oxide/content.min.css"
> import "../public/skins/content/default/content.min.css"
> ```
> Then you can use the editor in any component you want.

Now wouldn't it will work if we only import all the 
 ```
> import "tinymce/tinymce"
> import "tinymce/themes/silver" 
> import "../public/skins/ui/oxide/skin.min.css"
> import "../public/skins/ui/oxide/content.min.css"
> import "../public/skins/content/default/content.min.css"
> ```
In the component where we declare the TinyMCE vue wrapper....

**Comment by Pyronerd62** [comment]
I don't know. I use tiny mce in multiple areas so it made sense to just make it globally available. Try it and post back for others if it worked

**Comment by Pyronerd62** [comment]
Hey @prashant1k99 you can use it in a component. I started a new project and we only use the editor in one location and simply put everything in the component instead of the main.js. Still works just fine

**Comment by prashant1k99** [comment]
Thanks @Pyronerd62 . Can you share the entire code for setup in one gist, it will help me... Thanks anyway....

**Comment by Pyronerd62** [comment]
Here ya go
https://gist.github.com/Pyronerd62/b361822cce661152a80cdeb80a2ddb7f

**Comment by Mintonne** [comment]
Just a heads up, you don't have to copy the skins and themes to the `public` folder

import editor from '@tinymce/tinymce-vue'

import 'tinymce/tinymce'

// Theme
import 'tinymce/themes/silver/theme'

// Skins
import 'tinymce/skins/ui/oxide/skin.min.css'
import 'tinymce/skins/ui/oxide/content.min.css'
import 'tinymce/skins/content/default/content.min.css'

// Plugins
import 'tinymce/plugins/fullscreen'
import 'tinymce/plugins/paste'
import 'tinymce/plugins/autoresize'

**Comment by Pyronerd62** [comment]
hmmm.... Interesting. According the the TinyMCE documentation they said you did. However, I like it! Thanks for the update!!!!!

**Comment by bci24** [comment]
@Mintonne 

> Just a heads up. You don't have to copy the skins and themes to the public folder

For me it`s not working if I am not copying the files. Maybe I am doing something wrong!

I want to bundle all the content in app.css and app.js

In my app.js:

```
import Vue from 'vue';
import Editor from '@tinymce/tinymce-vue';
import 'tinymce/tinymce.min';
import 'tinymce/themes/silver/theme.min'

Vue.component('tinymce-editor', Editor);
```

and in app.scss:

```
@import '~tinymce/skins/ui/oxide/skin.min.css';
@import '~tinymce/skins/ui/oxide/content.min.css';
@import '~tinymce/skins/content/default/content.min.css';
```

In the browser console i get 404 for the imported css files. Why it keeps looking for the missing css files ???

If I copy them in public:

```
cp -r node_modules/tinymce/skins public/myApp/js/skins
```

it works.

**Comment by vahidahmad** [comment]
I wonder why there is not even a single example of how to use  standalone tinymce with package manager! All examples use tiny cloud cdn.

**Comment by cospring** [comment]
> Just a heads up. You don't have to copy the skins and themes to the `public` folder
> 
> ```js
> import editor from '@tinymce/tinymce-vue'
> 
> import 'tinymce/tinymce'
> 
> // Theme
> import 'tinymce/themes/silver/theme'
> 
> // Skins
> import 'tinymce/skins/ui/oxide/skin.min.css'
> import 'tinymce/skins/ui/oxide/content.min.css'
> import 'tinymce/skins/content/default/content.min.css'
> 
> // Plugins
> import 'tinymce/plugins/fullscreen'
> import 'tinymce/plugins/paste'
> import 'tinymce/plugins/autoresize'
> ```

For anyone who get the "Uncaught SyntaxError: Unexpected token '<'" error message to load icons.js while using tinymce v5.5.0 + , just add this code to import icons:
```
// icons
import 'tinymce/icons/default'
```

**Comment by hmingv** [comment]
如果您是 Tinymce V5+，可以阅读
https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/webpack/webpack_es6_npm/

如果您是 Tinymce V6+，可以阅读
https://www.tiny.cloud/docs/tinymce/6/webpack-es6-npm/

**Comment by hmingv** [comment]
If you are using Tinymce V5+, you can read:
https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/webpack/webpack_es6_npm/

If you are using Tinymce V6+, you can read:
https://www.tiny.cloud/docs/tinymce/6/webpack-es6-npm/

**Comment by AlexeyPlodenko** [comment]
For the v7 (latest) choose your bundler on the page https://www.tiny.cloud/docs/tinymce/latest/introduction-to-bundling-tinymce/ and follow from there.
