### ISSUE TITLE
Model :value not binding when using <scrip setup>

### ISSUE THREAD

**Issue by elouanmailly** [tinymce/tinymce-vue#303]
**What is the current behavior?**

After initializing a component with the `<script setup>` syntax, it seems that the value binding does not work.

[https://codesandbox.io/s/tinymce-editor-script-setup-x4dvkp](https://codesandbox.io/s/tinymce-editor-script-setup-x4dvkp)

**What is the expected behavior?**

The initial value in the editor should be _"initial-content"_ and when the button is clicked, the value should change to _"Change value with button"_

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**

**Vue**: 3.2.31
**Vite**: 2.8.6
**@tinymce/tinymce-vue**: 4.0.6
**tinymce**: 6.0.0

**Comment by andysay** [comment]
up

**Comment by maopixin** [comment]
I have same question，I can't imagine such a simple problem happening

**Comment by websitevirtuoso** [comment]
This is because in vue3 we have model-value. not "value"

**Comment by 490626721** [comment]
up,this question not repair！！！

**Comment by juliandreas** [comment]
This is my setup, hope it helps:

```javascript
const tinyConfig = {
  // Your setup here
  skin: false,
  plugins: "lists link image table code help wordcount",
  content_css: false,
  branding: false,
  promotion: false,

  // The important part
  setup(editor: TinyMCEEditor) {
    editor.on("input", () => handleInput(editor.getContent()));
  },
};

const handleInput = (editor: string) => {
  // Do whatever you want here
  console.log(editor);
};
```

```html
<Editor :init="tinyConfig" />
```
