### ISSUE TITLE
Removing empty line doesn't update v-model

### ISSUE THREAD

**Issue by rMonell** [tinymce/tinymce-vue#307]
### **What is the current behavior ?**

When I remove an empty line on the editor component, the v-mode doesn't update the value until I insert a new character or a new line.

[Here is a codesanbox where you can test this behavior](https://codesandbox.io/s/reverent-shirley-s9x4z9?file=/src/App.vue)

![Animation](https://user-images.githubusercontent.com/47424980/161732225-204b8c6f-6386-422d-8418-375c12425803.gif)

### **What is the expected behavior ?**

When removing an empty line, the v-model should update the value.

---

**Vue**: 2.6.14
**@tinymce/tinymce-vue**: 3.2.8
**tinymce**: 5.0.0

**Comment by jscasca** [comment]
@rMonell this originates from the TinyMCE editor not triggering an event when deleting an empty line. A workaround is to use a diferent `modelEvent` in the wrapper to catch this. For example: `<editor modelEvents="keyup" v-model="content" :init="config" />`. Read more about model events in the docs: https://www.tiny.cloud/docs/integrations/vue/#model-events

**Comment by rMonell** [comment]
Thank you ! This is exactly what I was looking for 👍

I had found a similar solution made of `keyup.native` But I completely missed the `modelEvent` prop, it's cleaner that way.
