### ISSUE TITLE
Same Paste is now working in TinyMCE

### ISSUE THREAD

**Issue by akashhdeep** [tinymce/tinymce-vue#309]
**Whenever I'm trying to paste the same text in TinyMCE it's showing a validation error This field is required **

![image](https://user-images.githubusercontent.com/91879324/165449573-3ea36a0b-8087-45e7-9f95-21b5ae12844d.png)

**Comment by akashhdeep** [comment]
@spocke @Afraithe @techtangents @TheSpyder Please Help Me Through This Issue

**Comment by andysay** [comment]
try use                     @selectionChange="changeContent"

{

      this.text = item.currentTarget.childNodes[1].lastChild.innerHTML;

}

**Comment by jscasca** [comment]
@akashhdeep  As @andysay suggested you might need to manually trigger an event based on how you are evaluating those conditions. I'm guessing it's validating a text area instead of a reactive variable?

Happy to reopen this issue if you have a replication case
