### ISSUE TITLE
Plugin assets not found

### ISSUE THREAD

**Issue by vielhuber** [tinymce/tinymce-vue#31]
Hello!

I use tinymce without cloud support the recommended way:

```js
/* core */
import tinymce from 'tinymce/tinymce';
import 'tinymce/themes/modern/theme';
/* some plugins */
import 'tinymce/plugins/advlist';
import 'tinymce/plugins/emoticons';
/* tinymce-vue */
import Editor from '@tinymce/tinymce-vue';
```
I use the following configuration:

```js
{
skin_url: '/_assets/tinymce/skins/lightgray',
language_url: '/_assets/tinymce/langs/de.js',
language: 'de',
plugins: ['emoticons'],
menubar: 'file edit view',
toolbar: 'emoticons'
}
```

I also copied the skins folder as described in the official documentation.

The problem now is that all assets of plugins are NOT found, because I have to place the skin and the language file inside a subfolder.

In order to get the assets of the plugins (e.g. plugins/emoticons/img/smiley-tongue-out.gif) to work, I have to copy the whole plugins folder to _assets/tinymce/plugins, correct?

Then how do I specifiy a custom plugin url path like I did for language_url and skin_url?

**Comment by fyrkant** [comment]
There is an external_plugins setting that might work for you: https://www.tiny.cloud/docs/configure/integration-and-setup/#external_plugins

**Comment by vielhuber** [comment]
Awesome, that did it!

```
import tinymce from 'tinymce/tinymce';
import 'tinymce/themes/modern/theme';
import Editor from '@tinymce/tinymce-vue';
```

```
...
                external_plugins: {
                    'emoticons': '/_assets/tinymce/plugins/emoticons/plugin.min.js',
                    /* ... */
                }
...
```

**Comment by fyrkant** [comment]
Great!

**Comment by prashant1k99** [comment]
> Awesome, that did it!
> 
> ```
> import tinymce from 'tinymce/tinymce';
> import 'tinymce/themes/modern/theme';
> import Editor from '@tinymce/tinymce-vue';
> ```
> ```
> /* ... */
> external_plugins: {
> 'emoticons': '/_assets/tinymce/plugins/emoticons/plugin.min.js',
> /* ... */
> }
> /* ... */
> ```

Can you just send the entire code for configuring the tinymce?...

**Comment by vielhuber** [comment]
https://gist.github.com/vielhuber/c0e63f643903e86b7ee356eead20c905
