### ISSUE TITLE
How does vue3 use the refs method of vue2

### ISSUE THREAD

**Issue by sqdqiushao** [tinymce/tinymce-vue#324]
tinymce-vue5.0.0:  vue2 update vue3,  The object obtained by refs has no method of vue2， like $refs.editor.editor.selection

**Comment by jscasca** [comment]
@sqdqiushao  If you want to access the editor you can either create your own `ref` or you can just store the editor variable yourself. Finally you can access it via a window invocation. Here is a sample: https://codesandbox.io/s/tinymcevue-forked-zbmii?file=/src/App.vue
