### ISSUE TITLE
自定义配置toolbar的styleselect fontsizeselect fontselect，toolbar栏不显示

### ISSUE THREAD

**Issue by chengup-git** [tinymce/tinymce-vue#326]
![1](https://user-images.githubusercontent.com/57739679/178643535-cc8dc547-2a3f-4d9a-8f91-bcbd581c4500.png)
![2](https://user-images.githubusercontent.com/57739679/178643549-525e1ad9-16ed-4454-b54c-074c184cb9da.png)

**Comment by 13191868165** [comment]
https://www.tiny.cloud/docs/tinymce/6/user-formatting-options/
fontfamily fontsize forecolor

**Comment by IKangXu** [comment]
`styleselect formatselect fontselect fontsizeselect`    switch to   `fontfamily fontsize blocks`

**Comment by jscasca** [comment]
Closing this issue as it has been answered
