### ISSUE TITLE
v-model invalid

### ISSUE THREAD

**Issue by maopixin** [tinymce/tinymce-vue#335]
**What is the current behavior?**

v-model cannot bind in both directions

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**

**What is the expected behavior?**

v-model can use
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
tinymce-vue: v5.0.0
browser: all browser

**Comment by gspgsp** [comment]
same issue, how to solve?
