### ISSUE TITLE
how to import a custom plugin for vue3

### ISSUE THREAD

**Issue by RobertHan215** [tinymce/tinymce-vue#336]
i'm using vue3 in the project, and i create a very simple custom plugin by **Yeoman** , but i could't find a way to import my custom plugin in the vue3 project. Where to find the start guide for this part.

**Comment by jscasca** [comment]
@RobertHan215 There are many ways to include your custom plugin in a Vue project. You can:
- Host/serve your custom plugin code and include it as an external plugin  [for example](https://codesandbox.io/s/vue3-tinymce-base-forked-ir75ou?file=/src/components/HelloWorld.vue)
- Copy your custom plugin into the plugins folders of your self-hosted TinyMCE deployment
- You can bundle TinyMCE with your custom plugin (not recommended but you can read more in [how to bundle TinyMCE](https://www.tiny.cloud/docs/tinymce/6/introduction-to-bundling-tinymce/) )

Additionally, you can always import your custom logic and load it in the component's configuration setup
