### ISSUE TITLE
The `outputFormat` prop should allow `"raw"`

### ISSUE THREAD

**Issue by fisker** [tinymce/tinymce-vue#338]
**What is the current behavior?**

```html
<tinymce-editor output-format="raw"></tinymce-editor>
```

Cause Vue warning

```text
[Vue warn]: Invalid prop: custom validator check failed for prop "outputFormat". 
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**

I don't think this is necessary, but I can setup one if required.

**What is the expected behavior?**

According to [type definition in core](https://github.com/tinymce/tinymce/blob/a48c85b693f8ce3690a853d5fbd6b6ebad7ab23a/modules/tinymce/src/core/main/ts/content/ContentTypes.ts#L4) the `getContent` format should allow `"raw"`, but in Vue component, `"raw"` is not allowed in [the `outputFormat` prop](https://github.com/tinymce/tinymce-vue/blob/ca3d166b8825e3c32b880166b42a3bf6014d1ca1/src/main/ts/components/EditorPropTypes.ts#L47).

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**

Version: `@tinymce/tinymce-vue@5.0.0`.

> Did this work in previous versions of TinyMCE or tinymce-vue?

IDK.

---

I'm using `"raw"` because the default `"html"` format cause `\n` added between `<section style="display: inline-block"/>` which is also a bug, but I'm not going to deal with it.

My workaround

```js
import TinymceEditor from '@tinymce/tinymce-vue';

const TinymceEditorSupportsRawFormat = {
  ...TinymceEditor,
  props: {
    ...TinymceEditor.props,
    outputFormat: {
      ...TinymceEditor.props.outputFormat,
      validator: (format) =>
        format === 'html' || format === 'text' || format === 'raw',
    },
  },
};
```

**Comment by jscasca** [comment]
@fisker the output format `raw` was intentionally excluded as it contains editor specific attributes and tags designed for internal use only.

If you really REALLY want this content you can access it via the editor ref of the component otherwise we don't recommend using it.

**Comment by fisker** [comment]
In that case, do you think this should be fixed?

> I'm using "raw" because the default "html" format cause \n added between <section style="display: inline-block"/> which is also a bug

**Comment by jscasca** [comment]
@fisker  That is part of the editor behaviour, unfortunately, this repo only deals with the Vue component. You would need to open an issue at the [TinyMCE repo](https://github.com/tinymce/tinymce/issues) since I'm not completely sure what is the editor expected behaviour.

If you want to use the `raw` option, you can write a custom handler using the editor ref of the component or a fork of this project but know that it is not supported

**Comment by fisker** [comment]
Thanks anyway.

**Comment by afan0228** [comment]
哥们能提供一下完整示例吗？
