### ISSUE TITLE
When used in vue <keep-alive>，how to not destroy the editor in deactivated hook

### ISSUE THREAD

**Issue by JackieCheung** [tinymce/tinymce-vue#340]
**What is the current behavior?**
When used in vue `<keep-alive>`，the editor will be removed in deactivated hook：

```
onDeactivated(() => {
  if (!modelBind) {
    cache = vueEditor.getContent();
  }
  getTinymce()?.remove(vueEditor);
});
```

**What is the expected behavior?**

How to prevent to remove the editor automatically?

**Comment by jscasca** [comment]
The editor gets removed otherwise it might become unusable if Vue moves it around. What seems to be the issue?
