### ISSUE TITLE
Paste plugin does not work with tinymce-vue

### ISSUE THREAD

**Issue by CacheMoneyPlaya** [tinymce/tinymce-vue#352]
Currently running "vue": "^2.5.17" with "@tinymce/tinymce-vue": "^3.2.8", the 'paste' plugin does not seem to make pasting via `edit->paste` work. The config is picked up no problem with all other changes, just not with paste.

Configuration is passed in as below:
```
                tinyMceInit: {
                 plugins : [
                   'advlist autolink lists link preview anchor',
                   'searchreplace visualblocks code fullscreen',
                   'table help wordcount paste'
                 ],
                 toolbar:[
                   'undo redo | formatselect | bold italic | \
                   alignleft aligncenter alignright alignjustify | \
                   bullist numlist outdent indent | removeformat | help'
                 ]
                }
```

**Comment by CacheMoneyPlaya** [comment]
Just had a look on the main tinymce issues page and can see a few threads about the same thing (Which would rule out this Vue wrapper), anyone able to confirm?

**Comment by lorenzo-pomili** [comment]
yes, the problem seems to be in the core, so I'll close this issue since already exists one [issue](https://github.com/tinymce/tinymce/issues/8078) in the core.

Thanks anyway to reported that :)
