### ISSUE TITLE
Setting the initial height of TinyMCE does not work.

### ISSUE THREAD

**Issue by randolf-alegre** [tinymce/tinymce-vue#356]
**What is the current behavior?**
When setting the initial height of the TinyMCE editor in vuejs 2 it does not apply because of the **.tox-tinymce** which has a value of **_height: 500px !important;_**.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**
.tox-tinymce {
    border-radius: 0.675rem !important;
    height: 500px !important;
}

**What is the expected behavior?**
The expected behavior based on the docs is it should change and follow the value that is set in the init attribute.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**

Version 3 and up using tinyMCE-vue
Browser: Chrome

**Comment by fyzhu** [comment]
put height in init property
<img width="516" alt="image" src="https://user-images.githubusercontent.com/5175751/224599907-c060449e-ab60-454a-a14e-4d3489c0c6f0.png">

**Comment by lorenzo-pomili** [comment]
Using the height in init as @fyzhu suggested I got the correct behavior too, if that does not fix your problem could you please provide us an example via codepen or similar that has the problem?
