### ISSUE TITLE
Standard Mode issue in vuejs build

### ISSUE THREAD

**Issue by daynecoetzee** [tinymce/tinymce-vue#358]
After adding this repo to my vuejs project I received the issue:
 `Failed to initialize the editor as the document is not in standards mode. TinyMCE requires standards mode.`

I did some investigation and found that this is due to the `<!DOCTYPE html>` not being present as the first tag. After checking and confirming that the tag does exist in the index.html, I discovered that somehow, during compilation this tag is being dropped when compiling the application by comparing the source code in the browser. I cannot find any further information online for as to why this happening.

**Comment by lorenzo-pomili** [comment]
I'd need a check, can you try to remove only `tinymce-vue` from your project and see if you get `<!DOCTYPE html>`?

If yes, can you give us a workable example (for example a Git repo) and step by step instruction to reproduce it?
