### ISSUE TITLE
Cannot convert blob

### ISSUE THREAD

**Issue by Krasnov8953** [tinymce/tinymce-vue#36]
After I initialized component i receive the message. Cannot convert blob:http://localhost:8080/1025c3a4-b849-4a20-b0ae-5598e2383a64 to Blob. Resource might not exist or is inaccessible. How can I resolve this?

**Comment by fyrkant** [comment]
Can you share some more information about the app, maybe create a small demo app that reproduces the issue? It's really difficult to understand the problem from only an error message.

**Comment by Krasnov8953** [comment]
> Can you share some more information about the app, maybe create a small demo app that reproduces the issue? It's really difficult to understand the problem from only an error message.

Here is how i use editor in my app
`
<template>
    tinymice.width-100(id="d1", v-model="item.body")
</template>

<script>
import tinymice from 'vue-tinymce-editor'
export default {
    components {
        tinymice
    }
}
</script>
`
This is content for item.body
"<p>Компания Marshall анонсировала беспроводные наушники Minor II Bluetooth. Они получили 14,5-миллиметровые излучатели и необычную конструкцию вкладышей. Сквозь каждый из них проходит соединительный провод, образующий регулируемую петлю. Она обеспечивает более плотную фиксацию в ушной раковине.</p><p><img src=\"blob:http://localhost:8080/1025c3a4-b849-4a20-b0ae-5598e2383a64\" style=\"width: 300px;\" class=\"fr-fic fr-dib fr-fil\"></p><p>&nbsp;</p><p><span class=\"fr-video fr-fvc fr-dvi fr-draggable\" contenteditable=\"false\"><iframe class=\"ql-video fr-draggable\" allowfullscreen=\"true\" src=\"https://www.youtube.com/embed/NrsOEmAyPwY?showinfo=0\" frameborder=\"0\"></iframe></span></p><p><span class=\"fr-video fr-fvc fr-dvb fr-draggable\" contenteditable=\"false\" draggable=\"true\"><iframe src=\"//vk.com/video_ext.php?oid=-19948688&id=171464567&hash=1063ae81cb908a1c&hd=2\" width=\"853\" height=\"480\" frameborder=\"0\" allowfullscreen=\"\" class=\"fr-draggable\"></iframe></span><br></p><p><br></p><p><strong><span class=\"ql-cursor\">﻿</span>&nbsp;</strong></p><p>Наушники оснащены модулем Bluetooth 5.0 и поддерживают кодек Qualcomm aptX, обеспечивающий улучшение качества беспроводного звука. Девайс будет доступен в чёрном, белом и коричневом цветах по цене 129 евро.</p><p><strong>&nbsp;</strong></p><p><a href=\"https://lifehacker.ru/marshall-minor-ii/\" target=\"_blank\">lifehacker.ru</a></p>"

**Comment by Krasnov8953** [comment]
This is content for item.body

<p>Компания Marshall анонсировала беспроводные наушники Minor II Bluetooth. Они получили 14,5-миллиметровые излучатели и необычную конструкцию вкладышей. Сквозь каждый из них проходит соединительный провод, образующий регулируемую петлю. Она обеспечивает более плотную фиксацию в ушной раковине.</p><p><img src=\"blob:http://localhost:8080/1025c3a4-b849-4a20-b0ae-5598e2383a64\" style=\"width: 300px;\" class=\"fr-fic fr-dib fr-fil\"></p><p>&nbsp;</p><p><span class=\"fr-video fr-fvc fr-dvi fr-draggable\" contenteditable=\"false\"><iframe class=\"ql-video fr-draggable\" allowfullscreen=\"true\" src=\"https://www.youtube.com/embed/NrsOEmAyPwY?showinfo=0\" frameborder=\"0\"></iframe></span></p><p><span class=\"fr-video fr-fvc fr-dvb fr-draggable\" contenteditable=\"false\" draggable=\"true\"><iframe src=\"//vk.com/video_ext.php?oid=-19948688&id=171464567&hash=1063ae81cb908a1c&hd=2\" width=\"853\" height=\"480\" frameborder=\"0\" allowfullscreen=\"\" class=\"fr-draggable\"></iframe></span><br></p><p><br></p><p><strong><span class=\"ql-cursor\">﻿</span>&nbsp;</strong></p><p>Наушники оснащены модулем Bluetooth 5.0 и поддерживают кодек Qualcomm aptX, обеспечивающий улучшение качества беспроводного звука. Девайс будет доступен в чёрном, белом и коричневом цветах по цене 129 евро.</p><p><strong>&nbsp;</strong></p><p><a href=\"https://lifehacker.ru/marshall-minor-ii/\" target=\"_blank\">lifehacker.ru</a></p>"

**Comment by Krasnov8953** [comment]
but when I used third party editor everithing looks fine

**Comment by fyrkant** [comment]
So you are using `vue-tinymce-editor`? Then you are on the wrong repo, here is the repo for that package: https://github.com/dyonir/vue-tinymce-editor

**Comment by Krasnov8953** [comment]
Oh, sorry for my mistake )
