### ISSUE TITLE
Can I format the content(html) to draftjs? And how?

### ISSUE THREAD

**Issue by huyanyawei** [tinymce/tinymce-vue#361]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

 **Describe the solution you'd like**

 **Describe alternatives you've considered**

**Comment by lorenzo-pomili** [comment]
can you be more specific?

**Comment by huyanyawei** [comment]
null

**Comment by huyanyawei** [comment]
null
