### ISSUE TITLE
images_upload_handler firefox

### ISSUE THREAD

**Issue by GaydideyArtem** [tinymce/tinymce-vue#364]
Version: 5.10.7 
function images_upload_handler not called after paste image ctrl-v on firefox in the field on vue3 project.  on toolbar upload work well.
In chrome work two ways normal

**Comment by lorenzo-pomili** [comment]
I see that you reply to the same [issue](https://github.com/tinymce/tinymce/issues/8379) in the core, thanks for it :) .

I'll close this one since it is a duplicate
