### ISSUE TITLE
Importing "tinymce-vue" results in requests to CDN for additional code

### ISSUE THREAD

**Issue by mryellow** [tinymce/tinymce-vue#369]
**What is the current behavior? Describe the bug**

`import Editor from '@tinymce/tinymce-vue';`

Loads resources from `cdn.tiny.cloud`

Resulting in an unnecessary vendor-lock where your CDN becomes the bottleneck.

**What is the expected behavior?**

Importing the code should import the code.

**Comment by TheSpyder** [comment]
Our vue integration defaults to cloud deployment, but if you have TinyMCE already loaded in the page it should not request a new one from our servers. For more information on this, see the self-hosted vue documentation:

Switching to a self-hosted copy of TinyMCE can be done with the `tinymce-script-src` configuration:
https://www.tiny.cloud/docs/tinymce/6/vue-ref/#tinymce-script-src
