### ISSUE TITLE
toolbar is shown even when toolbar configuration is false

### ISSUE THREAD

**Issue by Naama-Le** [tinymce/tinymce-vue#376]
**What is the current behavior?**
I'm using tinymce-vue to edit text in inline mode.
I'm using a computed property to set the init configuration, where I change the toolbar value conditionally.
I can see in the inspector that the editor updates the toolbar value (to false => to hide the toolbar), but the toolbar is still there on screen.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**
my computed value:
    editorConfig(){
      const toolbar = this.editTextBox ? false : 
        'undo redo | bold italic underline strikethrough | alignleft aligncenter alignright';
      return {
        selector: 'span',
        toolbar: toolbar,
        menubar: false
      }
    },
**What is the expected behavior?**
the toolbar should be hidden on toolbar: false

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
chrome on mac.

<img width="453" alt="Screenshot 2023-04-12 at 13 21 21" src="https://user-images.githubusercontent.com/54737585/231429610-8075d7fe-adc7-4cb4-b20c-ac95ea54114d.png">

![Screenshot 2023-04-12 at 13 23 03](https://user-images.githubusercontent.com/54737585/231430020-7a857051-ad6d-42bc-ab65-492617adcf22.png)

**Comment by TinyITAdmin** [comment]
Ref: INT-3174
