### ISSUE TITLE
Fetch API cannot load blob:https://example.feishu.cn/290d43d4-89f2-4d0b-8d43-8f50102ede2b. URL scheme "blob" is not supported.

### ISSUE THREAD

**Issue by suiboyu** [tinymce/tinymce-vue#377]
**What is the current behavior?**

tinymce-vue shows an error when I upload an image that starts with blob:http。The error is as follows

Fetch API cannot load blob:https://example.feishu.cn/290d43d4-89f2-4d0b-8d43-8f50102ede2b. URL scheme "blob" is not supported.

**What is the expected behavior?**

I'd like to be able to support images that start with blob:http

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**

"@tinymce/tinymce-vue": "^4.0.5",
"tinymce": "^6.4.0",
macOS：13.3.1

**Comment by TinyITAdmin** [comment]
Ref: INT-3178
