### ISSUE TITLE
MathML not rendering correctly

### ISSUE THREAD

**Issue by alishanster** [tinymce/tinymce-vue#381]
**What is the current behavior?**

Using wiris mathtype external plugin for tinymce, when I create and insert math equation, it renders correctly. However when I save everything and try to edit, content in the editor which supposed to be a math eqution does not render as it should. 
P.S. everything worked fine with Vue2 and tinymce-vue^3

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**
1. Install tinymce-vue^5
2. Add wiris mathType editor as external plugin
3. Create equation and save
4. Edit equation after save (need to get the contents from db)

**What is the expected behavior?**
Render editable MathType equations correctly
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
@tinymce/tinymce-vue^5
vue 3

**Comment by TinyITAdmin** [comment]
Ref: INT-3186

**Comment by alishanster** [comment]
UPD: downgrading to tinymce-vue^4 helped
