### ISSUE TITLE
disabled props is true when component first mounted，the fontselect toolbar was empty 

### ISSUE THREAD

**Issue by trcat** [tinymce/tinymce-vue#386]
**What is the current behavior?**

disabled props is true when component first mounted，the fontselect toolbar was empty 

this is the code

```vue
<template>
  <Editor api-key="no-api-key" :init="initConfig" :disabled="true"></Editor>
</template>

<script>
import "tinymce/skins/ui/oxide/skin.min.css"
import Editor from "@tinymce/tinymce-vue"

export default {
  name: "editor-demo-iframe",
  data() {
    return {
      initConfig: {
        toolbar: [
          "fontselect | fontsizeselect | bold italic underline strikethrough | forecolor backcolor | alignleft aligncenter alignright alignjustify | outdent indent | numlist bullist | removeformat | subscript superscript | charmap | emoticons | fullscreen | preview | print | help",
        ],
      },
      disabled: false
    }
  },
  components: {
    Editor,
  },
}
</script>
```

![image](https://github.com/tinymce/tinymce-vue/assets/23648263/0bd066d4-581d-45c4-8dcc-d3ff26560b6b)

**What is the expected behavior?**

disabled props is true when component first mounted，the fontselect toolbar has value

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**

vue: 2.7.17
tinymce/tinymce-vue: 3.2.8
browser/OS: chrome(last version) / windows 11

**Comment by TinyITAdmin** [comment]
Ref: INT-3193
