### ISSUE TITLE
I hope Dialogs can customize the mount DOM location

### ISSUE THREAD

**Issue by 490626721** [tinymce/tinymce-vue#389]
**Is your feature request related to a problem? Please describe.**
At present, I have a Vue TinyMce completed in Popover, but Dialogs are mounted under the body, which will cause Popover to unexpectedly close when I click on functions such as uploading images

 **Describe the solution you'd like**
I hope to specify the DOM where Dialogs are mounted

 **Describe alternatives you've considered**
I don't have a good idea either. Modifying the popover in the current project would be a bit complicated

**Comment by TinyITAdmin** [comment]
Ref: INT-3220
