### ISSUE TITLE
How to change tinymce language dynamically?

### ISSUE THREAD

**Issue by snowdream** [tinymce/tinymce-vue#391]
**What is the current behavior?**
I can not change change tinymce language dynamically.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**

**What is the expected behavior?**
 change tinymce language dynamically

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**

**Comment by TinyITAdmin** [comment]
Ref: INT-3232

**Comment by snowdream** [comment]
Fix: change language with rerender.

```
<template>
  <editor
    ref="editorRef"
    v-model="tinycontent"
    tinymce-script-src="/tinymce/tinymce.min.js"
    :init="tinyinit"
  />
</template>

<script setup lang="ts">
import Editor from '@tinymce/tinymce-vue'
...
const editorRef = ref()
editorRef.value.rerender({ language: language.value })

```

##Reference
[Refreshable.vue](https://github.com/tinymce/tinymce-vue/blob/e87883d8d0ebfaedf2aab6ba658b5737c9ef7b81/src/demo/views/Refreshable.vue#L45)
