### ISSUE TITLE
v-model issue

### ISSUE THREAD

**Issue by bjpayne** [tinymce/tinymce-vue#4]
Hey everyone - Hopefully this is something simple. I can't seem to get v-model working. In the vuejs dev tools if I update the bound model, the 'value' property in the Editor component is updated, however nothing changes in the actual editor. Using Vuejs 2.4.4.

Editor tag:
```html
<editor id="message" name="message" class="wysiwyg-editor" :init="config" v-model="content"></editor>
```

Vue instance:
```js
new Vue({
    el: '#send-message',
    data: {
        config: tinyMceConfig, 
        content: ''
    },
    components: {
        'editor': Editor,
    }, 
});
```

If I manually edit the 'content' property on the vue instance, the value property in the Editor component updates, but not the content in the editor. That doesn't seem to be bound to anything.

Thanks,
Ben

**Comment by fyrkant** [comment]
Can you share some more code? Maybe set up a small test app in a repo that I can take a look at?

**Comment by bjpayne** [comment]
@fyrkant Thanks for the response. In trying to create a sample app, I was actually able to get it working. The issue was I was globally initiating tinyMCE. Removing that fixed the issue. All is good now.

**Comment by Ajay1432** [comment]
@bjpayne I've the same issue. I've multiple instance of tinymce on a same page.
When I trying to toggle(hide/show) The value is not shown in editor. The value is shown VUE console. If I update the model from VUE console, the 'value' property in the Editor component is updated, and in editor data is shown.

Do we have any solution fo it?
