### ISSUE TITLE
API key warning on self-hosted TinyMCE

### ISSUE THREAD

**Issue by cwinters8** [tinymce/tinymce-vue#403]
I am just getting started with TinyMCE and planning to self-host, not use the cloud offering. I'm getting a warning (detailed below) about an API key when the editor loads.

I have both `@tinymce/tinymce-vue` and `tinymce` installed, which seems to be the difference between self-hosted and cloud installation in the docs

[Self-hosted](https://www.tiny.cloud/docs/tinymce/6/vue-pm/#procedure):

<img width="512" alt="Self-hosted install procedure" src="https://github.com/tinymce/tinymce-vue/assets/40615752/91546537-74d0-409f-aaae-ff5920daece7">

[Cloud](https://www.tiny.cloud/docs/tinymce/6/vue-cloud/#procedure):

<img width="442" alt="Cloud install procedure" src="https://github.com/tinymce/tinymce-vue/assets/40615752/fd91c0e0-f153-4a6f-b370-dcc4fddd6f31">

When I searched this warning in the docs, it seems to be related to using the cloud offering: [Cloud troubleshooting](https://www.tiny.cloud/docs/tinymce/latest/cloud-troubleshooting/#A-valid-API-key-is-required-starting-2024-to-continue-using-TinyMCE.-Please-alert-your-admin-to-sign-up-to-get-your-free-API-key.)

Does this mean TinyMCE can't be used without an API key from the cloud starting this year? Or is there some piece of configuration I'm missing to indicate this is self-hosted?

**What is the current behavior?**

When I use this package without an API key, I see this warning about needing a valid API key:

![API key warning](https://github.com/tinymce/tinymce-vue/assets/40615752/85733e0c-71ed-4de0-90da-f07f13a3b84c)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**

Install `@tinymce/tinymce-vue` and `tinymce`

```sh
npm install --save tinymce "@tinymce/tinymce-vue@^5"
```

Create an `Editor` without using an API key

```vue
<Editor :init="{ height: '100vh' }"><h1>Hello, Webster!</h1></Editor>
```

[Demo on Replit](https://replit.com/@cwinters8/TinyMCE-Vue#src/components/Editor.vue)

**What is the expected behavior?**

No warning should be displayed for self-hosted TinyMCE

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**

MacOS with FireFox and Edge for sure, but I don't have an easy way to test others. I suspect this is unrelated to specific browsers or operating systems.

```json
"dependencies": {
  "@tinymce/tinymce-vue": "^5.1.1",
  "tinymce": "^6.8.2",
  "vue": "^3.2.37"
},
```

**Comment by cwinters8** [comment]
FWIW my first step with TinyMCE was not using Vue, and I didn't see the warning there. Here's an example with that configuration: [Replit demo](https://replit.com/@cwinters8/TinyMCE-Vanilla#index.html). Note that I just copied `tinymce.min.js` straight from my repo for that example, so it hasn't been updated since I added it there on 2023-12-31.

**Comment by cwinters8** [comment]
I think I figured it out. This step about bundling in the [self-hosted Vue doc](https://www.tiny.cloud/docs/tinymce/6/vue-pm/#procedure) was sort of confusing

<img width="763" alt="bundling instructions" src="https://github.com/tinymce/tinymce-vue/assets/40615752/bf17def3-9b2c-423f-9dd1-6a27579764f2">

I updated the setup script to import tinymce itself and the associated plugins, themes, etc based on the [Vite bundling doc](https://www.tiny.cloud/docs/tinymce/6/vite-es6-npm/)

```vue
<script setup>
import 'tinymce'
import Editor from "@tinymce/tinymce-vue"

/* Required TinyMCE components */
import 'tinymce/icons/default/icons.min.js';
import 'tinymce/themes/silver/theme.min.js';
import 'tinymce/models/dom/model.min.js';

/* Import a skin (can be a custom skin instead of the default) */
import 'tinymce/skins/ui/oxide/skin.js';

/* Import plugins */
import 'tinymce/plugins/advlist';
import 'tinymce/plugins/code';
import 'tinymce/plugins/emoticons';
import 'tinymce/plugins/emoticons/js/emojis';
import 'tinymce/plugins/link';
import 'tinymce/plugins/lists';
import 'tinymce/plugins/table';

/* content UI CSS is required */
import 'tinymce/skins/ui/oxide/content.js';

/* The default content CSS can be changed or replaced with appropriate CSS for the editor content. */
import 'tinymce/skins/content/default/content.js';
</script>
```

And now the warning is gone

<img width="623" alt="editor without API key warning" src="https://github.com/tinymce/tinymce-vue/assets/40615752/0c00bedb-fed4-4a52-abed-ea967dc49485">

So I think I'm set for now, but I wonder if the bundling section of the self-hosted Vue install documentation could be updated to make it clear that you have to add some additional imports beyond what's currently in the bundling example currently, which amounts to

```vue
import { Editor } from '@tinymce/tinymce-vue';
```

[Updated demo in Replit](https://replit.com/@cwinters8/TinyMCE-Vue#src/components/Editor.vue)

**Comment by mryellow** [comment]
Be aware that they have attempted to prevent this in the past by building in errors.

Seems it does work again for the moment.

**Comment by mryellow** [comment]
Bump.

**Comment by danoaky-tiny** [comment]
Just to clarify: when using TinyMCE v7, you need either an API key for cloud-hosting, or a license key for self hosting (set `'gpl'` or provide a valid TinyMCE license key).

Unfortunately the Vue TinyMCE docs haven't yet been updated to reflect these changes but it's been logged internally to do soon.

If you need more info on anything specific, let us know.

It might also be beneficial to read the React, Angular or Svelte TinyMCE docs for self-hosting guides, such as https://www.tiny.cloud/docs/tinymce/latest/react-zip-host/

**Comment by mryellow** [comment]
> Unfortunately the Vue TinyMCE docs haven't yet been updated to reflect these changes but it's been logged internally to do soon.

...

>> What is the expected behavior?

> No warning should be displayed for self-hosted TinyMCE

**Comment by danoaky-tiny** [comment]
I understand, apologies for the inconvenience. But setting the `licenseKey` to `'gpl'` is intended to be a conscious decision made by the developer. See: https://www.tiny.cloud/docs/tinymce/latest/license-key. So for this reason there's no default for this option.

**Comment by mryellow** [comment]
It's not so much an inconvenience as a decision you've made. For obvious reasons.

**Comment by Eunknight** [comment]
solution https://github.com/tinymce/tinymce-vue/issues/464
