### ISSUE TITLE
Tinymce custom dialog with Vue component

### ISSUE THREAD

**Issue by obiefy** [tinymce/tinymce-vue#41]
this is the doc for [Create Custom Dialogs](https://www.tiny.cloud/docs/advanced/creating-custom-dialogs/).
I am using custom dialog on my editor, Can I want to use Vue component as the body of the dialog,
like this:
`editor.windowManager.open({
  title: "Dialog title",
  url: "<vue-component><vue-component>",
  // or
  body: "<vue-component><vue-component>"
});`

**Comment by fyrkant** [comment]
No that won't work, this package is a vue wrapper around TinyMCE so it does not change how the dialogs work in tinymce.

**Comment by obiefy** [comment]
I call the dialog body from another page which includes the Vue component using `url` property,
the Vue component will do some logic and I want to insert the result inside the editor content.
the question is how can I pass the result to the editor.
@fyrkant any Ideas ?!

**Comment by hightechguy** [comment]
@obiefy Did you managed to use Vues component as s Custom Dialog? Can you share?
Thanks!
