### ISSUE TITLE
TinyMCE v7 support

### ISSUE THREAD

**Issue by 719media** [tinymce/tinymce-vue#412]
Are you going to release a new version to npm?
Currently the latest version is 5.1.1, which means everyone using this package is stuck on tinymce v6 as package.json has that version constraint.

Thanks

**Comment by 719media** [comment]
This is also discussed at https://github.com/tinymce/tinymce-vue/issues/407

**Comment by jonjakoblich** [comment]
Package.json shows v7 in this repo.

**Comment by 719media** [comment]
The latest npm published version is 5.1.1, which is stuck on v6
https://www.npmjs.com/package/@tinymce/tinymce-vue

**Comment by meirroth** [comment]
Looks like @tinymce/tinymce-vue v6 published with TinyMCE v7 support 🎉
