### ISSUE TITLE
tinymce opens with empty head and body tags

### ISSUE THREAD

**Issue by NateWr** [tinymce/tinymce-vue#48]
I'm loading the tinymce vue component in a modal. The first time the modal is opened tinymce works fine. If the modal is then closed (removed from the DOM) and re-opened (added to the DOM), tinymce appears to load, but I can't click in the `iframe`. Upon inspection, the `iframe`'s `<head>` and `<body>` tags are empty.

I found similar issues (https://github.com/tinymce/tinymce-vue/issues/10, https://github.com/tinymce/tinymce-vue/issues/32) which suggest that there are problems when the `iframe` is removed from the DOM.

The parent component's `created`, `mounted` and `destroyed` lifecycle hooks are being fired correctly when the modal is opened/closed. And the tinymce component's `@onInit` event is firing each time the modal is loaded.

I tried using the suggested code in #10 in the `mounted` and `destroyed` lifecycle hooks to no avail:

```
mounted () {
	tinymce.EditorManager.execCommand('mceAddEditor', false, this.controlId);
},
destroyed () {
	tinymce.EditorManager.execCommand('mceRemoveEditor', false, this.controlId);
},
```

Is this a bug or expected behaviour? If it's the latter, is there a recommended approach for tearing down the tinymce control when the vue component is removed from the DOM?

**Comment by fyrkant** [comment]
Can you share some code from your implementation that I can test and see if I can get something working?

**Comment by NateWr** [comment]
Apologies for the delay in responding. I don't have a simple, reproducible test case and we have moved on from this implementation. Instead, we're using the `inline` mode which doesn't produce the `iframe` and loads more quickly for us because we don't have to load external stylesheets. Thanks for the follow-up though.

**Comment by RakibSiddiquee** [comment]
The following code works for me...

<editor v-if="active" v-model="description" :init="tinymce_init"></editor>

data(){
  return {
   active: false,
  }
},

mounted(){
  this.active= true;
},

destroyed(){
  this.active= false;
}

**Comment by scoutrul** [comment]
I have same problem and solved it by calling nextTick

```
  <editor v-if="active" />

  data: () => ({
    active: false,
  }),
  mounted() {
    this.$nextTick(() => {
      this.active = true;
    });
  },
```
