### ISSUE TITLE
where langs/zh_CN.js should place?

### ISSUE THREAD

**Issue by banzhuanmei** [tinymce/tinymce-vue#5]
![image](https://user-images.githubusercontent.com/13001095/37590900-a793a10a-2ba4-11e8-8b1c-2167f3d09890.png)
I had downloaded the folder of Chinese, but I don't know the place of langs. There is my file:
![image](https://user-images.githubusercontent.com/13001095/37591287-fc9ae31a-2ba5-11e8-916a-dcdbf8f78aeb.png)

@spocke @fyrkant @jayarjo

**Comment by fyrkant** [comment]
When you are using TinyMCE cloud you have to use the [`language_url`](https://www.tinymce.com/docs/configure/localization/#language_url) setting to point to the language file on your server. Also, note that there is no shorthand setting for `language` and `language-url`, you will have to put it inside of the `init` object.

**Comment by banzhuanmei** [comment]
Thank you!
adding language_url in init is useful!
