### ISSUE TITLE
Add button after load

### ISSUE THREAD

**Issue by shaunc869** [tinymce/tinymce-vue#51]
I know with tinymce you can add a button after load, can this be done with this plugin as well and if so any tips to getting access to the editor post lost so I can do this? Thanks!

**Comment by fyrkant** [comment]
Can you specify what you mean with "after load"? You can't add a button after the editor has initialised, but you can add one to the editor by using the setup callback method in the init like this: 
```ts
<editor
  :init="{
    setup (editor) {
      editor.addButton('hello', {text: 'Yo'});
    }
  }"
/>
```

**Comment by SimonFc** [comment]
Closing this since it seems like the original question has been answered
