### ISSUE TITLE
`contextmenu` prop

### ISSUE THREAD

**Issue by mhyfritz** [tinymce/tinymce-vue#54]
Hi 👋 

Given that you already support passing `plugins` and `toolbar` as props, it would be great if you could add `contextmenu`.

Cheers,
Markus

**Comment by mhyfritz** [comment]
Nevermind, forgot that `contextmenu` is a plugin, so the prop does not make sense... 

Anyhow, thanks a lot for providing an official Vue component, much appreciated!

**Comment by fyrkant** [comment]
Yeah it would be a little weird to have a prop that only works with a plugin, but good idea anyway!
