### ISSUE TITLE
Error loading tinymce-vue

### ISSUE THREAD

**Issue by mayankjain34** [tinymce/tinymce-vue#59]
Hi all, 

I am getting errors when trying to load `timymce-vue` without cloud.

![image](https://user-images.githubusercontent.com/34234376/53171087-cb00a980-3607-11e9-9cbf-071a59d2ae4f.png)

Can you provide an example of how to use TinyMCE without cloud?

Thanks,
Mayank

**Comment by bartroodzant** [comment]
I have the same issue.

**Comment by mayankjain34** [comment]
Hi All, Is anyone got a chance to look into this? Thanks!

**Comment by mayankjain34** [comment]
I manage to fix it by simply hosting skins files. closing this.

**Comment by bartroodzant** [comment]
Are you using Webpack? Because if you are, could you please explain how you hosted the skin files on your local machine?

**Comment by choudewh** [comment]
> I manage to fix it by simply hosting skins files. closing this.

Could you please describe how to fix it?
