### ISSUE TITLE
how can I add forecolor button into toolbar?

### ISSUE THREAD

**Issue by zzzgit** [tinymce/tinymce-vue#60]
How can I add `forecolor` button into toolbar?
I tried add `forecolor` in the config, but there's no effect.

And also, it will be better if you can supply an official demo of the usage of this vue component.

**Comment by fyrkant** [comment]
Can you show how you are configurating the editor? `forecolor` seem to work as expected for me.

**Comment by zzzgit** [comment]
![image](https://user-images.githubusercontent.com/1060733/54334099-dcb1fb80-465f-11e9-8c00-fe0b8af473bd.png)

**Comment by zzzgit** [comment]
![image](https://user-images.githubusercontent.com/1060733/54334170-14b93e80-4660-11e9-9478-5ccad4313b00.png)

**Comment by lnewson** [comment]
@zzzgit `forecolor` is the name of the toolbar button, not the name of the plugin. The name of the plugin that provides that button is `textcolor`, so if you update your code to the following, you shouldn't get that error.
```
<el-editor :init="{plugins: 'wordcount textcolor'}"></el-editor>
```

In case it's helpful, here's the docs for the textcolor plugin in TInyMCE 4 which details the configuration for the `forecolor` toolbar button: https://www.tiny.cloud/docs-4x/plugins/textcolor/

**Comment by zzzgit** [comment]
now I see, thanks

**Comment by SimonFc** [comment]
Closing this since it appears that the original question has been answered
