### ISSUE TITLE
Spellchecker for tinymce-vue

### ISSUE THREAD

**Issue by avinashy1** [tinymce/tinymce-vue#61]
Hi Team,

I didn't find any event in the current documentation for spellchecker callback. In our current project we'are using tinymce-vue component with typescript.

The example stated in the docs https://www.tiny.cloud/docs/plugins/spellchecker/  is not compatible with the existing tinymce-vue component, as there is no way to define callbacks using the template as stated in the github page https://github.com/tinymce/tinymce-vue.

![image](https://user-images.githubusercontent.com/28036676/53784057-12f1cb80-3f3a-11e9-9b54-584227bd4a7e.png)

Can you help out in this.

Thanks
Avinash.

**Comment by fyrkant** [comment]
You can send in the same configuration to the init prop of the vue component as you would to the tinymce.init method.

**Comment by avinashy1** [comment]
@fyrkant ,

Yes i did the same. However as we are using tinymce-vue with typescript ,is there any event to handle the spellchecker functionality instead of passing callback function in the `init` method as some functions like `this.getWordCharPattern()`, `this.getLanguage()`  are getting compilation errors as `this`  keyword here refers to typescript vue class instead of tinymce instance.

![image](https://user-images.githubusercontent.com/28036676/53797639-915f6500-3f5c-11e9-9af6-3b1666de3790.png)

Thanks
Avinash.

**Comment by fyrkant** [comment]
You'll have to type the this of the function: https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters

**Comment by avinashy1** [comment]
Thanks @fyrkant
