### ISSUE TITLE
Please write all the parameters of the initial configuration item.

### ISSUE THREAD

**Issue by MrQiangHu** [tinymce/tinymce-vue#62]
For example, what do the following parameters mean?
        selector:   // ID
        height:  
        body_class:  
        object_resizing:  
        toolbar: 
        menubar: 
        plugins: ,
        end_container_on_empty_block: ,
        powerpaste_word_import: 'clean',
        code_dialog_height: 450,
        code_dialog_width: 1000,
        advlist_bullet_styles: 'square',
        advlist_number_styles: 'default',
        imagetools_cors_hosts: ['www.tinymce.com', 'codepen.io'],
        default_link_target: '_blank',
        link_title: false,
        nonbreaking_force_tab: true,
thank you

**Comment by SimonFc** [comment]
tinymce-vue is a wrapper for tinymce. If you wish to find out more about tinymce please refer to the [Docs](https://www.tiny.cloud/docs/). Thanks!
