### ISSUE TITLE
Getting an error thrown

### ISSUE THREAD

**Issue by deep0410** [tinymce/tinymce-vue#63]
theme.min.js:9
```
Uncaught Error: Node cannot be null or undefined
    at Object.Wn [as fromDom] (theme.min.js:9)
    at Hw.<anonymous> (theme.min.js:9)
    at bw.c.fire (tinymce.min.js?apiKey='####':9)
    at Hw.fire (tinymce.min.js?apiKey='####':9)
    at yx (tinymce.min.js?apiKey='####':9)
    at Cx.f.content_style.a (tinymce.min.js?apiKey='####':9)
    at tinymce.min.js?apiKey='####':9
    at tinymce.min.js?apiKey='####':9
```

And the editor goes blank.

**Comment by SimonFc** [comment]
Might be an issue with tinymce and not the tinymce-vue wrapper. See if you can reproduce the issue here: http://fiddle.tinymce.com/

**Comment by SimonFc** [comment]
Closing due to lack of response. Please open up a new detailed issue if you encounter the problem again!

**Comment by danvim** [comment]
I'm facing the same problem. The reproduction method is to have a button add an editor every time it's pressed.

**Comment by danvim** [comment]
I found out my problem. This package isn't compatible with https://www.npmjs.com/package/vue-fragment The problem is reproduced if I add the editors wrapped with fragments on button click.

**Comment by tempfirstuser** [comment]
I have the save issue:
```
[Vue warn]: Error in beforeDestroy hook: "Error: Node cannot be null or undefined"

found in

---> <Editor>
```
And stacktrace:

```
theme.min.js:9
---
remove tinymce.min.js:9
remove tinymce.min.js:9
beforeDestroy Editor.js:73
```
73 line of  Editor.js:73 contain this code:
`getTinymce().remove(this.editor);`

And this is whole code of method:
```
    beforeDestroy: function () {
        if (getTinymce() !== null) {
            getTinymce().remove(this.editor);
        }
    },
```
I get this issue when I push new router right after this code:
`self.$router.push({ name: 'some-route'});`

I was trying to add v-if following this example https://github.com/tinymce/tinymce-vue/issues/10#issuecomment-540996933 but it doesn't help. 

What else can I try?

**Comment by SimonFc** [comment]
@tempfirstuser Are you able to set up an example/reproduce the issue on this [CodeSandbox](https://codesandbox.io/s/9y95z5m40y?fontsize=14)? (It would help a lot to be able to see the whole picture of what you're trying to do) Thanks!

**Comment by tempfirstuser** [comment]
@SimonFc maybe later. I have fixed my issue. This comment https://github.com/tinymce/tinymce-vue/issues/10#issuecomment-380262238 was helpful. I have added 
`tinymce.EditorManager.execCommand('mceRemoveEditor', false, 'myEditor')` right before pushing to the router:

```
tinymce.EditorManager.execCommand('mceRemoveEditor', false, 'description');
self.$router.push({ name: 'some-route'});
```

I did not use "keep-alive" that is why I have added only 'mceRemoveEditor'.
