### ISSUE TITLE
how to use lang packages in .vue

### ISSUE THREAD

**Issue by anyclub** [tinymce/tinymce-vue#66]
```<template>
  <div class="tinyMce">
    <Editor
      v-model="content"
      :init="config"
    ></Editor>
    <div v-html="content"></div>
  </div>
</template>

<script>
import Editor from '@tinymce/tinymce-vue'

export default {
  name: 'TinyMCE',
  components: {
    Editor
  },
  data () {
    return {
      content: '',
      config: {
        language: 'zh_CN',
        language_url: '../assets/langs/zh_CN.js'
      }
    }
  }
}
</script>```

console error 

`Uncaught SyntaxError: Unexpected token <`

version: 
  "@tinymce/tinymce-vue": "^2.0.0"

lang packages from `https://www.tiny.cloud/get-tiny/language-packages/`

**Comment by anyclub** [comment]
I solved it, 
please close it

**Comment by Valterrsj** [comment]
Could you share how you solver it? I have the same problem

**Comment by guangshao** [comment]
> 我解决了，
> 请关闭它

请问你如何解决的可以分享一下吗

**Comment by SimonFc** [comment]
@Valterrsj Have you read the Docs on the subject? [language](https://www.tiny.cloud/docs/configure/localization/#language) and [language_url](https://www.tiny.cloud/docs/configure/localization/#language_url)

Let me know if you still have the same problem and I'll see if I can help you. It is probably an issue related to your setup though if you're unable to load your language packs.

**Comment by elvishuges** [comment]
> I solved it,
> please close it

can you share the solution ?  please  !!
