### ISSUE TITLE
how can I use my own icons instead of those in toolbar?  

### ISSUE THREAD

**Issue by anotherlover** [tinymce/tinymce-vue#68]
For example, carry the icons in MS-office  into tinymce, so make tinymce look like Word-editor software

**Comment by SimonFc** [comment]
I'm assuming that you're using TinyMCE 5. The documentation for this is still in progress, although you might be interested in the discussion over here(the same applies to tinymce-vue):
https://github.com/tinymce/tinymce/issues/4887
https://github.com/tinymce/tinymce/issues/4887#issuecomment-475503714
