### ISSUE TITLE
Image/Links Popup textinput are not clickable when tinymce within bootstrap modal.

### ISSUE THREAD

**Issue by riddhiparekh** [tinymce/tinymce-vue#69]
Only save and cancel buttons are working. None of other inputs are clickable inside the popup.
I know this is some issue related to focus but i don't know how to fix it in vue.
What i found until now as solution is to add this.
$(document).on('focusin', function(e) {
    if ($(event.target).closest(".mce-window").length) {
        e.stopImmediatePropagation();
    }
});
[Fiddle](http://jsfiddle.net/y9wgdfdw/6/) to this.

![Screenshot from 2019-03-20 11-24-30](https://user-images.githubusercontent.com/45178176/54662161-145af080-4b03-11e9-9c6d-9ff38b00755d.png)

If i close the popup that is behind then this starts working.

**Comment by SimonFc** [comment]
Is that the correct fiddle you attached? It seems to be using TinyMCE 4.0

**Comment by SimonFc** [comment]
You're spot on with the workaround which actually is the official solution!
https://www.tiny.cloud/docs/integrations/bootstrap/
