### ISSUE TITLE
How to change tinymce configuration / settings dynamically?

### ISSUE THREAD

**Issue by hjelperne** [tinymce/tinymce-vue#71]
Hi I am trying to achieve changing the tinymce configuration (passed in on :init) dynamically at runtime.
I am not using cloud - but have made tinymce globally available by import "tinymce/tinymce"  in main.js etc..

So far I got this working with:

**In the template the relevant stuff is:**
A)  a selector (drop-down based on vue bootstrap - not relevant) calling the reInit() function 
B) The Vue Tinymce editor:

  <b-form-select id="configselector" v-model="configselector.selected"
                                       :options="configselector.options" @change="reInit()"/>
      <editor ref="tinyMceEditor" v-model="content" :init="this.configselector.selected" @onChange="handlerfunction"></editor>

**and in the data section of the Vue file:**

` data() {
      return {
       content: '<b>content here</b>',
        configselector:{
                        selected: tinyMceDefaultConfig,
                        options: [
                            {value: tinyMceDefaultConfig, text: 'default'},
                            {value: tinyMceMiniConfig, text: 'mini'},
                        ]
                    },
tinyMceDefaultConfig = {
    height: '100%',
  // other settings...
},
tinyMceMiniConfig{
  height: 200,
}
      }
}`

**and in the methods section of the Vue file:**

`methods:{
 reInit: function () {
               this.$refs.tinyMceEditor.editor.remove();
               this.$refs.tinyMceEditor.editor = new tinymce.Editor(this.$refs.tinyMceEditor.editor.id, this.configselector.selected, tinymce.EditorManager);
               this.$refs.tinyMceEditor.editor.render();
            }
}`

Now this approach apparently works - **BUT** the editor is no longer reactive - and the v-model property no longer gets updated. The id of the  $refs.tinyMceEditor.editor appears to be the same after - but having {{content}} in the template no longer gets updated.

Does anyone have any idea how to change the tinymce config properly (dynamically) - using Vue tinymce - AND "staying reactive" / keeping the v-model bound??

Perhaps this should be a feature request - having a  this.$refs.tinyMceEditor.editor.setSettings(newConfig) that would automatically call a "refresh on the ui" or something - if this is not at all possible in todays version ("@tinymce/tinymce-vue": "^2.0.0").

PS: I have even tried a dirty hack of having 2  <editor> instances, each wrapped in a conditional div v-if="condition" (with different :init configs from start) and switching between them (by changing condition true/false) - but this doesn't either work because of how the toolbar gets rendered - it just doesnt work the way you would expect- the toolbar gets rendered - despite being inside the false condition div... What??

**Any help would be greatly appreciated.** 
Please let me know if I can assist in any way by providing more info if anything is unclear.
Hope some tinymce genius out there will be able to assist. :-)

Best regards,
H

**Comment by SimonFc** [comment]
The problem with the approach of reaching into the Vue-wrapper and initializing the editor directly is that the bindings between the vue-wrapper and the editor gets broken. When the vue-wrapper is initalized some event binding occurs, and simply put, that process would need to run again.

You're right in that the editor doesn't support changing the init configuration dynamically and that is because the editor itself has a process that runs once on initial setup - just like the Vue-wrapper has.

The simplest way to make sure that everything gets initialized correctly is to re-initialize the vue-component, which then would take care of the editor. I found a [post](http://michaelnthiessen.com/force-re-render/) which I think might be of help. The alternative with the `:key` attribute should work in your case, although there might be some even better way to do it in.

It's difficult to read the code you have when you're not formatting it in a code block but if you could set up a jsfiddle with your problem I would be happy to take a look at it!

**Comment by jscasca** [comment]
Hey @hjelperne 

As Simon mentioned, by using the reference to the editor you will be breaking the bindings and the editor will lose its reactivity. The best way to go forward in this case would be to reinitialize the wrapper.

If you follow the link posted by Simon you'll see some ways to enforce re-rendering of components. By enforcing the re-rendering the component will run the init routine again achieving what you want.
One way of doing so is by changing the `key` property of the component.
E.G.:
```
<select id="configselector" v-model="configselector.selected" @change="reInit()">
      <option v-for="option in configselector.options" v-bind:key="option.text" v-bind:value="option.value">{{ option.text }}</option>
    </select>
    <editor :key="tinyId" v-model="content" :init="this.configselector.selected" />
```
The `reInit` code only needs to change the key value in order for Vue to re-render the component as follows:
```
export default {
  name: 'App',
  data() {
    var tinyMceDefaultConfig = {height: 600};
    var tinyMceMiniConfig = {height: 200};
    return {
      tinyId: 0,
      content:'New content',
      configselector: {
        selected: tinyMceDefaultConfig,
        options: [ 
          {value: tinyMceDefaultConfig, text: 'default'}, 
          {value: tinyMceMiniConfig, text: 'mini'}, ]
      }
    };
  },
  components: {
    HelloWorld,
    'editor': Editor
  },
  methods: {
    reInit() {
      this.tinyId += 1;
    }
  }
}
```

Let me know if this helps. 

In the meantime I will close the ticket but I'm happy to reopen it if needed.
