### ISSUE TITLE
Cannot resize tables and images after update

### ISSUE THREAD

**Issue by mhyfritz** [tinymce/tinymce-vue#77]
Hi 👋 

I just updated to `tinymce` v5.0.3 and `tinymce-vue` v2.0.0 and lost the ability to resize tables and images -- if I focus them, the corresponding controls/drag handlers do not appear anymore. If I use plain TinyMCE without the Vue wrapper this works.

I am providing a minimal example below, but also created a [sandbox on CodeSandbox](https://codesandbox.io/s/qlp7o9pk79).

Cheers,
Markus

```vue
<template>
  <Editor plugins="image table" toolbar="image table" />
</template>

<script>
import "tinymce/tinymce";
import "tinymce/themes/silver";
import "tinymce/plugins/image";
import "tinymce/plugins/table";
import Editor from "@tinymce/tinymce-vue";

export default {
  name: "App",
  components: {
    Editor
  }
};
</script>

<style src="tinymce/skins/ui/oxide/skin.min.css"></style>
```

**Comment by SimonFc** [comment]
Hi,
There are normally three css files that normally are to be included. UI skin, which you have, and two content-css files.
```
```
`skins/ui/oxide/skin.min.css` (which you have) `skins/ui/oxide/content.min.css`
