### ISSUE TITLE
tinymce on nuxtjs gives error everytime i leave the page

### ISSUE THREAD

**Issue by khofesh** [tinymce/tinymce-vue#80]
Hey, I'm using tinymce-vue on nuxtjs and set tinymce available globally as instructed [here](https://github.com/tinymce/tinymce-vue#loading-tinymce-by-yourself).
I'm currently trying to set content inside the editor

Here's my setup:
```
<template>
  <div>
    <no-ssr>
      <editor
        id="editor"
        plugins="link paste image advlist autolink anchor preview table media print insertdatetime hr lists visualblocks"
        :init="{height: 600, width: 600}"
        toolbar="undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor table"
        :initial-value="$store.getters.getContentEditor"
        @onChange="onEditorChange"
      />
    </no-ssr>
  </div>
</template>
```

```
<script>
import Editor from '@tinymce/tinymce-vue'

if (process.client) {
  require('tinymce/tinymce')
  require('tinymce/themes/silver/theme')
  require('tinymce/plugins/paste')
  require('tinymce/plugins/link')
  require('tinymce/plugins/image')
  require('tinymce/plugins/advlist')
  require('tinymce/plugins/autolink')
  require('tinymce/plugins/anchor')
  require('tinymce/plugins/preview')
  require('tinymce/plugins/bbcode')
  require('tinymce/plugins/charmap')
  require('tinymce/plugins/code')
  require('tinymce/plugins/codesample')
  require('tinymce/plugins/colorpicker')
  require('tinymce/plugins/media')
  require('tinymce/plugins/print')
  require('tinymce/plugins/fullpage')
  require('tinymce/plugins/table')
  require('tinymce/plugins/insertdatetime')
  require('tinymce/plugins/hr')
  require('tinymce/plugins/lists')
  require('tinymce/plugins/visualblocks')
}

export default {
  components: {
    editor: Editor
  },
  data() {
    return {
      contentEditor: 'test'
    }
  },
  updated() {
    this.setContent()
  },
  beforeDestroy() {
    const tinymce = require('tinymce/tinymce')
    tinymce.remove('editor')
  },
  methods: {
    onEditorChange() {
      if (process.client) {
        const tinymce = require('tinymce/tinymce')
        try {
          const content = tinymce.get('editor').getContent()
          return this.$store.dispatch('setContentEditor', content)
        } catch (err) {
          console.log('error in onEditorChange: ', err)
        }
      }
    },
    setContent() {
      const tinymce = require('tinymce/tinymce')

      if (
        tinymce.activeEditor !== null &&
        'parser' in tinymce.activeEditor &&
        'parse' in tinymce.activeEditor.parser
      ) {
        // When you first load, you rely on the content second times in V-model to use the setContent method to assign.
        try {
          tinymce
            .get('editor')
            .setContent(this.$store.getters.getContentEditor)
          tinymce.get('editor').focus()
          tinymce
            .get('editor')
            .selection.select(tinymce.get('editor').getBody(), true)
          tinymce.get('editor').selection.collapse(false)
        } catch (err) {
          console.log('error in setContent: ', err)
        }

        // console.log('set content')
      }
    }
  }
}
</script>
```

I'm using `if (process.client){}` to avoid error window is not defined, 
` :initial-value="$store.getters.getContentEditor"` to set content every time tinymce was created.
But, everytime I leave the page, I get error saying `error in onEditorChange:  TypeError: "tinymce.get(...) is null"`

I know it came from onEditorChange function in methods.
what happens, could you provide me with the solution??
Oh, and same thing happens if I used `tinymce.activeEditor` inside onEditorChange function
thanks in advance

**Comment by khofesh** [comment]
Oh, and same thing happens if I used `tinymce.activeEditor` inside onEditorChange function

**Comment by SimonFc** [comment]
Hi! I see that you're requiring tinymce multiple times although this is only necessary to do once. The first time you've done that a global object called tinymce will be created and you should have access to it everywhere. See if you can remove all `require('tinymce/tinymce')` except the first one and if that solves your issue.

**Comment by khofesh** [comment]
> Hi! I see that you're requiring tinymce multiple times although this is only necessary to do once. The first time you've done that a global object called `tinymce` will be created and you should have access to it everywhere. See if you can remove all `require('tinymce/tinymce')` except the first one and if that solves your issue.
> 
> Your `process.client` check should probably be one level higher up as well(and only one instead of multiple). So if you don't have the window/document then don't initialize the editor component at all.
> 
> Let me know if you got any questions!

alright, so i removed multple `require('tinymce/tinymce')` and declare tinymce outside if statement 

```
let tinymce
if (process.client) {
  tinymce = require('tinymce/tinymce')
  require('tinymce/themes/silver/theme')
  require('tinymce/plugins/paste')
  require('tinymce/plugins/link')
  require('tinymce/plugins/image')
  require('tinymce/plugins/advlist')
  require('tinymce/plugins/autolink')
  require('tinymce/plugins/anchor')
  ...
}
```

and I removed `if (process.client) {}` from onEditorChange method:

```
onEditorChange() {
      try {
        const content = tinymce.get('editor').getContent()
        return this.$store.dispatch('setContentEditor', content)
      } catch (err) {
        console.log('error in onEditorChange: ', err)
      }
    },
```

the error persists
```
error in onEditorChange: TypeError: "tinymce.get(...) is null"
    NuxtJS 57
   
    onEditorChange 
    invokeWithErrorHandling
    invoker
    bindHandlers
    fire
    fire
    add
    addNonTypingUndoLevel
    fire
    fire
    save
    remove$6
    remove
    remove
    beforeDestroy
    invokeWithErrorHandling
    callHook
    $destroy
    destroy
    invokeDestroyHook
    invokeDestroyHook
    patch
    $destroy
    destroy
    invokeDestroyHook
    invokeDestroyHook
    invokeDestroyHook
    invokeDestroyHook
    patch
    $destroy
    destroy
    invokeDestroyHook
    invokeDestroyHook
    invokeDestroyHook
    patch
    $destroy
    destroy
    invokeDestroyHook
    patch
    $destroy
    destroy
    invokeDestroyHook
    invokeDestroyHook
    invokeDestroyHook
    patch
    $destroy
    destroy
    invokeDestroyHook
    removeVnodes
    patch
    _update
    updateComponent
    get
    run
    flushSchedulerQueue
    nextTick
    flushCallbacks
```

**Comment by SimonFc** [comment]
So it seems like the editor is being initialized for you but I can't see what would make `tinymce` undefined  inside your onEditorChange handler. It would be great if you could reproduce the issue [here](https://codesandbox.io/s/9y95z5m40y?fontsize=14)

As an alternative to how you're accessing the editor you should be able to do
```
onEditorChange (e, editor) {
  // editor.getContent();
}
```

**Comment by khofesh** [comment]
> So it seems like the editor is being initialized for you but I can't see what would make `tinymce` undefined inside your onEditorChange handler. It would be great if you could reproduce the issue [here](https://codesandbox.io/s/9y95z5m40y?fontsize=14)
> 
> As an alternative to how you're accessing the editor you should be able to do
> 
> ```
> onEditorChange (e, editor) {
>   // editor.getContent();
> }
> ```
> 
> Hmm I see that this isn't documented in the readme so I'll add that.

I tried the alternative you suggested and it doesn't throw the error anymore.
```
onEditorChange(e, editor) {
      try {
        const content = editor.getContent()
        return this.$store.dispatch('setContentEditor', content)
      } catch (err) {
        console.log('error in onEditorChange: ', err)
      }
    }
```

Thanks
