### ISSUE TITLE
Related insert content into editor

### ISSUE THREAD

**Issue by vaibhavFullStackDev** [tinymce/tinymce-vue#85]
Actual thing is that how to triggered editors event for inserting text in editor from outside the editor in vue

**Comment by SimonFc** [comment]
Is this a question? If you're looking for an api there's [editor.setContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#setcontent) and [selection.setContent](https://www.tiny.cloud/docs/api/tinymce.dom/tinymce.dom.selection/#setcontent). Let me know if you're looking for something else!

**Comment by vaibhavFullStackDev** [comment]
ohh i got solution, actually it is about "mceInsertContent"

**Comment by xlcrr** [comment]
How did you insert content?

**Comment by xlcrr** [comment]
Here, copy paste not difficult 

```
add(content) {
   tinymce.activeEditor.insertContent(content);
}
```
