### ISSUE TITLE
regarding copy/paste

### ISSUE THREAD

**Issue by vaibhavFullStackDev** [tinymce/tinymce-vue#86]
Scenario: when copy from libreoffice/excel file to editor, content not retain formatting/style
Is there any solution?

**Comment by SimonFc** [comment]
The [paste](https://www.tiny.cloud/docs/plugins/paste/) or [powerpaste](https://www.tiny.cloud/docs/plugins/powerpaste/) plugin should be able to help you with this.

I'll close this issue but let me know you have any questions!

**Comment by vaibhavFullStackDev** [comment]
thanks @SimonFc for your suggestion.
I am done, no more questions..
