### ISSUE TITLE
tiny + vue draggable

### ISSUE THREAD

**Issue by irbis999** [tinymce/tinymce-vue#89]
**What is the current behavior?**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-vue`?**

**Comment by irbis999** [comment]
When works together with vue-draggable editor looses its content when drag finishes
https://monosnap.com/file/HvCRvJdyaP6XcdCpbcv0UakUMVLrH4

**Comment by hafung** [comment]
I just got the same problem like you do.....  and don't know how to debug it, sign~.... please let me know if you find out the solution. thanks!

**Comment by SimonFc** [comment]
Hi! Unfortunately, this is due to a native iframe behavior and is nothing we can do anything about. [Related issue](https://github.com/tinymce/tinymce-angular/issues/76#issuecomment-484117388) To summarize: Tiny's iframe will re-render whenever it's moved within the DOM.
