### ISSUE TITLE
Loading tinymce myself

### ISSUE THREAD

**Issue by rajneeshm49** [tinymce/tinymce-vue#90]
Hii In order not to load it from cloud and no need to call tinymce.init as discussed in issue 11, here is how Iam doing it.   

     <template>
        <editor :init="initValue" id="evidence-editor" class="tinymce"></editor>
    </template>
    <script>
        import Editor from "@tinymce/tinymce-vue";
        import 'tinymce';
        import 'tinymce/themes/modern/theme';
        import 'tinymce/plugins/link';

    export default {
        name: "alchemy-tinymce-editor",
        components: {
        editor: Editor
    },
    data() {
        return {
           initValue: {
                selector: ".tinymce",
                theme: 'modern',
                menubar: false,
                plugins: ['link'],
                skin_url: '/skins/lightgray',
                branding: false,
                toolbar: [ 'bold italic underline removeformat' ]
      }
Am I doint something wrong in this. Its still not loading. I have copied the skins folder - 

> cp -r node_modules/tinymce/skins skins

**Comment by Cryde** [comment]
It's because Editor will try to get the "global" tinymce... (and only global)
So you will have to register your tinymce as global (depending on your build tool)
I did something like that : 
```
    import tinymce from 'tinymce';
    window.tinymce = tinymce; 
    import Editor from "@tinymce/tinymce-vue";
```
I don't understand why they did that.

**Comment by sushiljic** [comment]
For the nuxt ,
Below is my setting,
tinymce.js as plugin


          `import Vue from 'vue'
           import TinyMCE from '@tinymce/tinymce-vue'
           import 'tinymce/tinymce'
           import 'tinymce/themes/silver'


           Vue.component('tiny-mce', TinyMCE)
`
which allows me to load the TinyMCE from the npm.

**Comment by SimonFc** [comment]
Thanks for the explanation @sushiljic  I'll close this issue since it appears to be solved.
@rajneeshm49 Let me know if you're still unable to self-host and I'll see if I can help you.
