### ISSUE TITLE
Which TinyMCE Editor does this wrap for IE11 support?

### ISSUE THREAD

**Issue by davewallace** [tinymce/tinymce-vue#92]
**Is your feature request related to a problem? Please describe.**
I'm unsure if this component is a thin-wrapper for TinyMCE that supports IE11?

 **Describe the solution you'd like**
Confirmation of browser support.

**Comment by SimonFc** [comment]
TinyMCE supports IE11 ([see here](https://www.tiny.cloud/docs/general-configuration-guide/system-requirements/#browsercompatibility)) and the same seems to be true for Vue given that you compile to es5 or polyfill. So the answer to your question is a yes!
