### ISSUE TITLE
一个页面怎么加载多个tinymce

### ISSUE THREAD

**Issue by 309893147** [tinymce/tinymce-vue#94]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

 **Describe the solution you'd like**

 **Describe alternatives you've considered**

**Comment by 309893147** [comment]
how to do

**Comment by SimonFc** [comment]
How to do what? Please leave a description of your issue in English, thanks!

**Comment by fralonra** [comment]
Translation: How to init multiple tinymce in one page?

**Comment by SimonFc** [comment]
Have multiple instances of the editor in your template? Let me know if there's any unexpected behavior with this but as of now I'm assuming that this answers the question
```
<tinymce-editor></tinymce-editor>
<tinymce-editor></tinymce-editor>
```
