### ISSUE TITLE
3.0.0 break npm run with vue 2.x

### ISSUE THREAD

**Issue by mymbrooks** [tinymce/tinymce-vue#95]
**What is the current behavior?**
With last update version 3.0.0, I use npm run with my Vue project, get error:
* @tinymce/tinymce-vue in ./src/main.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/inspection/recieve.vue?vue&type=script&lang=js& and 4 others
To install it, you can run: npm install --save @tinymce/tinymce-vue

I found a temp solution:
Edit the package.json in tinymce-vue 3.0.0:
..........
  "main": "lib/cjs/index.js",
  "module": "lib/es2015/index.js",
..........

to

..........
  "main": "lib/cjs/main/ts/index.js",
  "module": "lib/es2015/main/ts/index.js",
..........

now npm run works fine.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**
Install latest version: npm install --save @tinymce/tinymce-vue
then run: npm run ...

**What is the expected behavior?**
No error

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
tinymce-vue 3.0.0
node -v & npm -v
v12.8.1
6.10.2
Windows 10 19h1 10.0.18362.295
Google Chrome | 78.0.3880.4 (Official Build) dev (64-bit) (cohort: Dev)

Before 3.0.0 everything works fine

**Comment by SimonFc** [comment]
The temp solution you have found is the actual solution, the paths are wrong. Thanks for letting us know about it! A new release will be out soon

**Comment by SimonFc** [comment]
A fix is published under 3.0.1

**Comment by MakerLZZ** [comment]
That's so terrible. Because of this problem, I checked the data for 3 hours.
