### ISSUE TITLE
Plugin Directory for adding custom plugins?

### ISSUE THREAD

**Issue by FilipePrates** [tinymce/tinymce-vue#98]
Hey, in the 'normal' tinymce, aparently there is a directory "tinymce/jscripts/tiny_mce/plugins", where you can edit and add new custom plugins by dropping on this directory, as It says on the installation of this plugin https://github.com/moonwave99/TinyMCELaTeXPlugin
But on this vue-accessible version I can't find this directory, am I being dumb or is there no way to add this custom plugin to the editor?

**Comment by lnewson** [comment]
@FilipePrates it looks like that plugin only works with TinyMCE 3, as per https://github.com/moonwave99/TinyMCELatexPlugin/issues/1 and unfortunately the integration only works with TinyMCE4 and 5.

To answer the other question of where to add custom plugins, the place to add plugins in the TinyMCE 4 and 5 self-hosted download is `tinymce/plugins/` or if you're using cloud then you'd either need to bundle the plugin in your app or host the plugin somewhere yourself and then use the [external_plugins](https://www.tiny.cloud/docs/configure/integration-and-setup/#external_plugins) setting to specify the location.
